const AMBIENCE_PROFILES=Object.freeze({
  "fluorescent-hum":{frequencies:[50,100,150],wave:"triangle",noiseFrequency:115,noiseGain:.1,oscillatorGain:.045},
  "unstable-grid":{frequencies:[47,94,188],wave:"sawtooth",noiseFrequency:176,noiseGain:.075,oscillatorGain:.032},
  "hollow-rooms":{frequencies:[31,63],wave:"sine",noiseFrequency:72,noiseGain:.045,oscillatorGain:.026},
  silent:{frequencies:[],noiseGain:0,oscillatorGain:0},
});

export function getAmbienceProfile(id){return AMBIENCE_PROFILES[id]??AMBIENCE_PROFILES["fluorescent-hum"];}

export class BackroomsAudio {
  constructor(){this.context=null;this.master=null;this.sources=[];this.running=false;this.following=false;this.muted=false;this.levelAudio={ambience:"fluorescent-hum",volume:1,transitionSeconds:1.4,events:[]};this.levelBounds=null;this.ambience=null;this.nextEventAt=Infinity;}
  async start(){
    if(this.running){if(this.context.state==="suspended")await this.context.resume();return;}
    this.context=new AudioContext();await this.context.resume();this.running=true;this.master=this.context.createGain();this.master.gain.value=this.muted?.0001:.22;this.master.connect(this.context.destination);this.#transitionAmbience(this.levelAudio);
  }
  setLevelAudio(config={},bounds=null){this.levelAudio={ambience:config.ambience??"fluorescent-hum",volume:Math.max(0,Number(config.volume??1)),transitionSeconds:Math.max(.05,Number(config.transitionSeconds??1.4)),events:Array.isArray(config.events)?config.events:[]};this.levelBounds=bounds?{...bounds}:null;this.nextEventAt=this.#nextEventTime(performance.now());if(this.context)this.#transitionAmbience(this.levelAudio);}
  #nextEventTime(now){if(!this.levelAudio.events.length)return Infinity;const minimum=Math.min(...this.levelAudio.events.map(event=>Number(event.minDelay??12))),maximum=Math.max(...this.levelAudio.events.map(event=>Number(event.maxDelay??28)));return now+(minimum+Math.random()*Math.max(0,maximum-minimum))*1000;}
  #noiseBuffer(){const length=this.context.sampleRate*2,buffer=this.context.createBuffer(1,length,this.context.sampleRate),data=buffer.getChannelData(0);let brown=0;for(let i=0;i<length;i++){brown=(brown+.018*(Math.random()*2-1))/1.018;data[i]=brown*3;}return buffer;}
  #buildAmbience(config){const profile=getAmbienceProfile(config.ambience),bus=this.context.createGain(),filter=this.context.createBiquadFilter(),sources=[];bus.gain.value=.0001;bus.connect(this.master);filter.type="lowpass";filter.frequency.value=config.ambience==="hollow-rooms"?310:700;filter.connect(bus);const track=source=>{sources.push(source);this.sources.push(source);source.onended=()=>{const globalIndex=this.sources.indexOf(source);if(globalIndex>=0)this.sources.splice(globalIndex,1);const localIndex=sources.indexOf(source);if(localIndex>=0)sources.splice(localIndex,1);if(!sources.length){filter.disconnect();bus.disconnect();}};};profile.frequencies.forEach((frequency,index)=>{const oscillator=this.context.createOscillator(),gain=this.context.createGain();oscillator.type=index?profile.wave:"sine";oscillator.frequency.value=frequency;gain.gain.value=profile.oscillatorGain/(index+1);oscillator.connect(gain).connect(filter);oscillator.start();track(oscillator);});if(profile.noiseGain){const noise=this.context.createBufferSource(),noiseFilter=this.context.createBiquadFilter(),noiseGain=this.context.createGain();noise.buffer=this.#noiseBuffer();noise.loop=true;noiseFilter.type="bandpass";noiseFilter.frequency.value=profile.noiseFrequency;noiseGain.gain.value=profile.noiseGain;noise.connect(noiseFilter).connect(noiseGain).connect(bus);noise.start();track(noise);}return{bus,sources};}
  #transitionAmbience(config){const now=this.context.currentTime,fade=config.transitionSeconds,next=this.#buildAmbience(config);next.bus.gain.setValueAtTime(.0001,now);next.bus.gain.exponentialRampToValueAtTime(Math.max(.0001,config.volume),now+fade);if(this.ambience){this.ambience.bus.gain.cancelScheduledValues(now);this.ambience.bus.gain.setValueAtTime(Math.max(.0001,this.ambience.bus.gain.value),now);this.ambience.bus.gain.exponentialRampToValueAtTime(.0001,now+fade);if(!this.ambience.sources.length)this.ambience.bus.disconnect();for(const source of [...this.ambience.sources]){try{source.stop(now+fade+.06);}catch{}}}this.ambience=next;}
  #output(position){if(!position||!this.context.createPanner)return this.master;const panner=this.context.createPanner();panner.panningModel="HRTF";panner.distanceModel="inverse";panner.refDistance=2;panner.maxDistance=35;panner.rolloffFactor=1.2;if(panner.positionX){panner.positionX.value=position.x;panner.positionY.value=position.y??1;panner.positionZ.value=position.z;}else panner.setPosition(position.x,position.y??1,position.z);panner.connect(this.master);return panner;}
  playEvent(type,position){if(!this.context||!this.master)return;const now=this.context.currentTime,output=this.#output(position),frequencies=type==="distant-step"?[58,46]:type==="metal-pop"?[510]:[165,54];frequencies.forEach((frequency,index)=>{const oscillator=this.context.createOscillator(),gain=this.context.createGain(),delay=index*(type==="distant-step"?.22:.045),duration=type==="metal-pop"?.16:.32;oscillator.type=type==="metal-pop"?"triangle":type==="buzz-drop"?"sawtooth":"sine";oscillator.frequency.setValueAtTime(frequency,now+delay);oscillator.frequency.exponentialRampToValueAtTime(Math.max(20,frequency*.58),now+delay+duration);gain.gain.setValueAtTime(.0001,now+delay);gain.gain.exponentialRampToValueAtTime(type==="metal-pop"?.12:.07,now+delay+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+delay+duration);oscillator.connect(gain).connect(output);oscillator.start(now+delay);oscillator.stop(now+delay+duration+.02);});}
  update(now,listenerPosition,bounds=this.levelBounds){if(!this.context)return;const listener=this.context.listener;if(listenerPosition){if(listener.positionX){listener.positionX.value=listenerPosition.x;listener.positionY.value=listenerPosition.y??1.7;listener.positionZ.value=listenerPosition.z;}else listener.setPosition(listenerPosition.x,listenerPosition.y??1.7,listenerPosition.z);}if(now<this.nextEventAt||!this.levelAudio.events.length)return;const event=this.levelAudio.events[Math.floor(Math.random()*this.levelAudio.events.length)],position=event.spatial!==false&&bounds?{x:bounds.minX+Math.random()*(bounds.maxX-bounds.minX),y:1,z:bounds.minZ+Math.random()*(bounds.maxZ-bounds.minZ)}:null;this.playEvent(event.type??"distant-step",position);this.nextEventAt=this.#nextEventTime(now);}
  shiftTimeline(milliseconds){const delta=Math.max(0,Number(milliseconds)||0);if(Number.isFinite(this.nextEventAt))this.nextEventAt+=delta;}
  electrical(){if(!this.context||!this.master)return;const now=this.context.currentTime,o=this.context.createOscillator(),g=this.context.createGain();o.type="sawtooth";o.frequency.setValueAtTime(180,now);o.frequency.exponentialRampToValueAtTime(45,now+.45);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.18,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+.5);o.connect(g).connect(this.master);o.start(now);o.stop(now+.52);}
  doorHandle(){if(!this.context||!this.master)return;const now=this.context.currentTime,o=this.context.createOscillator(),g=this.context.createGain();o.type="square";o.frequency.setValueAtTime(185,now);o.frequency.exponentialRampToValueAtTime(92,now+.055);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.11,now+.004);g.gain.exponentialRampToValueAtTime(.0001,now+.075);o.connect(g).connect(this.master);o.start(now);o.stop(now+.08);}
  doorCreak(){if(!this.context||!this.master)return;const now=this.context.currentTime,o=this.context.createOscillator(),filter=this.context.createBiquadFilter(),g=this.context.createGain();o.type="sawtooth";o.frequency.setValueAtTime(74,now);o.frequency.linearRampToValueAtTime(112,now+.48);o.frequency.linearRampToValueAtTime(67,now+.95);filter.type="bandpass";filter.frequency.value=430;filter.Q.value=5;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.045,now+.08);g.gain.setValueAtTime(.035,now+.68);g.gain.exponentialRampToValueAtTime(.0001,now+1);o.connect(filter).connect(g).connect(this.master);o.start(now);o.stop(now+1.02);}
  setFollowing(value){if(value===this.following)return;this.following=value;if(!value||!this.context||!this.master)return;const now=this.context.currentTime;[0,.065].forEach((delay,index)=>{const o=this.context.createOscillator(),g=this.context.createGain();o.type="triangle";o.frequency.value=index?1568:1175;g.gain.setValueAtTime(.0001,now+delay);g.gain.exponentialRampToValueAtTime(.16,now+delay+.008);g.gain.exponentialRampToValueAtTime(.0001,now+delay+.095);o.connect(g).connect(this.master);o.start(now+delay);o.stop(now+delay+.11);});}
  mute(value){this.muted=Boolean(value);if(this.master)this.master.gain.setTargetAtTime(this.muted?.0001:.22,this.context.currentTime,.04);}
  stop(){if(!this.context)return;for(const source of this.sources){try{source.stop();}catch{}}this.sources.length=0;this.following=false;this.ambience=null;const context=this.context;this.context=null;this.master=null;this.running=false;if(context.state!=="closed")void context.close();}
}
