import * as THREE from "../vendor/three.module.min.js";
import {findMazePath} from "./maze.js";
import {BackroomsAudio} from "./audio.js";
import {PLAYER,CAMERA,ARCHITECTURE,RENDERING,INTERACTION} from "./config.js";
import {getLevelConfig} from "./levels/index.js";
import {LevelManager} from "./systems/level-manager.js";
import {TransitionManager} from "./systems/transition-manager.js";
import {createDoorAssembly,createDoorHeadWall,DoorController,HINGE_SIDES,SWING_DIRECTIONS} from "./systems/door.js";
import {createItem,expandObjectRules} from "./systems/item-registry.js";
import {createLevelLighting} from "./systems/level-lighting.js";
import {CreatureManager} from "./systems/creature-registry.js";
import {circleIntersectsMeshes} from "./systems/collision.js";
import {updateWallVisibility} from "./systems/wall-visibility.js";
import {calculateInteractionLayout,shouldShowInteractionLabel} from "./systems/interaction-layout.js";
import {INPUT_ACTIONS} from "./systems/input-bindings.js";
import {inputActionLabel,refreshInputLabels} from "./systems/input-labels.js";
import {InputManager} from "./systems/input-manager.js";
import {loadInputPreferences} from "./systems/input-preferences.js";
import {ControlsPanel} from "./systems/controls-panel.js";
import {disposeObjectTree} from "./systems/resource-disposal.js";
import {snapshotItem,restoreItem} from "./systems/item-persistence.js";
import {createEmptyLevelSave,createExplorationSave,migrateExplorationSave} from "./systems/save-schema.js";
import {resolveRestoredPlayerPosition} from "./systems/save-restoration.js";
import {AutosaveController,createExplorationSaveStorage} from "./systems/save-storage.js";
import {findSafeGuideSpawn} from "./systems/guide-spawn.js";
import {loadOptionalDebug} from "./systems/optional-debug.js";
import {getLocale,subscribeLocale,translate as t} from "./systems/i18n.js";
import {localizeItem} from "./systems/item-localization.js";

const $=selector=>document.querySelector(selector);
const home=$("#home"),game=$("#game"),viewport=$("#viewport"),prompt=$("#prompt"),interaction=$("#interaction"),radialMenu=$("#radial-menu"),notice=$("#notice"),items=$("#items"),objective=$("#objective"),levelLabel=$("#level"),seedLabel=$("#seed"),inventoryEl=$("#inventory"),inventoryIndex=$("#inventory-index"),thirstEl=$("#thirst"),hungerEl=$("#hunger"),timeEl=$("#time"),traversedEl=$("#traversed"),modal=$("#modal"),modalTitle=$("#modal-title"),modalText=$("#modal-text"),pauseMenu=$("#pause-menu"),continueButton=$("#continue-game"),deleteSaveButton=$("#delete-save"),saveSummary=$("#save-summary"),saveStatus=$("#save-status"),controlsPanel=new ControlsPanel(),saveStorage=createExplorationSaveStorage();
let cleanupGame=null;
refreshInputLabels(document,controlsPanel.preferences);
controlsPanel.subscribe(event=>{if(event.type==="change")refreshInputLabels(document,event.preferences);});

function showNotice(text,duration=3000){notice.textContent=text;notice.hidden=false;clearTimeout(showNotice.timer);showNotice.timer=setTimeout(()=>notice.hidden=true,duration);}

function formatDuration(seconds){const minutes=Math.floor(seconds/60),hours=Math.floor(minutes/60);return hours?t("game.duration.hours",{hours,minutes:String(minutes%60).padStart(2,"0")}):t("game.duration.minutes",{minutes});}
function refreshSaveUi(){const result=saveStorage.read(),save=result.save,available=result.ok&&Boolean(save),broken=["invalid","incompatible","migration-write-failed"].includes(result.status);continueButton.hidden=!available;deleteSaveButton.hidden=!available&&!broken;saveSummary.textContent=available?t("game.save.summary",{level:save.world.level,duration:formatDuration(save.world.elapsed),date:new Date(save.meta.updatedAt).toLocaleString(getLocale())}):broken?t("game.save.broken"):t("hero.generated");return result;}
function startGame(save=null){home.hidden=true;game.hidden=false;window.scrollTo(0,0);cleanupGame?.();cleanupGame=createGame(save);}
function startNewGame(){const result=saveStorage.read(),existing=result.save,broken=["invalid","incompatible","migration-write-failed"].includes(result.status);if(existing&&!confirm(t("game.save.confirmNew")))return;if(broken&&!confirm(t("game.save.confirmBroken")))return;if(existing||broken)saveStorage.remove();startGame();refreshSaveUi();}
$("#play").addEventListener("click",startNewGame);$("#play-footer").addEventListener("click",startNewGame);
continueButton.addEventListener("click",()=>{const result=saveStorage.read();if(result.save)startGame(result.save);else refreshSaveUi();});
deleteSaveButton.addEventListener("click",()=>{if(!confirm(t("game.save.confirmDelete")))return;saveStorage.remove();refreshSaveUi();});
refreshSaveUi();
subscribeLocale(()=>refreshSaveUi());
$("#home-controls").addEventListener("click",()=>controlsPanel.open("home"));
$("#quit").addEventListener("click",()=>{cleanupGame?.saveNow?.("return-home");cleanupGame?.();cleanupGame=null;pauseMenu.hidden=true;game.hidden=true;home.hidden=false;refreshSaveUi();});

function createGame(initialSave=null){
  const restoredSave=initialSave?migrateExplorationSave(initialSave):null;
  const saveCreatedAt=restoredSave?.meta.createdAt??Date.now();
  const levelOne=getLevelConfig(1);
  const worldSeed=restoredSave?.world.seed??Math.floor(100000+Math.random()*899999);seedLabel.textContent=t("game.seed",{seed:worldSeed});
  const levelManager=new LevelManager(worldSeed),transitionManager=new TransitionManager(),startingMaze=levelManager.ensure(1).maze;
  const scene=new THREE.Scene();scene.background=new THREE.Color(levelOne.appearance.background);scene.fog=new THREE.FogExp2(levelOne.appearance.fog,levelOne.appearance.fogDensity);
  const camera=new THREE.PerspectiveCamera(CAMERA.fieldOfView,innerWidth/innerHeight,CAMERA.near,CAMERA.far);scene.add(camera);camera.position.set(startingMaze.originX+(startingMaze.entryColumn+.5)*startingMaze.cellSize,PLAYER.height,startingMaze.originZ+2.2);
  const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,RENDERING.maxPixelRatio));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;viewport.appendChild(renderer.domElement);
  const audio=new BackroomsAudio();let inputPreferences=loadInputPreferences();const input=new InputManager({bindings:inputPreferences.bindings}),raycaster=new THREE.Raycaster(),rendered=new Map(),inventory=[],pendingTimeouts=new Set(),mobileListeners=[],physicalDoors=[],interactables=[],artifacts=[],levelObjects=new Map(),levelObjectStates=new Map(),levelSaveMetadata=new Map(),levelRoutes=new Map(),guideCompletedLevels=new Set(restoredSave?.progress.guide?.completedLevels??[]);
  const creatureManager=new CreatureManager(scene,{audio});
  let paused=false,pauseStartedAt=0;const schedule=(callback,delay)=>{let id;const run=()=>{pendingTimeouts.delete(id);if(paused){id=setTimeout(run,100);pendingTimeouts.add(id);return;}callback();};id=setTimeout(run,delay);pendingTimeouts.add(id);return id;};
  let selectedIndex=0,tabOpen=false,thirst=restoredSave?.player.needs.thirst??0,hunger=restoredSave?.player.needs.hunger??0,elapsed=restoredSave?.world.elapsed??0,dragging=false,lastDragX=0,needsFrozen=false,activeCommandObjective=null,activeObjective=()=>t("game.objective.explore"),plush=null,battery=null,examinedObject=null,autosave=null;
  const markSave=(reason,immediate=true)=>autosave?.markDirty({reason,immediate});
  const commandKey=action=>inputActionLabel(inputPreferences,action);
  function setObjective(key,parameters={}){activeCommandObjective=null;activeObjective=()=>t(key,parameters);objective.textContent=activeObjective();}
  function setDynamicObjective(render){activeCommandObjective=render;activeObjective=render;objective.textContent=render();}
  function setCommandObjective(before,action,after=""){setDynamicObjective(()=>`${before}${commandKey(action)}${after}`);}
  const wallMaterial=new THREE.MeshStandardMaterial({color:levelOne.appearance.wall,roughness:.95}),floorMaterial=new THREE.MeshStandardMaterial({color:levelOne.appearance.floor,roughness:1}),ceilingMaterial=new THREE.MeshStandardMaterial({color:levelOne.appearance.ceiling,roughness:.9});
  const graffitiTexture=levelOne.entrance.graffiti?new THREE.TextureLoader().load(levelOne.entrance.graffiti):null;if(graffitiTexture)graffitiTexture.colorSpace=THREE.SRGBColorSpace;
  const graffitiMaterial=graffitiTexture?new THREE.MeshBasicMaterial({map:graffitiTexture,transparent:true,alphaTest:.025,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-2}):null;
  const ambientLight=new THREE.HemisphereLight(0xd8ca6a,0x2a2417,levelOne.lighting.ambientIntensity);scene.add(ambientLight);
  let currentIndex=(restoredSave?.world.level??1)-1,yaw=restoredSave?.player.orientation.yaw??Math.PI,pitch=restoredSave?.player.orientation.pitch??0,last=performance.now(),raf=0,hovered=null,muted=false,exitWall=null,exitOpened=restoredSave?.progress.exitOpened??false,exitOpening=false,exitOpeningAt=0;

  function definition(index){return levelManager.ensure(index+1).maze;}
  function addChunk(data){
    if(rendered.has(data.index))return;const group=new THREE.Group(),walls=[],chunkConfig=levelManager.ensure(data.index+1).config;
    const wall=(x,z,horizontal,cellSize)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(horizontal?cellSize+ARCHITECTURE.wallThickness:ARCHITECTURE.wallThickness,ARCHITECTURE.wallHeight,horizontal?ARCHITECTURE.wallThickness:cellSize+ARCHITECTURE.wallThickness),wallMaterial);mesh.position.set(x,ARCHITECTURE.wallHeight/2,z);group.add(mesh);walls.push(mesh);return mesh;};
    data.cells.forEach((row,y)=>row.forEach((cell,x)=>{const wx=data.originX+x*data.cellSize,wz=data.originZ+y*data.cellSize;if(cell.n)wall(wx+data.cellSize/2,wz,true,data.cellSize);if(cell.w)wall(wx,wz+data.cellSize/2,false,data.cellSize);if(x===data.width-1&&cell.e)wall(wx+data.cellSize,wz+data.cellSize/2,false,data.cellSize);if(y===data.height-1&&cell.s)wall(wx+data.cellSize/2,wz+data.cellSize,true,data.cellSize);}));
    for(const feature of data.features??[])if(feature.type==="column"){const size=Math.min(.62,data.cellSize*.14),column=new THREE.Mesh(new THREE.BoxGeometry(size,ARCHITECTURE.wallHeight,size),wallMaterial);column.position.set(data.originX+(feature.x+.5)*data.cellSize,ARCHITECTURE.wallHeight/2,data.originZ+(feature.y+.5)*data.cellSize);column.userData={architectureFeature:"column",level:data.index+1};group.add(column);walls.push(column);}
    if(data.index===0&&levelOne.entrance.type==="sealed-wall"){
      const entranceX=data.originX+(data.entryColumn+.5)*data.cellSize,entranceZ=data.originZ,entranceWall=wall(entranceX,entranceZ,true,data.cellSize);entranceWall.userData={entranceWall:true,level:1};
      if(graffitiMaterial){const graffiti=new THREE.Mesh(new THREE.PlaneGeometry(Math.min(2.45,data.cellSize*.55),2.45),graffitiMaterial);graffiti.position.set(entranceX,1.5,entranceZ+ARCHITECTURE.wallThickness/2+.006);graffiti.renderOrder=2;graffiti.userData={entranceGraffiti:true};group.add(graffiti);}
    }
    if(data.index===0&&levelOne.exit.type==="hidden-wall"&&!exitOpened){const exitX=data.originX+(data.exitColumn+.5)*data.cellSize,exitZ=data.originZ+data.worldLength;exitWall=wall(exitX,exitZ,true,data.cellSize);exitWall.userData={exitWall:true,level:1,opensWhen:levelOne.exit.opensWhen};}
    if(chunkConfig.entrance.type==="return-wall"){const returnX=data.originX+(data.entryColumn+.5)*data.cellSize,returnZ=data.originZ,returnWall=wall(returnX,returnZ,true,data.cellSize);walls.splice(walls.indexOf(returnWall),1);returnWall.userData={transitionWall:true,level:data.index+1,anchor:"return-wall"};}
    if(data.index===1&&!physicalDoors.length){
      const doorWidth=Math.min(2.35,data.cellSize*.55),doorX=data.originX+(data.exitColumn+.5)*data.cellSize,doorZ=data.originZ+data.worldLength,sideWidth=(data.cellSize-doorWidth)/2;
      wall(doorX-(doorWidth+sideWidth)/2,doorZ,true,sideWidth);wall(doorX+(doorWidth+sideWidth)/2,doorZ,true,sideWidth);
      const doorHeight=2.35,frameThickness=.13,assembly=createDoorAssembly({width:doorWidth,height:doorHeight,frameThickness,frameDepth:.2,hingeSide:HINGE_SIDES.LEFT,swingDirection:SWING_DIRECTIONS.INWARD}),headWall=createDoorHeadWall({width:doorWidth,openingHeight:doorHeight+frameThickness,wallHeight:ARCHITECTURE.wallHeight,depth:ARCHITECTURE.wallThickness,material:wallMaterial});assembly.doorFrame.position.set(doorX,0,doorZ);assembly.doorFrame.userData={id:"physical-door-2-3",icon:"🚪",nameKey:"door.white.name",descriptionKey:"door.white.description",name:t("door.white.name"),description:t("door.white.description"),interactable:true};headWall.position.x=doorX;headWall.position.z=doorZ;headWall.userData.level=data.index+1;group.add(headWall);scene.add(assembly.doorFrame);interactables.push(assembly.doorFrame);
      const controller=new DoorController(assembly,{duration:1350,playerRadius:PLAYER.collisionRadius,onHandle:()=>audio.doorHandle(),onCreak:()=>audio.doorCreak(),onBlocked:()=>showNotice(t("game.notice.doorBlocked"),1500)});physicalDoors.push({sourceLevel:2,targetLevel:3,assembly,controller});
    }
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(data.worldWidth,data.worldLength),floorMaterial);floor.rotation.x=-Math.PI/2;floor.position.set(data.originX+data.worldWidth/2,0,data.originZ+data.worldLength/2);group.add(floor);
    const ceiling=new THREE.Mesh(new THREE.PlaneGeometry(data.worldWidth,data.worldLength),ceilingMaterial);ceiling.rotation.x=Math.PI/2;ceiling.position.set(data.originX+data.worldWidth/2,ARCHITECTURE.wallHeight,data.originZ+data.worldLength/2);group.add(ceiling);
    const lighting=createLevelLighting(data,chunkConfig.lighting,chunkConfig.appearance,worldSeed);group.add(lighting.group);
    scene.add(group);rendered.set(data.index,{data,group,walls,lighting});
  }
  function disposeChunk(chunk){scene.remove(chunk.group);chunk.group.remove(chunk.lighting.group);chunk.lighting.dispose();if(exitWall?.parent===chunk.group&&exitWall.material!==wallMaterial)exitWall.material.dispose();disposeObjectTree(chunk.group,{materials:false});chunk.group.clear();}
  function disposePhysicalDoor(door){const index=interactables.indexOf(door.assembly.doorFrame);if(index>=0)interactables.splice(index,1);scene.remove(door.assembly.doorFrame);door.assembly.dispose();}
  function stream(){levelManager.setActive(currentIndex+1);const window=levelManager.streamingWindow(),loadedLevels=window.map(record=>record.levelNumber);for(const record of window){addChunk(definition(record.index));spawnLevelObjects(record);}creatureManager.syncLoaded(loadedLevels);for(const[index,chunk]of rendered)if(!levelManager.shouldRemainLoaded(index+1)){disposeChunk(chunk);rendered.delete(index);}for(const level of [...levelObjects.keys()])if(!levelManager.shouldRemainLoaded(level))despawnLevelObjects(level);for(let index=physicalDoors.length-1;index>=0;index--){const door=physicalDoors[index];if(!levelManager.shouldRemainLoaded(door.sourceLevel)&&!levelManager.shouldRemainLoaded(door.targetLevel)){disposePhysicalDoor(door);physicalDoors.splice(index,1);}}}
  const firstRecord=levelManager.ensure(1),secondRecord=levelManager.ensure(2),firstExitX=firstRecord.originX+(firstRecord.maze.exitColumn+.5)*firstRecord.maze.cellSize,firstExitZ=firstRecord.bounds.maxZ,secondEntryX=secondRecord.originX+(secondRecord.maze.entryColumn+.5)*secondRecord.maze.cellSize,secondEntryZ=secondRecord.bounds.minZ;
  audio.setLevelAudio(levelOne.audio,firstRecord.bounds);
  transitionManager.registerAnchor({id:"hidden-exit",level:1,position:{x:firstExitX,y:0,z:firstExitZ},yaw:0,width:firstRecord.maze.cellSize,height:ARCHITECTURE.wallHeight,depth:1.2});
  transitionManager.registerAnchor({id:"return-wall",level:2,position:{x:secondEntryX,y:0,z:secondEntryZ},yaw:0,width:secondRecord.maze.cellSize,height:ARCHITECTURE.wallHeight,depth:1.2});
  for(const transition of levelOne.transitions)transitionManager.register(transition);
  function routeFor(record){if(!levelRoutes.has(record.levelNumber)){const maze=record.maze,startX=maze.originX+(maze.entryColumn+.5)*maze.cellSize,startZ=maze.originZ+maze.cellSize*.5;levelRoutes.set(record.levelNumber,findMazePath(maze,startX,startZ));}return levelRoutes.get(record.levelNumber);}
  function placeOnRoute(object,record,placement){const route=routeFor(record),index=Math.max(0,Math.min(route.length-1,Math.round(placement.progress*(route.length-1)))),point=route[index],neighbor=route[Math.min(route.length-1,index+1)]||route[Math.max(0,index-1)]||point,dx=neighbor.x-point.x,dz=neighbor.z-point.z,length=Math.hypot(dx,dz)||1;object.position.set(point.x-dz/length*placement.lateral,placement.height,point.z+dx/length*placement.lateral);object.rotation.y=placement.rotation;}
  function spawnLevelObjects(record){if(levelObjects.has(record.levelNumber))return levelObjects.get(record.levelNumber);const objects=[],saved=levelObjectStates.get(record.levelNumber);if(saved){for(const state of saved){const object=restoreItem(state);scene.add(object);objects.push(object);interactables.push(object);if(object.userData.type==="artifact")artifacts.push(object);}}else for(const placement of expandObjectRules(record.config.objects)){const object=createItem(placement.type,{userData:{instanceId:`level-${record.levelNumber}:${placement.instanceId}`,level:record.levelNumber}});if(placement.strategy==="route")placeOnRoute(object,record,placement);scene.add(object);objects.push(object);interactables.push(object);}levelObjects.set(record.levelNumber,objects);if(record.levelNumber===1){plush=inventory.find(object=>object.userData.type==="plush")??objects.find(object=>object.userData.type==="plush")??null;battery=inventory.find(object=>object.userData.type==="battery")??objects.find(object=>object.userData.type==="battery")??null;}return objects;}
  function despawnLevelObjects(level){const objects=levelObjects.get(level);if(!objects)return;const saved=[];for(const object of objects){if(inventory.includes(object))continue;const interactableIndex=interactables.indexOf(object);if(interactableIndex>=0)interactables.splice(interactableIndex,1);const artifactIndex=artifacts.indexOf(object);if(artifactIndex>=0)artifacts.splice(artifactIndex,1);if(!object.userData.consumed&&object.parent)saved.push(snapshotItem(object));object.parent?.remove(object);disposeObjectTree(object);}levelObjectStates.set(level,saved);levelObjects.delete(level);levelRoutes.delete(level);}
  if(restoredSave)for(const[level,state]of Object.entries(restoredSave.levels)){levelObjectStates.set(Number(level),structuredClone(state.objects));levelSaveMetadata.set(Number(level),structuredClone(state));}
  levelManager.setActive(currentIndex+1,{previousLevel:currentIndex>=1?currentIndex:null,nextLevel:currentIndex+2});
  stream();
  function collides(x,z){for(const chunk of rendered.values())if(circleIntersectsMeshes(x,z,PLAYER.collisionRadius,chunk.walls))return true;for(const door of physicalDoors)if(door.controller.collides({x,z}))return true;return false;}

  if(restoredSave)for(const state of restoredSave.inventory){const object=restoreItem(state);camera.add(object);inventory.push(object);interactables.push(object);}
  const savedPosition=restoredSave?.player.position,activeRecord=levelManager.ensure(currentIndex+1),fallbackPosition=[activeRecord.originX+(activeRecord.maze.entryColumn+.5)*activeRecord.maze.cellSize,PLAYER.height,activeRecord.originZ+activeRecord.maze.cellSize*.5];
  camera.position.fromArray(resolveRestoredPlayerPosition(savedPosition,{levelNumber:currentIndex+1,findLevel:(x,z)=>levelManager.findByPosition(x,z),collides,fallback:fallbackPosition}));
  levelLabel.textContent=t("game.level",{level:currentIndex+1});traversedEl.textContent=String(currentIndex);updateNeedsDisplay();timeEl.textContent=`${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(Math.floor(elapsed%60)).padStart(2,"0")}`;
  const levelOneItems=levelObjects.get(1)??[];plush=inventory.find(object=>object.userData.type==="plush")??levelOneItems.find(object=>object.userData.type==="plush")??plush;battery=inventory.find(object=>object.userData.type==="battery")??levelOneItems.find(object=>object.userData.type==="battery")??battery;
  audio.setLevelAudio(activeRecord.config.audio,activeRecord.bounds);
  if(restoredSave)for(const state of restoredSave.progress.doors){const door=physicalDoors.find(candidate=>candidate.sourceLevel===state.sourceLevel&&candidate.targetLevel===state.targetLevel);if(!door||!Number.isFinite(state.angle))continue;door.controller.angle=Math.max(0,Math.min(door.controller.maxAngle,state.angle));door.controller.startAngle=door.controller.angle;door.controller.targetAngle=door.controller.angle;door.controller.moving=false;door.assembly.setAngle(door.controller.angle);}
  if(restoredSave)for(const state of restoredSave.progress.artifacts){if(!state?.type)continue;const id=state.userData?.instanceId;if(inventory.some(object=>object.userData.instanceId===id)||[...levelObjects.values()].flat().some(object=>object.userData.instanceId===id))continue;const level=Number(state.userData?.level)||1;if(levelObjects.has(level)){const artifact=restoreItem(state);scene.add(artifact);artifacts.push(artifact);interactables.push(artifact);levelObjects.get(level).push(artifact);}else{const saved=levelObjectStates.get(level)??[];saved.push(structuredClone(state));levelObjectStates.set(level,saved);}}
  function createArtifact(position){const level=currentIndex+1,id=`level-${level}:guide-artifact`;if(inventory.some(object=>object.userData.instanceId===id)||[...levelObjects.values()].flat().some(object=>object.userData.instanceId===id)||(levelObjectStates.get(level)??[]).some(state=>state.userData?.instanceId===id))return null;const artifact=createItem("artifact",{userData:{instanceId:id,level,guideReward:true}});artifact.position.copy(position);artifact.position.y=.25;scene.add(artifact);artifacts.push(artifact);interactables.push(artifact);const objects=levelObjects.get(level)??[];objects.push(artifact);levelObjects.set(level,objects);markSave("artifact");return artifact;}
  function beginExitOpening(now){if(exitOpened||exitOpening||!exitWall)return false;exitOpening=true;exitOpeningAt=now;exitWall.material=exitWall.material.clone();exitWall.material.transparent=true;exitWall.material.opacity=1;exitWall.userData.closedY=exitWall.position.y;setObjective("game.objective.opening");showNotice(t("game.notice.wallFades"),2600);markSave("exit-opening");return true;}
  function updateExitOpening(now){if(!exitOpening||!exitWall)return;const progress=Math.min(1,(now-exitOpeningAt)/1400),eased=progress*progress*(3-2*progress);exitWall.material.opacity=1-eased;exitWall.position.y=exitWall.userData.closedY-eased*(ARCHITECTURE.wallHeight+.2);if(progress<1)return;const chunk=rendered.get(0),wallIndex=chunk?.walls.indexOf(exitWall)??-1;if(wallIndex>=0)chunk.walls.splice(wallIndex,1);exitWall.parent?.remove(exitWall);exitWall.geometry.dispose();exitWall.material.dispose();exitWall=null;exitOpening=false;exitOpened=true;setObjective("game.objective.cross");showNotice(t("game.notice.passage"),2200);}
  const companion=new THREE.Group(),coreMat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true}),haloMat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.18,depthWrite:false,blending:THREE.AdditiveBlending});
  const core=new THREE.Mesh(new THREE.SphereGeometry(.17,18,14),coreMat),halo=new THREE.Mesh(new THREE.SphereGeometry(.4,18,14),haloMat),guideLight=new THREE.PointLight(0xffffff,0,8,2);companion.add(core,halo,guideLight);companion.visible=false;scene.add(companion);
  const vaporPositions=new Float32Array(54);for(let i=0;i<vaporPositions.length;i+=3){vaporPositions[i]=(Math.random()-.5)*.55;vaporPositions[i+1]=Math.random()*.4;vaporPositions[i+2]=(Math.random()-.5)*.55;}const vaporGeometry=new THREE.BufferGeometry();vaporGeometry.setAttribute("position",new THREE.BufferAttribute(vaporPositions,3));const vaporMaterial=new THREE.PointsMaterial({color:0xffffff,size:.09,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}),vapor=new THREE.Points(vaporGeometry,vaporMaterial);vapor.visible=false;companion.add(vapor);
  let guideActive=false,guidePath=[],guideWaypoint=0,guidePhase="near",guideChunk=0,waitUntil=0,transitionStart=0,transitionStartY=1.78,rebirthAt=0,lastPlayerCell="",lastRemainingSteps=Infinity,playerOnCorrectRoute=false,lastPlayerMoveAt=performance.now(),observedPlayerX=camera.position.x,observedPlayerZ=camera.position.z,losAchievedAt=0,wasFollowing=false;
  if(restoredSave?.progress.guide){const state=restoredSave.progress.guide;guideChunk=Number.isInteger(state.level)?state.level-1:currentIndex;guideActive=Boolean(state.active)&&!guideCompletedLevels.has(guideChunk+1);guidePhase=guideCompletedLevels.has(guideChunk+1)?"completed":typeof state.phase==="string"?state.phase:"near";if(Array.isArray(state.position)&&state.position.length===3&&state.position.every(Number.isFinite)){companion.position.fromArray(state.position);companion.visible=guideActive;}if(guideActive){guideLight.intensity=3;coreMat.opacity=1;haloMat.opacity=.2;}}
  const white=new THREE.Color(0xffffff),yellow=new THREE.Color(0xffdf35),losOrigin=new THREE.Vector3(),losTarget=new THREE.Vector3(),losDirection=new THREE.Vector3();
  function makeGuidePath(points,limit){guidePath=points.slice(1,limit?limit+1:undefined);guideWaypoint=0;}
  function activateGuide(x,z){const level=currentIndex+1,config=levelManager.ensure(level).config;if(!config.guide.enabled||guideCompletedLevels.has(level))return false;guideActive=true;guideChunk=currentIndex;companion.visible=true;companion.position.set(x,1.78,z);companion.scale.setScalar(1);vapor.visible=false;vaporMaterial.opacity=0;coreMat.color.set(0xffffff);coreMat.opacity=1;haloMat.color.set(0xffffff);haloMat.opacity=.2;guideLight.color.set(0xffffff);guideLight.intensity=3;guidePhase="near";guidePath=[];lastPlayerCell="";lastRemainingSteps=Infinity;setObjective("game.objective.follow");showNotice(t("game.notice.guideAwake"));markSave("guide-awake");return true;}
  function planGuide(){makeGuidePath(findMazePath(definition(currentIndex),companion.position.x,companion.position.z),4);guidePhase=guidePath.length?"guide":"wait";waitUntil=performance.now()+2500;}
  function planReturn(){makeGuidePath(findMazePath(definition(currentIndex),companion.position.x,companion.position.z,camera.position.x,camera.position.z));guidePhase=guidePath.length?"return":"near";}
  function safeGuideSpawn(){const record=levelManager.ensure(currentIndex+1);return findSafeGuideSpawn(camera.position,{collides,contains:(x,z)=>x>record.bounds.minX+.35&&x<record.bounds.maxX-.35&&z>record.bounds.minZ+.35&&z<record.bounds.maxZ-.35,startAngle:yaw});}
  function checkLOS(){losOrigin.set(camera.position.x,1.625,camera.position.z);losTarget.set(companion.position.x,1.625,companion.position.z);losDirection.subVectors(losTarget,losOrigin);raycaster.far=losDirection.length();raycaster.set(losOrigin,losDirection.normalize());const walls=[];for(const chunk of rendered.values())walls.push(...chunk.walls);return raycaster.intersectObjects(walls,false).length===0;}
  function moveGuide(dt){const target=guidePath[guideWaypoint];if(!target)return true;const dx=target.x-companion.position.x,dz=target.z-companion.position.z,d=Math.hypot(dx,dz);if(d<.13){guideWaypoint++;return guideWaypoint>=guidePath.length;}const step=Math.min(d,2.65*dt),nx=companion.position.x+dx/d*step,nz=companion.position.z+dz/d*step;if(!collides(nx,companion.position.z))companion.position.x=nx;if(!collides(companion.position.x,nz))companion.position.z=nz;return false;}
  function updateGuide(dt,now,playerIdle){if(!guideActive)return;const playerDistance=Math.hypot(companion.position.x-camera.position.x,companion.position.z-camera.position.z),chunk=definition(currentIndex),exitX=chunk.originX+(chunk.exitColumn+.5)*chunk.cellSize,exitZ=chunk.originZ+(chunk.height-.5)*chunk.cellSize,playerExitDistance=Math.hypot(camera.position.x-exitX,camera.position.z-exitZ),guideExitDistance=Math.hypot(companion.position.x-exitX,companion.position.z-exitZ),cellX=Math.max(0,Math.min(chunk.width-1,Math.floor((camera.position.x-chunk.originX)/chunk.cellSize))),cellY=Math.max(0,Math.min(chunk.height-1,Math.floor((camera.position.z-chunk.originZ)/chunk.cellSize))),playerCell=`${currentIndex}:${cellX}:${cellY}`;
    if(playerExitDistance<2.4&&guideExitDistance<4.8&&!['complete','waitLevel','rebirth'].includes(guidePhase)){guidePhase="complete";transitionStart=now;transitionStartY=companion.position.y;guidePath=[];coreMat.color.set(0xffffff);haloMat.color.set(0xffffff);guideLight.color.set(0xffffff);vapor.visible=true;vapor.position.y=0;audio.setFollowing(false);setObjective("game.objective.cross");}
    if(playerCell!==lastPlayerCell&&!['complete','waitLevel','rebirth'].includes(guidePhase)){const remaining=findMazePath(chunk,camera.position.x,camera.position.z).length;if(Number.isFinite(lastRemainingSteps))playerOnCorrectRoute=remaining<lastRemainingSteps;lastRemainingSteps=remaining;lastPlayerCell=playerCell;if(playerOnCorrectRoute){makeGuidePath(findMazePath(chunk,companion.position.x,companion.position.z,camera.position.x,camera.position.z));guidePhase="follow";}else if(guidePhase==="follow"){guidePath=[];guidePhase="near";}}
    const following=['guide','wait','follow'].includes(guidePhase)&&playerDistance<4.5;audio.setFollowing(following);wasFollowing=following;
    if(!['complete','waitLevel','rebirth'].includes(guidePhase)){const exitNear=THREE.MathUtils.clamp(1-guideExitDistance/(chunk.worldLength*.58),0,1),visible=THREE.MathUtils.smoothstep(playerDistance,.7,2.6);coreMat.color.copy(white).lerp(yellow,exitNear);haloMat.color.copy(white).lerp(yellow,exitNear);guideLight.color.copy(white).lerp(yellow,exitNear);coreMat.opacity=visible;haloMat.opacity=.2*visible;guideLight.intensity=visible*THREE.MathUtils.lerp(2.8,6.2,exitNear);}
    if(playerIdle&&guidePhase==="follow"){playerOnCorrectRoute=false;guidePath=[];guidePhase="near";}
    if(guidePhase==="follow"){if(guidePath.length&&moveGuide(dt))guidePath=[];if(!guidePath.length&&playerDistance>1.9)makeGuidePath(findMazePath(chunk,companion.position.x,companion.position.z,camera.position.x,camera.position.z));}
    else if(guidePhase==="near"){if(playerDistance>1.8)planReturn();else planGuide();}
    else if(guidePhase==="guide"){if(moveGuide(dt)){guidePhase="wait";waitUntil=now+2500;}}
    else if(guidePhase==="wait"){if(playerDistance<2.4)planGuide();else if(now>=waitUntil&&!checkLOS()){planReturn();losAchievedAt=0;}}
    else if(guidePhase==="return"){if(checkLOS()){if(!losAchievedAt)losAchievedAt=now;if(now-losAchievedAt>600){guidePhase="wait";waitUntil=now+2500;guidePath=[];losAchievedAt=0;}else if(moveGuide(dt))guidePhase="near";}else{losAchievedAt=0;if(moveGuide(dt))guidePhase="near";}}
    else if(guidePhase==="complete"){const progress=Math.min(1,(now-transitionStart)/1200),eased=1-Math.pow(1-progress,3);companion.position.y=THREE.MathUtils.lerp(transitionStartY,.2,eased);coreMat.opacity=1-progress;haloMat.opacity=.22*(1-progress);guideLight.intensity=4*Math.pow(1-progress,2);vaporMaterial.opacity=Math.sin(progress*Math.PI)*.85;vapor.position.y=progress*1.9;vapor.rotation.y+=dt*1.4;companion.scale.setScalar(1+progress*.35);if(progress>=1){const level=currentIndex+1,config=levelManager.ensure(level).config;guideCompletedLevels.add(level);if(config.guide.leavesArtifact)createArtifact(companion.position);companion.visible=false;vapor.visible=false;guideActive=false;guidePhase="completed";showNotice(t("game.notice.artifact"),2600);if(level===1)beginExitOpening(now);markSave("guide-complete");}}
    else if(guidePhase==="rebirth"&&now>=rebirthAt){const spawn=safeGuideSpawn();if(!spawn){rebirthAt=now+250;}else{companion.position.set(spawn.x,1.78,spawn.z);companion.scale.setScalar(1);companion.visible=true;vapor.visible=false;vaporMaterial.opacity=0;coreMat.color.set(0xffffff);coreMat.opacity=1;haloMat.color.set(0xffffff);haloMat.opacity=.2;guideLight.color.set(0xffffff);guideLight.intensity=3.2;guidePhase="near";}}
    if(!['complete','waitLevel','rebirth'].includes(guidePhase))companion.position.y=1.78+Math.sin(now*.0022)*.16;companion.rotation.y+=dt*.8;
  }

  function selectedObject(){return inventory.length?inventory[Math.max(0,Math.min(inventory.length-1,selectedIndex))]:null;}
  function doorFor(object){return physicalDoors.find(door=>door.assembly.doorFrame===object)||null;}
  function actionsFor(object,inInventory=inventory.includes(object)){if(!object)return[];const key=action=>inputActionLabel(inputPreferences,action),actions=[],door=doorFor(object);if(door)actions.push({key:key(INPUT_ACTIONS.INTERACT),label:t(door.controller.targetAngle>.001||door.controller.angle>.001?"game.action.close":"game.action.open"),icon:"🚪"});else if(!inInventory)actions.push({key:key(INPUT_ACTIONS.INTERACT),label:t("game.action.take"),icon:"✋"});if(object.userData.description)actions.push({key:key(INPUT_ACTIONS.EXAMINE),label:t("game.action.examine"),icon:object.userData.icon||"◈"});if(object.userData.sips>0)actions.push({key:key(INPUT_ACTIONS.DRINK),label:t("game.action.drink"),icon:"💧"});if(inInventory){actions.push({key:key(INPUT_ACTIONS.DROP),label:t("game.action.drop"),icon:"⬇️"});if(object===battery&&inventory.includes(plush))actions.push({key:key(INPUT_ACTIONS.COMBINE),label:t("game.action.combine"),icon:"🔌"});if(object===plush&&object.userData.powered&&!object.userData.fried)actions.push({key:key(INPUT_ACTIONS.POWER_PLUSH),label:t("game.action.power"),icon:"🔴"});}return actions;}
  function renderActions(){const object=tabOpen?selectedObject():hovered,actions=actionsFor(object),layout=calculateInteractionLayout(actions.length,innerHeight,{compact:innerWidth<=700});game.style.setProperty("--action-label-offset",`${layout.labelOffset}px`);radialMenu.replaceChildren();radialMenu.hidden=!object||!actions.length;interaction.hidden=!shouldShowInteractionLabel({objectAvailable:Boolean(object),inventoryOpen:tabOpen});if(object&&!tabOpen)interaction.textContent=t("game.interaction.object",{name:object.userData.name});actions.forEach((action,index)=>{const angle=index/actions.length*Math.PI*2-Math.PI/2,node=document.createElement("div");node.className="action-node";node.style.transform=`translate(${Math.cos(angle)*layout.radius}px,${Math.sin(angle)*layout.radius}px)`;node.innerHTML=`<strong>${action.key}</strong><span>${action.label}</span><i>${action.icon}</i>`;radialMenu.append(node);});}
  function updateInventory(){if(selectedIndex>=inventory.length)selectedIndex=Math.max(0,inventory.length-1);const selected=selectedObject();items.textContent=inventory.length?(tabOpen?`${selected.userData.icon||"◆"} ${selected.userData.name}`:inventory.map(o=>o.userData.icon||"◆").join("  ")):t("game.empty");inventoryIndex.textContent=inventory.length?`${selectedIndex+1}/${inventory.length}`:"";inventoryEl.classList.toggle("open",tabOpen);renderActions();}
  function take(object){const artifactIndex=artifacts.indexOf(object);if(artifactIndex>=0)artifacts.splice(artifactIndex,1);camera.add(object);inventory.push(object);object.userData.worldScale=object.scale.x;object.scale.setScalar(.15);selectedIndex=inventory.length-1;hovered=null;interaction.hidden=true;updateInventory();if(inventory.includes(plush)&&inventory.includes(battery))setDynamicObjective(()=>t("game.objective.combine",{inventory:commandKey(INPUT_ACTIONS.INVENTORY),combine:commandKey(INPUT_ACTIONS.COMBINE)}));markSave("take-item");}
  function use(object){const door=doorFor(object);if(door){door.controller.toggle(performance.now());renderActions();markSave("door",false);return;}take(object);}
  function combine(){const selected=selectedObject();if(selected!==battery||!inventory.includes(plush)||plush.userData.powered)return;camera.remove(battery);inventory.splice(inventory.indexOf(battery),1);battery.userData.consumed=true;const batteryInteractable=interactables.indexOf(battery);if(batteryInteractable>=0)interactables.splice(batteryInteractable,1);for(const objects of levelObjects.values()){const index=objects.indexOf(battery);if(index>=0)objects.splice(index,1);}disposeObjectTree(battery);plush.userData.powered=true;localizeItem(plush);const glow=new THREE.PointLight(0xffd84a,.55,2.4,2);glow.userData.powerIndicator=true;plush.add(glow);selectedIndex=inventory.indexOf(plush);updateInventory();setDynamicObjective(()=>t("game.objective.power",{key:commandKey(INPUT_ACTIONS.POWER_PLUSH)}));showNotice(t("game.notice.battery",{key:commandKey(INPUT_ACTIONS.POWER_PLUSH)}));markSave("combine");}
  function fry(){if(selectedObject()!==plush||!plush.userData.powered||plush.userData.fried)return;plush.userData.fried=true;localizeItem(plush);const indicator=plush.children.find(o=>o.userData.powerIndicator);if(indicator)plush.remove(indicator);plush.traverse(o=>{if(o.material){o.material=o.material.clone();o.material.color?.setHex(0x222222);}});const red=new THREE.PointLight(0xff0000,3,10,2);plush.add(red);audio.electrical();game.classList.add("flash");schedule(()=>game.classList.remove("flash"),550);setDynamicObjective(()=>t("game.objective.dropRabbit",{key:commandKey(INPUT_ACTIONS.DROP)}));showNotice(t("game.notice.rabbit",{key:commandKey(INPUT_ACTIONS.DROP)}),4200);updateInventory();markSave("power-plush");}
  function dropSelected(){const object=selectedObject();if(!object)return;inventory.splice(selectedIndex,1);camera.remove(object);for(const objects of levelObjects.values()){const index=objects.indexOf(object);if(index>=0)objects.splice(index,1);}const forward=new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion).setY(0).normalize(),position=camera.position.clone().add(forward.multiplyScalar(.8));object.position.copy(position);object.position.y=.06;object.scale.setScalar(object.userData.worldScale||1);object.userData.level=currentIndex+1;object.visible=true;scene.add(object);const currentObjects=levelObjects.get(currentIndex+1)??[];currentObjects.push(object);levelObjects.set(currentIndex+1,currentObjects);if(object.userData.type==="artifact"&&!artifacts.includes(object))artifacts.push(object);updateInventory();if(object===plush&&plush.userData.fried){plush.userData.consumed=true;scene.remove(plush);const plushInteractable=interactables.indexOf(plush);if(plushInteractable>=0)interactables.splice(plushInteractable,1);currentObjects.splice(currentObjects.indexOf(plush),1);disposeObjectTree(plush);setObjective("game.objective.transform");schedule(()=>activateGuide(position.x,position.z),450);}markSave("drop-item");}
  function examine(){const object=tabOpen?selectedObject():hovered;if(!object)return;document.exitPointerLock();examinedObject=object;modalTitle.textContent=object.userData.name||t("game.unknownObject");modalText.textContent=object.userData.description||t("game.noInformation");modal.hidden=false;}
  function drink(){const object=tabOpen?selectedObject():hovered;if(!object?.userData.sips)return;object.userData.sips--;thirst=Math.max(0,thirst-15);if(!object.userData.sips){object.userData.id="water_empty";object.userData.icon="🫙";object.traverse(child=>{if(child.material){child.material=child.material.clone();child.material.opacity=.15;child.material.color?.setHex(0xaaaaaa);}});}localizeItem(object);updateInventory();showNotice(t(object.userData.sips?"game.notice.drink":"game.notice.emptyBottle"),1600);markSave("drink");}

  function refreshGameTranslation(){
    for(const object of new Set([...interactables,...inventory])){if(object.userData.type)localizeItem(object);else if(object.userData.nameKey){object.userData.name=t(object.userData.nameKey);object.userData.description=t(object.userData.descriptionKey);}}
    levelLabel.textContent=t("game.level",{level:currentIndex+1});seedLabel.textContent=t("game.seed",{seed:worldSeed});objective.textContent=activeObjective();$("#sound").textContent=t(muted?"game.soundOff":"game.soundOn");
    const promptHelp=document.querySelector('[data-i18n-dynamic="game.prompt"]'),inventoryHelp=document.querySelector('[data-i18n-dynamic="game.inventoryHelp"]');
    if(promptHelp)promptHelp.textContent=t("game.prompt",{movement:inputPreferences.layout==="qwerty"?"WASD":"ZQSD",run:commandKey(INPUT_ACTIONS.RUN),interact:commandKey(INPUT_ACTIONS.INTERACT)});
    if(inventoryHelp)inventoryHelp.textContent=t("game.inventoryHelp",{inventory:commandKey(INPUT_ACTIONS.INVENTORY)});
    if(examinedObject&&!modal.hidden){modalTitle.textContent=examinedObject.userData.name||t("game.unknownObject");modalText.textContent=examinedObject.userData.description||t("game.noInformation");}
    updateInventory();refreshSaveUi();
  }
  const unsubscribeLocale=subscribeLocale(refreshGameTranslation);refreshGameTranslation();

  function debugSafePosition(target,distance=1.15){for(let ring=distance;ring<=distance+2;ring+=.45)for(let index=0;index<16;index++){const angle=index/16*Math.PI*2,x=target.x+Math.cos(angle)*ring,z=target.z+Math.sin(angle)*ring;if(!collides(x,z))return{x,z};}return null;}
  function debugTeleportNear(target,distance){const safe=debugSafePosition(target,distance);if(!safe)return false;camera.position.set(safe.x,PLAYER.height,safe.z);observedPlayerX=safe.x;observedPlayerZ=safe.z;lastPlayerMoveAt=performance.now();return true;}
  function debugGoToLevel(levelNumber){const normalized=Math.max(1,Math.floor(Number(levelNumber)));if(!Number.isFinite(normalized))return false;const record=levelManager.ensure(normalized);currentIndex=record.index;levelManager.setActive(normalized);stream();const target={x:record.originX+(record.maze.entryColumn+.5)*record.maze.cellSize,z:record.originZ+record.maze.cellSize*.5},safe=!collides(target.x,target.z)?target:debugSafePosition(target,.35);if(!safe)return false;camera.position.set(safe.x,PLAYER.height,safe.z);observedPlayerX=safe.x;observedPlayerZ=safe.z;lastPlayerMoveAt=performance.now();levelLabel.textContent=t("game.level",{level:normalized});traversedEl.textContent=String(record.index);audio.setLevelAudio(record.config.audio,record.bounds);return true;}
  function debugWakeGuide(){const safe=debugSafePosition(camera.position,1.15);return safe?activateGuide(safe.x,safe.z):false;}
  function debugToggleDoor(){let nearest=null,distance=Infinity;for(const door of physicalDoors){const position=door.assembly.doorFrame.position,currentDistance=Math.hypot(camera.position.x-position.x,camera.position.z-position.z);if(currentDistance<distance){nearest=door;distance=currentDistance;}}return nearest?nearest.controller.toggle(performance.now()):false;}
  function updateNeedsDisplay(){thirstEl.textContent=`${Math.floor(thirst)}%`;hungerEl.textContent=`${Math.floor(hunger)}%`;}
  function exportGameState(){
    const levels={};
    for(const[level,objects]of levelObjectStates){const state=structuredClone(levelSaveMetadata.get(level)??createEmptyLevelSave());state.objects=structuredClone(objects);levels[level]=state;}
    for(const[level,objects]of levelObjects){const state=levels[level]??structuredClone(levelSaveMetadata.get(level)??createEmptyLevelSave());state.objects=objects.filter(object=>!inventory.includes(object)&&!object.userData.consumed&&object.parent).map(snapshotItem);levels[level]=state;}
    return createExplorationSave({seed:worldSeed,level:currentIndex+1,elapsed,position:camera.position.toArray(),yaw,pitch,thirst,hunger,inventory:inventory.map(snapshotItem),progress:{exitOpened,doors:physicalDoors.map(door=>({sourceLevel:door.sourceLevel,targetLevel:door.targetLevel,angle:door.controller.angle})),transitions:[],guide:guideActive||guideCompletedLevels.size?{active:guideActive,phase:guidePhase,level:guideChunk+1,position:companion.position.toArray(),completedLevels:[...guideCompletedLevels].sort((a,b)=>a-b)}:null,artifacts:[]},levels,createdAt:saveCreatedAt,updatedAt:Date.now()});
  }
  autosave=new AutosaveController({snapshot:exportGameState,storage:saveStorage,intervalMs:15000});autosave.start();
  const beforeUnload=()=>autosave.flush("before-unload");addEventListener("beforeunload",beforeUnload);
  const debugApi=Object.freeze({
    snapshot(){const record=levelManager.ensure(currentIndex+1);return Object.freeze({level:currentIndex+1,position:Object.freeze({x:camera.position.x,y:camera.position.y,z:camera.position.z}),bounds:Object.freeze({...record.bounds}),exitOpened,exitOpening,guideActive,guidePhase,thirst,hunger,needsFrozen,inventory:Object.freeze(inventory.map(object=>object.userData.instanceId??object.userData.type)),doors:Object.freeze(physicalDoors.map(door=>Object.freeze({sourceLevel:door.sourceLevel,targetLevel:door.targetLevel,angle:door.controller.angle,moving:door.controller.moving})))});},
    objects(){return Object.freeze(interactables.filter(object=>object.userData.type&&!object.userData.consumed).map(object=>{const position=object.getWorldPosition(new THREE.Vector3());return Object.freeze({instanceId:object.userData.instanceId??object.userData.id,type:object.userData.type,name:object.userData.name,level:object.userData.level,inInventory:inventory.includes(object),visible:object.visible,position:Object.freeze({x:position.x,y:position.y,z:position.z})});}));},
    teleportNearObject(identifier){const object=interactables.find(candidate=>!inventory.includes(candidate)&&candidate.parent&&candidate.visible&&(candidate.userData.instanceId===identifier||candidate.userData.type===identifier||candidate.userData.id===identifier));return object?debugTeleportNear(object.getWorldPosition(new THREE.Vector3())):false;},
    teleportNearExit(){const record=levelManager.ensure(currentIndex+1),route=findMazePath(record.maze,camera.position.x,camera.position.z),point=route[Math.max(0,route.length-3)];return point?debugTeleportNear(point,.45):false;},
    goToLevel(levelNumber){return debugGoToLevel(levelNumber);},
    previousLevel(){return debugGoToLevel(Math.max(1,currentIndex));},
    nextLevel(){return debugGoToLevel(currentIndex+2);},
    wakeGuide(){return debugWakeGuide();},
    unlockExit(){return exitOpened||exitOpening||beginExitOpening(performance.now());},
    toggleDoor(){return debugToggleDoor();},
    toggleNeedsFreeze(){needsFrozen=!needsFrozen;return needsFrozen;},
    resetNeeds(){thirst=0;hunger=0;updateNeedsDisplay();return true;},
    exportSave(){return exportGameState();},
  });
  let debugSession={dispose(){}},gameDisposed=false;void loadOptionalDebug(debugApi,{onUnavailable:error=>console.info("[Backrooms] Outils de debug locaux indisponibles.",error?.message??error)}).then(session=>{if(gameDisposed)session.dispose();else debugSession=session;});

  function pointerLock(){if(paused||controlsPanel.isOpen())return;audio.start();renderer.domElement.requestPointerLock();}
  renderer.domElement.addEventListener("click",pointerLock);
  const mouse=e=>{if(document.pointerLockElement!==renderer.domElement)return;yaw-=e.movementX*CAMERA.mouseSensitivity;pitch=Math.max(-1.35,Math.min(1.35,pitch-e.movementY*CAMERA.mouseSensitivity));};
  input.onPress(INPUT_ACTIONS.INVENTORY,()=>{tabOpen=true;updateInventory();});input.onRelease(INPUT_ACTIONS.INVENTORY,()=>{tabOpen=false;dragging=false;updateInventory();});input.onPress(INPUT_ACTIONS.INTERACT,()=>{if(!tabOpen&&hovered)use(hovered);});input.onPress(INPUT_ACTIONS.EXAMINE,examine);input.onPress(INPUT_ACTIONS.COMBINE,()=>{if(tabOpen)combine();});input.onPress(INPUT_ACTIONS.POWER_PLUSH,()=>{if(tabOpen)fry();});input.onPress(INPUT_ACTIONS.DROP,()=>{if(tabOpen)dropSelected();});input.onPress(INPUT_ACTIONS.DRINK,drink);
  const updatePauseSave=()=>{$("#pause-load").disabled=!saveStorage.read().save;},openPause=()=>{if(paused)return;paused=true;pauseStartedAt=performance.now();input.setEnabled(false);audio.mute(true);saveStatus.textContent="";updatePauseSave();pauseMenu.hidden=false;prompt.hidden=true;document.exitPointerLock?.();},resumeGame=()=>{if(!paused)return;const resumedAt=performance.now(),pauseDuration=Math.max(0,resumedAt-pauseStartedAt),shift=value=>value?value+pauseDuration:value;exitOpeningAt=shift(exitOpeningAt);waitUntil=shift(waitUntil);transitionStart=shift(transitionStart);rebirthAt=shift(rebirthAt);lastPlayerMoveAt=shift(lastPlayerMoveAt);losAchievedAt=shift(losAchievedAt);for(const door of physicalDoors)if(door.controller.moving)door.controller.startedAt+=pauseDuration;creatureManager.shiftTimeline(pauseDuration);audio.shiftTimeline(pauseDuration);pauseMenu.hidden=true;paused=false;last=resumedAt;input.setEnabled(true);audio.mute(muted);renderer.domElement.requestPointerLock();},openGameControls=()=>{if(!paused)openPause();pauseMenu.hidden=true;controlsPanel.open("game");},wheel=e=>{if(paused||!tabOpen||!inventory.length)return;e.preventDefault();selectedIndex=(selectedIndex+(e.deltaY>0?1:-1)+inventory.length)%inventory.length;updateInventory();},pointerDown=e=>{if(!paused&&tabOpen){dragging=true;lastDragX=e.clientX;}},pointerMove=e=>{if(paused||!dragging||!tabOpen||!inventory.length)return;const delta=e.clientX-lastDragX;if(Math.abs(delta)>28){selectedIndex=(selectedIndex+(delta<0?1:-1)+inventory.length)%inventory.length;lastDragX=e.clientX;updateInventory();}},pointerUp=()=>dragging=false,lock=()=>{const locked=document.pointerLockElement===renderer.domElement;if(!locked&&!paused&&modal.hidden&&!controlsPanel.isOpen())openPause();prompt.hidden=locked||paused||!modal.hidden;},resize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);};
  const pauseEscape=event=>{if(event.code!=="Escape"||!paused||pauseMenu.hidden||controlsPanel.isOpen())return;event.preventDefault();event.stopImmediatePropagation?.();resumeGame();};
  addEventListener("mousemove",mouse);addEventListener("wheel",wheel,{passive:false});addEventListener("pointerdown",pointerDown);addEventListener("pointermove",pointerMove);addEventListener("pointerup",pointerUp);addEventListener("resize",resize);addEventListener("keydown",pauseEscape);mobileListeners.push([globalThis,"keydown",pauseEscape]);document.addEventListener("pointerlockchange",lock);
  document.querySelectorAll("[data-move]").forEach(button=>{const action={forward:INPUT_ACTIONS.MOVE_FORWARD,left:INPUT_ACTIONS.MOVE_LEFT,back:INPUT_ACTIONS.MOVE_BACKWARD,right:INPUT_ACTIONS.MOVE_RIGHT}[button.dataset.move],source=`mobile:${button.dataset.move}`,press=()=>input.activate(action,source),release=()=>input.deactivate(action,source);button.addEventListener("pointerdown",press);mobileListeners.push([button,"pointerdown",press]);for(const type of["pointerup","pointercancel","pointerleave"]){button.addEventListener(type,release);mobileListeners.push([button,type,release]);}});
  const unsubscribeControls=controlsPanel.subscribe(event=>{if(event.type==="change"){inputPreferences=event.preferences;input.setBindings(event.preferences.bindings);refreshInputLabels(document,inputPreferences);refreshGameTranslation();}else if(event.type==="close"&&event.context==="game")pauseMenu.hidden=false;});
  $("#game-pause").onclick=openPause;$("#resume-game").onclick=resumeGame;$("#pause-controls").onclick=openGameControls;$("#pause-home").onclick=()=>$("#quit").click();
  $("#pause-save").onclick=()=>{const result=autosave.markDirty({reason:"manual",immediate:true});saveStatus.textContent=t(result?.ok?"game.save.done":"game.save.unavailable");updatePauseSave();refreshSaveUi();};
  $("#pause-load").onclick=()=>{const result=saveStorage.read();if(!result.save){saveStatus.textContent=t("game.save.none");updatePauseSave();return;}if(!confirm(t("game.save.confirmLoad")))return;cleanupGame?.();cleanupGame=createGame(result.save);};
  $("#new-run").onclick=startNewGame;
  $("#modal-close").onclick=()=>{modal.hidden=true;examinedObject=null;renderer.domElement.requestPointerLock();};
  $("#sound").onclick=()=>{muted=!muted;audio.mute(muted);$("#sound").textContent=t(muted?"game.soundOff":"game.soundOn");};
  const clockTimer=setInterval(()=>{if(paused)return;elapsed++;if(!needsFrozen){thirst=Math.min(100,thirst+.15);hunger=Math.min(100,hunger+.08);updateNeedsDisplay();}timeEl.textContent=`${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`;markSave("clock",false);},1000);
  let frame=0;
  function animate(now){
    const dt=Math.min((now-last)/1000,.04);last=now;if(paused){renderer.render(scene,camera);raf=requestAnimationFrame(animate);return;}const activeRecord=levelManager.ensure(currentIndex+1),activeLighting=activeRecord.config.lighting;audio.update(now,camera.position,activeRecord.bounds);ambientLight.intensity=THREE.MathUtils.lerp(ambientLight.intensity,activeLighting.ambientIntensity,.05);for(const chunk of rendered.values())chunk.lighting.update(now);for(const door of physicalDoors)door.controller.update(now,camera.position);camera.rotation.set(pitch,yaw,0,"YXZ");const previousPosition={x:camera.position.x,y:camera.position.y,z:camera.position.z},forward=Number(input.isActive(INPUT_ACTIONS.MOVE_FORWARD))-Number(input.isActive(INPUT_ACTIONS.MOVE_BACKWARD)),side=Number(input.isActive(INPUT_ACTIONS.MOVE_RIGHT))-Number(input.isActive(INPUT_ACTIONS.MOVE_LEFT)),speed=input.isActive(INPUT_ACTIONS.RUN)?PLAYER.runSpeed:PLAYER.walkSpeed,dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed*dt,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*speed*dt;if(!collides(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(!collides(camera.position.x,camera.position.z+dz))camera.position.z+=dz;const crossing=transitionManager.tryCrossing({levelNumber:currentIndex+1,previousPosition,currentPosition:camera.position,yaw,pitch,velocity:{x:dt?dx/dt:0,y:0,z:dt?dz/dt:0},isEnabled:transition=>transition.enabledWhen==="always"||(transition.enabledWhen==="guide-complete"&&exitOpened)});if(crossing){const target=levelManager.ensure(crossing.targetLevel);addChunk(target.maze);camera.position.set(crossing.position.x,crossing.position.y,crossing.position.z);yaw=crossing.yaw;pitch=crossing.pitch;}const motion=Math.hypot(camera.position.x-observedPlayerX,camera.position.z-observedPlayerZ);if(motion>.035){observedPlayerX=camera.position.x;observedPlayerZ=camera.position.z;lastPlayerMoveAt=now;}const playerIdle=now-lastPlayerMoveAt>PLAYER.idleDelay;
    const detectedRecord=levelManager.findByPosition(camera.position.x,camera.position.z),detected=detectedRecord?.index??currentIndex;if(detected!==currentIndex){currentIndex=detected;const enteredRecord=levelManager.ensure(currentIndex+1);audio.setLevelAudio(enteredRecord.config.audio,enteredRecord.bounds);levelLabel.textContent=t("game.level",{level:currentIndex+1});traversedEl.textContent=String(currentIndex);stream();companion.visible=false;audio.setFollowing(false);guidePath=[];lastPlayerCell="";lastRemainingSteps=Infinity;playerOnCorrectRoute=false;if(enteredRecord.config.guide.enabled&&!guideCompletedLevels.has(currentIndex+1)){guideChunk=currentIndex;guideActive=true;guidePhase="rebirth";rebirthAt=now+350;}else{guideActive=false;guidePhase=guideCompletedLevels.has(currentIndex+1)?"completed":"inactive";}markSave("level-change");}
    const creatureRecord=levelManager.ensure(currentIndex+1);creatureManager.update({now,dt,level:currentIndex+1,config:creatureRecord.config.creatures,maze:creatureRecord.maze,camera,walls:rendered.get(currentIndex)?.walls??[]});
    updateGuide(dt,now,playerIdle);
    inventory.forEach((object,index)=>{const angle=inventory.length?(index-selectedIndex)/inventory.length*Math.PI*2:0;const tx=tabOpen?Math.sin(angle)*.34:camera.aspect*.48-(index%5)*.095,ty=tabOpen?-.12:-.30+Math.floor(index/5)*.09,tz=tabOpen?-.65+Math.cos(angle)*.18:-.9,scale=tabOpen?.32:.11;object.position.lerp(new THREE.Vector3(tx,ty,tz),.13);object.scale.lerp(new THREE.Vector3(scale,scale,scale),.13);object.rotation.y+=tabOpen?.008:.015;});
    if(++frame%RENDERING.interactionRefreshFrames===0){raycaster.setFromCamera(new THREE.Vector2(0,0),camera);const available=interactables.filter(o=>!inventory.includes(o)&&o.parent===scene);const hits=raycaster.intersectObjects(available,true);hovered=null;for(const hit of hits){if(hit.distance>INTERACTION.rayDistance)break;let o=hit.object;while(o&&!o.userData.interactable)o=o.parent;if(o?.userData.interactable&&!inventory.includes(o)){hovered=o;break;}}
      if(!hovered){const direction=new THREE.Vector3();camera.getWorldDirection(direction);let bestDistance=Infinity;for(const candidate of available){const toward=candidate.getWorldPosition(new THREE.Vector3()).sub(camera.position),distance=toward.length();if(distance<INTERACTION.proximityDistance&&toward.normalize().dot(direction)>INTERACTION.proximityAlignment&&distance<bestDistance){hovered=candidate;bestDistance=distance;}}}
      renderActions();for(const chunk of rendered.values())updateWallVisibility(chunk.walls,camera.position.x,camera.position.z,{distance:RENDERING.wallDistance,margin:RENDERING.wallSafetyMargin,hysteresis:RENDERING.wallHysteresis});}
    updateExitOpening(now);for(const artifact of artifacts)if(artifact.parent===scene){artifact.rotation.y+=dt*1.5;artifact.rotation.x+=dt*.8;artifact.position.y=.25+Math.sin(now*.0025+artifact.position.x)*.04;}
    renderer.render(scene,camera);raf=requestAnimationFrame(animate);
  }
  raf=requestAnimationFrame(animate);
  const cleanup=()=>{gameDisposed=true;autosave?.stop();removeEventListener("beforeunload",beforeUnload);unsubscribeControls();unsubscribeLocale();pauseMenu.hidden=true;debugSession.dispose();input.dispose();cancelAnimationFrame(raf);clearInterval(clockTimer);for(const id of pendingTimeouts)clearTimeout(id);pendingTimeouts.clear();clearTimeout(showNotice.timer);notice.hidden=true;game.classList.remove("flash");creatureManager.clear();audio.stop();for(const chunk of rendered.values())disposeChunk(chunk);rendered.clear();for(const door of physicalDoors)disposePhysicalDoor(door);physicalDoors.length=0;for(const object of new Set(interactables)){object.parent?.remove(object);disposeObjectTree(object);}interactables.length=0;disposeObjectTree(companion);levelObjects.clear();levelObjectStates.clear();levelSaveMetadata.clear();levelRoutes.clear();transitionManager.clear();levelManager.clear();wallMaterial.dispose();floorMaterial.dispose();ceilingMaterial.dispose();graffitiMaterial?.dispose();graffitiTexture?.dispose();document.exitPointerLock?.();renderer.domElement.removeEventListener("click",pointerLock);renderer.renderLists?.dispose();renderer.dispose();viewport.replaceChildren();radialMenu.replaceChildren();for(const[element,type,handler]of mobileListeners)element.removeEventListener(type,handler);mobileListeners.length=0;removeEventListener("mousemove",mouse);removeEventListener("wheel",wheel);removeEventListener("pointerdown",pointerDown);removeEventListener("pointermove",pointerMove);removeEventListener("pointerup",pointerUp);removeEventListener("resize",resize);document.removeEventListener("pointerlockchange",lock);};cleanup.exportSave=exportGameState;cleanup.saveNow=reason=>autosave.flush(reason);return cleanup;
}
