import * as THREE from "../vendor/three.module.min.js";
import {MAZE_SIZE,CELL_SIZE,ENTRY_COLUMN,CHUNK_LENGTH,findMazePath} from "./maze.js";
import {BackroomsAudio} from "./audio.js";
import {PLAYER,CAMERA,ARCHITECTURE,RENDERING,INTERACTION} from "./config.js";
import {getLevelConfig} from "./levels/index.js";
import {LevelManager} from "./systems/level-manager.js";

const $=selector=>document.querySelector(selector);
const home=$("#home"),game=$("#game"),viewport=$("#viewport"),prompt=$("#prompt"),interaction=$("#interaction"),radialMenu=$("#radial-menu"),notice=$("#notice"),items=$("#items"),objective=$("#objective"),levelLabel=$("#level"),seedLabel=$("#seed"),inventoryEl=$("#inventory"),inventoryIndex=$("#inventory-index"),thirstEl=$("#thirst"),hungerEl=$("#hunger"),timeEl=$("#time"),traversedEl=$("#traversed"),modal=$("#modal"),modalTitle=$("#modal-title"),modalText=$("#modal-text");
let cleanupGame=null;

function showNotice(text,duration=3000){notice.textContent=text;notice.hidden=false;clearTimeout(showNotice.timer);showNotice.timer=setTimeout(()=>notice.hidden=true,duration);}

function startGame(){
  home.hidden=true;game.hidden=false;window.scrollTo(0,0);cleanupGame?.();cleanupGame=createGame();
}
$("#play").addEventListener("click",startGame);$("#play-footer").addEventListener("click",startGame);
$("#quit").addEventListener("click",()=>{cleanupGame?.();cleanupGame=null;game.hidden=true;home.hidden=false;});

function createGame(){
  const levelOne=getLevelConfig(1),objectPlacement=Object.fromEntries(levelOne.objects.map(object=>[object.id,object]));
  const worldSeed=Math.floor(100000+Math.random()*899999);seedLabel.textContent=`SEED ${worldSeed}`;
  const levelManager=new LevelManager(worldSeed);levelManager.ensure(1);
  const scene=new THREE.Scene();scene.background=new THREE.Color(levelOne.appearance.background);scene.fog=new THREE.FogExp2(levelOne.appearance.fog,levelOne.appearance.fogDensity);
  const camera=new THREE.PerspectiveCamera(CAMERA.fieldOfView,innerWidth/innerHeight,CAMERA.near,CAMERA.far);scene.add(camera);camera.position.set((ENTRY_COLUMN+.5)*CELL_SIZE,PLAYER.height,2.2);
  const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,RENDERING.maxPixelRatio));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;viewport.appendChild(renderer.domElement);
  const audio=new BackroomsAudio(),keys=new Set(),raycaster=new THREE.Raycaster(),rendered=new Map(),inventory=[],pendingTimeouts=new Set(),mobileListeners=[];
  const schedule=(callback,delay)=>{const id=setTimeout(()=>{pendingTimeouts.delete(id);callback();},delay);pendingTimeouts.add(id);return id;};
  let selectedIndex=0,tabOpen=false,thirst=0,hunger=0,elapsed=0,dragging=false,lastDragX=0;
  const wallMaterial=new THREE.MeshStandardMaterial({color:levelOne.appearance.wall,roughness:.95}),floorMaterial=new THREE.MeshStandardMaterial({color:levelOne.appearance.floor,roughness:1}),ceilingMaterial=new THREE.MeshStandardMaterial({color:levelOne.appearance.ceiling,roughness:.9}),panelMaterial=new THREE.MeshBasicMaterial({color:levelOne.appearance.lightPanel});
  scene.add(new THREE.HemisphereLight(0xd8ca6a,0x2a2417,.62));
  let currentIndex=0,yaw=Math.PI,pitch=0,last=performance.now(),raf=0,hovered=null,muted=false;

  function definition(index){return levelManager.ensure(index+1).maze;}
  function addChunk(data){
    if(rendered.has(data.index))return;const group=new THREE.Group(),walls=[];
    const wall=(x,z,horizontal,cellSize)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(horizontal?cellSize+ARCHITECTURE.wallThickness:ARCHITECTURE.wallThickness,ARCHITECTURE.wallHeight,horizontal?ARCHITECTURE.wallThickness:cellSize+ARCHITECTURE.wallThickness),wallMaterial);mesh.position.set(x,ARCHITECTURE.wallHeight/2,z);group.add(mesh);walls.push(mesh);};
    data.cells.forEach((row,y)=>row.forEach((cell,x)=>{const wx=data.originX+x*data.cellSize,wz=data.originZ+y*data.cellSize;if(cell.n)wall(wx+data.cellSize/2,wz,true,data.cellSize);if(cell.w)wall(wx,wz+data.cellSize/2,false,data.cellSize);if(x===data.width-1&&cell.e)wall(wx+data.cellSize,wz+data.cellSize/2,false,data.cellSize);}));
    const floor=new THREE.Mesh(new THREE.PlaneGeometry(data.worldWidth,data.worldLength),floorMaterial);floor.rotation.x=-Math.PI/2;floor.position.set(data.originX+data.worldWidth/2,0,data.originZ+data.worldLength/2);group.add(floor);
    const ceiling=new THREE.Mesh(new THREE.PlaneGeometry(data.worldWidth,data.worldLength),ceilingMaterial);ceiling.rotation.x=Math.PI/2;ceiling.position.set(data.originX+data.worldWidth/2,ARCHITECTURE.wallHeight,data.originZ+data.worldLength/2);group.add(ceiling);
    if(levelOne.lighting.enabled)for(let y=2;y<data.height;y+=levelOne.lighting.spacing)for(let x=2;x<data.width;x+=levelOne.lighting.spacing){const light=new THREE.PointLight(levelOne.appearance.light,levelOne.lighting.intensity,levelOne.lighting.distance,2);light.position.set(data.originX+x*data.cellSize,3,data.originZ+y*data.cellSize);group.add(light);const panel=new THREE.Mesh(new THREE.BoxGeometry(2.7,.035,.42),panelMaterial);panel.position.copy(light.position);panel.position.y=3.21;group.add(panel);}
    scene.add(group);rendered.set(data.index,{data,group,walls});
  }
  function stream(){levelManager.setActive(currentIndex+1);for(const record of levelManager.streamingWindow())addChunk(definition(record.index));for(const[index,chunk]of rendered)if(!levelManager.shouldRemainLoaded(index+1)){scene.remove(chunk.group);chunk.group.traverse(object=>object.geometry?.dispose());rendered.delete(index);}}
  stream();
  const openingRoute=findMazePath(definition(0),camera.position.x,camera.position.z);
  function routePosition(progress,lateral=0){const index=Math.max(0,Math.min(openingRoute.length-1,Math.round(progress*(openingRoute.length-1)))),point=openingRoute[index],neighbor=openingRoute[Math.min(openingRoute.length-1,index+1)]||openingRoute[Math.max(0,index-1)],dx=neighbor.x-point.x,dz=neighbor.z-point.z,length=Math.hypot(dx,dz)||1;return{x:point.x-dz/length*lateral,z:point.z+dx/length*lateral};}
  function placeOnRoute(object,progress,height,lateral=0){const p=routePosition(progress,lateral);object.position.set(p.x,height,p.z);}
  function collides(x,z){const activeRecord=levelManager.ensure(currentIndex+1);if(levelOne.exit.lockedUntilGuide&&!guideActive&&currentIndex===0&&z>activeRecord.bounds.maxZ-ARCHITECTURE.exitSealDepth)return true;for(const chunk of rendered.values())for(const wall of chunk.walls){const p=wall.geometry.parameters;if(Math.abs(x-wall.position.x)<p.width/2+PLAYER.collisionRadius&&Math.abs(z-wall.position.z)<p.depth/2+PLAYER.collisionRadius)return true;}return false;}

  function makeRabbit(){
    const group=new THREE.Group(),fur=new THREE.MeshStandardMaterial({color:0xcc9977,roughness:1}),belly=new THREE.MeshStandardMaterial({color:0xddbbaa,roughness:1}),dark=new THREE.MeshStandardMaterial({color:0x17120f});
    const body=new THREE.Mesh(new THREE.SphereGeometry(.12,16,12),fur);body.scale.set(.9,1.15,.8);body.position.y=.13;const head=new THREE.Mesh(new THREE.SphereGeometry(.09,16,12),fur);head.position.y=.3;
    const ear1=new THREE.Mesh(new THREE.CapsuleGeometry(.025,.13,6,8),fur),ear2=ear1.clone();ear1.position.set(-.04,.45,0);ear1.rotation.z=.2;ear2.position.set(.045,.43,0);ear2.rotation.z=-.45;
    const eye=new THREE.Mesh(new THREE.SphereGeometry(.014,8,8),dark);eye.position.set(-.03,.32,.082);group.add(body,head,ear1,ear2,eye);group.scale.setScalar(1.15);group.rotation.y=.25;group.userData={id:"plush",icon:"🐰",name:"PELUCHE USÉE",description:"Une peluche de lapin qui a perdu un œil. Elle sent la moquette mouillée et l'abandon.",interactable:true,powered:false,fried:false};return group;
  }
  const plush=makeRabbit(),plushPlacement=objectPlacement.plush;placeOnRoute(plush,plushPlacement.progress,plushPlacement.height,plushPlacement.lateral);scene.add(plush);
  const battery=new THREE.Mesh(new THREE.CylinderGeometry(.05,.05,.27,16),new THREE.MeshStandardMaterial({color:0xe3cf36,metalness:.75,roughness:.28,emissive:0x332b00}));battery.rotation.z=Math.PI/2;battery.position.set(camera.position.x+.65,.3,3.65);battery.userData={id:"battery",name:"PILE AA",interactable:true};scene.add(battery);
  const batteryPlacement=objectPlacement.battery;placeOnRoute(battery,batteryPlacement.progress,batteryPlacement.height,batteryPlacement.lateral);battery.userData.icon="🔋";battery.userData.description="Une pile AA légèrement oxydée, mais encore chargée.";
  const displayBase=new THREE.Mesh(new THREE.BoxGeometry(.01,.01,.01),new THREE.MeshBasicMaterial());displayBase.visible=false;scene.add(displayBase);
  const artifactLight=new THREE.PointLight(0xffe77e,0,1,2);scene.add(artifactLight);
  const ringMaterial=new THREE.MeshBasicMaterial({color:0xe8d952,transparent:true,opacity:.55,side:THREE.DoubleSide});
  ringMaterial.dispose();

  function makeBook(id,name,color,description,progress,lateral){const object=new THREE.Mesh(new THREE.BoxGeometry(.3,.05,.4),new THREE.MeshStandardMaterial({color,roughness:.9}));placeOnRoute(object,progress,.03,lateral);object.rotation.y=progress*Math.PI;object.userData={id,icon:"📖",name,description,interactable:true};scene.add(object);return object;}
  function makeBottle(id,name,sips,progress,lateral){const group=new THREE.Group(),material=new THREE.MeshStandardMaterial({color:sips>2?0x2979ff:0x66ccff,transparent:true,opacity:.58,roughness:.15,metalness:.55}),body=new THREE.Mesh(new THREE.CylinderGeometry(.04,.04,.18,16),material),neck=new THREE.Mesh(new THREE.CylinderGeometry(.015,.04,.05,16),material),cap=new THREE.Mesh(new THREE.CylinderGeometry(.017,.017,.02,16),new THREE.MeshStandardMaterial({color:0x090909}));neck.position.y=.115;cap.position.y=.15;group.add(body,neck,cap);placeOnRoute(group,progress,.05,lateral);group.rotation.z=Math.PI/2;group.userData={id,icon:"💧",name,description:`Une bouteille contenant encore ${sips} gorgée${sips>1?"s":""}.`,sips,interactable:true};scene.add(group);return group;}
  const red=objectPlacement.book_red,green=objectPlacement.book_green,blue=objectPlacement.book_blue,whiteBookPlacement=objectPlacement.book_white,half=objectPlacement.water_half,full=objectPlacement.water_full;
  const redBook=makeBook("book","CARNET ROUGE (MESSAGE)",0x5a1818,"Le même avertissement couvre toutes les pages : la pile ne servirait à rien. Le texte semble vouloir vous décourager.",red.progress,red.lateral);
  const greenBook=makeBook("book_green","JOURNAL DE BORD",0x185a25,"Une phrase se répète : « ne cherchez pas, vous perdez votre temps ». L'encre devient tremblante vers la fin.",green.progress,green.lateral);
  const blueBook=makeBook("book_blue","MANUEL TECHNIQUE",0x18305a,"Un manuel absurde expliquant comment fermer l'onglet. Une page arrachée mentionne pourtant une lumière-guide.",blue.progress,blue.lateral);
  const whiteBook=makeBook("book_white","LIVRE BLANC IMMACULÉ",0xdddddd,"La couverture est parfaitement propre. À l'intérieur : « ARRÊTEZ DE CHERCHER. LA PILE NE SERT À RIEN. »",whiteBookPlacement.progress,whiteBookPlacement.lateral);
  const halfWater=makeBottle("water","BOUTEILLE D'EAU (À MOITIÉ VIDE)",2,half.progress,half.lateral);
  const fullWater=makeBottle("water_full","BOUTEILLE D'EAU (PLEINE)",4,full.progress,full.lateral);
  const interactables=[plush,battery,redBook,greenBook,blueBook,whiteBook,halfWater,fullWater];
  const artifacts=[];
  function createArtifact(position){const artifact=new THREE.Mesh(new THREE.TetrahedronGeometry(.13),new THREE.MeshStandardMaterial({color:0x111111,metalness:1,roughness:.2,emissive:0xffdf35,emissiveIntensity:1.2}));artifact.position.copy(position);artifact.position.y=.25;artifact.userData={id:"artifact",icon:"🔮",name:"ARTEFACT DE SEUIL",description:"Un fragment laissé par la lumière au passage entre deux labyrinthes.",interactable:true};artifact.add(new THREE.PointLight(0xffdf35,1.5,3.5));scene.add(artifact);artifacts.push(artifact);interactables.push(artifact);}
  const silhouette=new THREE.Group(),shadowMaterial=new THREE.MeshBasicMaterial({color:0x010101,fog:true});const shadowBody=new THREE.Mesh(new THREE.CapsuleGeometry(.22,1.35,6,10),shadowMaterial),shadowHead=new THREE.Mesh(new THREE.SphereGeometry(.2,12,10),shadowMaterial),shadowArmGeometry=new THREE.CapsuleGeometry(.055,1.35,4,8),shadowLeftArm=new THREE.Mesh(shadowArmGeometry,shadowMaterial),shadowRightArm=shadowLeftArm.clone();shadowBody.position.y=1.05;shadowBody.scale.set(.72,1,.48);shadowHead.position.set(0,2.02,0);shadowHead.rotation.z=.16;shadowLeftArm.position.set(-.28,1.05,0);shadowLeftArm.rotation.z=.08;shadowRightArm.position.set(.28,1.05,0);shadowRightArm.rotation.z=-.08;silhouette.add(shadowBody,shadowHead,shadowLeftArm,shadowRightArm);silhouette.visible=false;scene.add(silhouette);let silhouetteAppearedAt=0,silhouetteSeenAt=0,nextSilhouette=Infinity;

  const companion=new THREE.Group(),coreMat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true}),haloMat=new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.18,depthWrite:false,blending:THREE.AdditiveBlending});
  const core=new THREE.Mesh(new THREE.SphereGeometry(.17,18,14),coreMat),halo=new THREE.Mesh(new THREE.SphereGeometry(.4,18,14),haloMat),guideLight=new THREE.PointLight(0xffffff,0,8,2);companion.add(core,halo,guideLight);companion.visible=false;scene.add(companion);
  const vaporPositions=new Float32Array(54);for(let i=0;i<vaporPositions.length;i+=3){vaporPositions[i]=(Math.random()-.5)*.55;vaporPositions[i+1]=Math.random()*.4;vaporPositions[i+2]=(Math.random()-.5)*.55;}const vaporGeometry=new THREE.BufferGeometry();vaporGeometry.setAttribute("position",new THREE.BufferAttribute(vaporPositions,3));const vaporMaterial=new THREE.PointsMaterial({color:0xffffff,size:.09,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending}),vapor=new THREE.Points(vaporGeometry,vaporMaterial);vapor.visible=false;companion.add(vapor);
  let guideActive=false,guidePath=[],guideWaypoint=0,guidePhase="near",guideChunk=0,waitUntil=0,transitionStart=0,transitionStartY=1.78,rebirthAt=0,lastPlayerCell="",lastRemainingSteps=Infinity,playerOnCorrectRoute=false,lastPlayerMoveAt=performance.now(),observedPlayerX=camera.position.x,observedPlayerZ=camera.position.z,losAchievedAt=0,wasFollowing=false;
  const white=new THREE.Color(0xffffff),yellow=new THREE.Color(0xffdf35),losOrigin=new THREE.Vector3(),losTarget=new THREE.Vector3(),losDirection=new THREE.Vector3();
  function makeGuidePath(points,limit){guidePath=points.slice(1,limit?limit+1:undefined);guideWaypoint=0;}
  function activateGuide(x,z){if(!levelOne.guide.enabled)return;guideActive=true;guideChunk=currentIndex;companion.visible=true;companion.position.set(x,1.78,z);guideLight.intensity=3;guidePhase="near";objective.textContent="Suivez la lumière vers la sortie";showNotice("LE GUIDE EST ÉVEILLÉ");}
  function planGuide(){makeGuidePath(findMazePath(definition(currentIndex),companion.position.x,companion.position.z),4);guidePhase=guidePath.length?"guide":"wait";waitUntil=performance.now()+2500;}
  function planReturn(){makeGuidePath(findMazePath(definition(currentIndex),companion.position.x,companion.position.z,camera.position.x,camera.position.z));guidePhase=guidePath.length?"return":"near";}
  function checkLOS(){losOrigin.set(camera.position.x,1.625,camera.position.z);losTarget.set(companion.position.x,1.625,companion.position.z);losDirection.subVectors(losTarget,losOrigin);raycaster.far=losDirection.length();raycaster.set(losOrigin,losDirection.normalize());const walls=[];for(const chunk of rendered.values())walls.push(...chunk.walls);return raycaster.intersectObjects(walls,false).length===0;}
  function moveGuide(dt){const target=guidePath[guideWaypoint];if(!target)return true;const dx=target.x-companion.position.x,dz=target.z-companion.position.z,d=Math.hypot(dx,dz);if(d<.13){guideWaypoint++;return guideWaypoint>=guidePath.length;}const step=Math.min(d,2.65*dt),nx=companion.position.x+dx/d*step,nz=companion.position.z+dz/d*step;if(!collides(nx,companion.position.z))companion.position.x=nx;if(!collides(companion.position.x,nz))companion.position.z=nz;return false;}
  function updateGuide(dt,now,playerIdle){if(!guideActive)return;const playerDistance=Math.hypot(companion.position.x-camera.position.x,companion.position.z-camera.position.z),chunk=definition(currentIndex),exitX=chunk.originX+(chunk.exitColumn+.5)*CELL_SIZE,exitZ=chunk.originZ+(MAZE_SIZE-.5)*CELL_SIZE,playerExitDistance=Math.hypot(camera.position.x-exitX,camera.position.z-exitZ),guideExitDistance=Math.hypot(companion.position.x-exitX,companion.position.z-exitZ),cellX=Math.max(0,Math.min(MAZE_SIZE-1,Math.floor((camera.position.x-chunk.originX)/CELL_SIZE))),cellY=Math.max(0,Math.min(MAZE_SIZE-1,Math.floor((camera.position.z-chunk.originZ)/CELL_SIZE))),playerCell=`${currentIndex}:${cellX}:${cellY}`;
    if(playerExitDistance<2.4&&guideExitDistance<4.8&&!['complete','waitLevel','rebirth'].includes(guidePhase)){guidePhase="complete";transitionStart=now;transitionStartY=companion.position.y;guidePath=[];coreMat.color.set(0xffffff);haloMat.color.set(0xffffff);guideLight.color.set(0xffffff);vapor.visible=true;vapor.position.y=0;audio.setFollowing(false);objective.textContent="Franchissez le seuil";}
    if(playerCell!==lastPlayerCell&&!['complete','waitLevel','rebirth'].includes(guidePhase)){const remaining=findMazePath(chunk,camera.position.x,camera.position.z).length;if(Number.isFinite(lastRemainingSteps))playerOnCorrectRoute=remaining<lastRemainingSteps;lastRemainingSteps=remaining;lastPlayerCell=playerCell;if(playerOnCorrectRoute){makeGuidePath(findMazePath(chunk,companion.position.x,companion.position.z,camera.position.x,camera.position.z));guidePhase="follow";}else if(guidePhase==="follow"){guidePath=[];guidePhase="near";}}
    const following=['guide','wait','follow'].includes(guidePhase)&&playerDistance<4.5;audio.setFollowing(following);wasFollowing=following;
    if(!['complete','waitLevel','rebirth'].includes(guidePhase)){const exitNear=THREE.MathUtils.clamp(1-guideExitDistance/(CHUNK_LENGTH*.58),0,1),visible=THREE.MathUtils.smoothstep(playerDistance,.7,2.6);coreMat.color.copy(white).lerp(yellow,exitNear);haloMat.color.copy(white).lerp(yellow,exitNear);guideLight.color.copy(white).lerp(yellow,exitNear);coreMat.opacity=visible;haloMat.opacity=.2*visible;guideLight.intensity=visible*THREE.MathUtils.lerp(2.8,6.2,exitNear);}
    if(playerIdle&&guidePhase==="follow"){playerOnCorrectRoute=false;guidePath=[];guidePhase="near";}
    if(guidePhase==="follow"){if(guidePath.length&&moveGuide(dt))guidePath=[];if(!guidePath.length&&playerDistance>1.9)makeGuidePath(findMazePath(chunk,companion.position.x,companion.position.z,camera.position.x,camera.position.z));}
    else if(guidePhase==="near"){if(playerDistance>1.8)planReturn();else planGuide();}
    else if(guidePhase==="guide"){if(moveGuide(dt)){guidePhase="wait";waitUntil=now+2500;}}
    else if(guidePhase==="wait"){if(playerDistance<2.4)planGuide();else if(now>=waitUntil&&!checkLOS()){planReturn();losAchievedAt=0;}}
    else if(guidePhase==="return"){if(checkLOS()){if(!losAchievedAt)losAchievedAt=now;if(now-losAchievedAt>600){guidePhase="wait";waitUntil=now+2500;guidePath=[];losAchievedAt=0;}else if(moveGuide(dt))guidePhase="near";}else{losAchievedAt=0;if(moveGuide(dt))guidePhase="near";}}
    else if(guidePhase==="complete"){const progress=Math.min(1,(now-transitionStart)/1200),eased=1-Math.pow(1-progress,3);companion.position.y=THREE.MathUtils.lerp(transitionStartY,.2,eased);coreMat.opacity=1-progress;haloMat.opacity=.22*(1-progress);guideLight.intensity=4*Math.pow(1-progress,2);vaporMaterial.opacity=Math.sin(progress*Math.PI)*.85;vapor.position.y=progress*1.9;vapor.rotation.y+=dt*1.4;companion.scale.setScalar(1+progress*.35);if(progress>=1){if(levelOne.guide.leavesArtifact)createArtifact(companion.position);companion.visible=false;vapor.visible=false;guidePhase="waitLevel";showNotice("LE GUIDE A LAISSÉ UN ARTEFACT",2600);}}
    else if(guidePhase==="rebirth"&&now>=rebirthAt){companion.position.set(camera.position.x+1.3,1.78,camera.position.z+.5);companion.scale.setScalar(1);companion.visible=true;vapor.visible=false;vaporMaterial.opacity=0;coreMat.color.set(0xffffff);coreMat.opacity=1;haloMat.color.set(0xffffff);haloMat.opacity=.2;guideLight.color.set(0xffffff);guideLight.intensity=3.2;guidePhase="near";}
    if(!['complete','waitLevel','rebirth'].includes(guidePhase))companion.position.y=1.78+Math.sin(now*.0022)*.16;companion.rotation.y+=dt*.8;
  }

  function selectedObject(){return inventory.length?inventory[Math.max(0,Math.min(inventory.length-1,selectedIndex))]:null;}
  function actionsFor(object,inInventory=inventory.includes(object)){if(!object)return[];const actions=[];if(!inInventory)actions.push({key:"E",label:"PRENDRE",icon:"✋"});if(object.userData.description)actions.push({key:"F",label:"EXAMINER",icon:object.userData.icon||"◈"});if(object.userData.sips>0)actions.push({key:"R",label:"BOIRE",icon:"💧"});if(inInventory){actions.push({key:"G",label:"DÉPOSER",icon:"⬇️"});if(object===battery&&inventory.includes(plush))actions.push({key:"C",label:"METTRE DANS LAPIN",icon:"🔌"});if(object===plush&&object.userData.powered&&!object.userData.fried)actions.push({key:"H",label:"ALLUMER LE LAPIN",icon:"🔴"});}return actions;}
  function renderActions(){const object=tabOpen?selectedObject():hovered,actions=actionsFor(object);radialMenu.replaceChildren();radialMenu.hidden=!object||!actions.length;interaction.hidden=!object;if(object)interaction.textContent=tabOpen?object.userData.name:`OBJET — ${object.userData.name}`;actions.forEach((action,index)=>{const angle=index/actions.length*Math.PI*2-Math.PI/2,node=document.createElement("div"),radius=72;node.className="action-node";node.style.transform=`translate(${Math.cos(angle)*radius}px,${Math.sin(angle)*radius}px)`;node.innerHTML=`<strong>${action.key}</strong><span>${action.label}</span><i>${action.icon}</i>`;radialMenu.append(node);});}
  function updateInventory(){if(selectedIndex>=inventory.length)selectedIndex=Math.max(0,inventory.length-1);const selected=selectedObject();items.textContent=inventory.length?(tabOpen?`${selected.userData.icon||"◆"} ${selected.userData.name}`:inventory.map(o=>o.userData.icon||"◆").join("  ")):"Vide";inventoryIndex.textContent=inventory.length?`${selectedIndex+1}/${inventory.length}`:"";inventoryEl.classList.toggle("open",tabOpen);renderActions();}
  function take(object){camera.add(object);inventory.push(object);object.userData.worldScale=object.scale.x;object.scale.setScalar(.15);selectedIndex=inventory.length-1;hovered=null;interaction.hidden=true;updateInventory();if(inventory.includes(plush)&&inventory.includes(battery))objective.textContent="Ouvrez TAB, sélectionnez la pile et appuyez sur C";}
  function combine(){const selected=selectedObject();if(selected!==battery||!inventory.includes(plush)||plush.userData.powered)return;camera.remove(battery);inventory.splice(inventory.indexOf(battery),1);plush.userData.powered=true;plush.userData.name="PELUCHE MOTORISÉE";plush.userData.description="La pile est installée. Elle vibre doucement et attend d'être allumée avec H.";const glow=new THREE.PointLight(0xffd84a,.55,2.4,2);glow.userData.powerIndicator=true;plush.add(glow);selectedIndex=inventory.indexOf(plush);updateInventory();objective.textContent="Sélectionnez le lapin et appuyez sur H";showNotice("PILE INSTALLÉE — APPUYEZ SUR H");}
  function fry(){if(selectedObject()!==plush||!plush.userData.powered||plush.userData.fried)return;plush.userData.fried=true;plush.userData.name="PELUCHE GRILLÉE";plush.userData.description="Elle a fait PZZZ et dégage une odeur de brûlé. Son œil émet une lumière rouge.";const indicator=plush.children.find(o=>o.userData.powerIndicator);if(indicator)plush.remove(indicator);plush.traverse(o=>{if(o.material){o.material=o.material.clone();o.material.color?.setHex(0x222222);}});const red=new THREE.PointLight(0xff0000,3,10,2);plush.add(red);audio.electrical();game.classList.add("flash");schedule(()=>game.classList.remove("flash"),550);objective.textContent="Appuyez sur G pour jeter le lapin au sol";showNotice("LE LAPIN GRÉSILLE — JETEZ-LE AVEC G",4200);updateInventory();}
  function dropSelected(){const object=selectedObject();if(!object)return;inventory.splice(selectedIndex,1);camera.remove(object);const forward=new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion).setY(0).normalize(),position=camera.position.clone().add(forward.multiplyScalar(.8));object.position.copy(position);object.position.y=.06;object.scale.setScalar(object.userData.worldScale||1);scene.add(object);updateInventory();if(object===plush&&plush.userData.fried){scene.remove(plush);objective.textContent="Le lapin se transforme…";schedule(()=>activateGuide(position.x,position.z),450);}}
  function examine(){const object=tabOpen?selectedObject():hovered;if(!object)return;document.exitPointerLock();modalTitle.textContent=object.userData.name||"OBJET INCONNU";modalText.textContent=object.userData.description||"Aucune information.";modal.hidden=false;}
  function drink(){const object=tabOpen?selectedObject():hovered;if(!object?.userData.sips)return;object.userData.sips--;thirst=Math.max(0,thirst-15);if(!object.userData.sips){object.userData.id="water_empty";object.userData.icon="🫙";object.userData.name="BOUTEILLE VIDE";object.userData.description="Juste un bout de plastique transparent. Vous devriez probablement la jeter.";object.traverse(child=>{if(child.material){child.material=child.material.clone();child.material.opacity=.15;child.material.color?.setHex(0xaaaaaa);}});}else{object.userData.description=`Il reste ${object.userData.sips} gorgée(s).`;object.userData.name=object.userData.sips===1?"BOUTEILLE D'EAU (PRESQUE VIDE)":object.userData.sips===2?"BOUTEILLE D'EAU (À MOITIÉ VIDE)":"BOUTEILLE D'EAU (ENTAMÉE)";}updateInventory();showNotice(object.userData.sips?"VOUS BUVEZ UNE GORGÉE":"LA BOUTEILLE EST VIDE",1600);}

  function pointerLock(){audio.start();renderer.domElement.requestPointerLock();}
  renderer.domElement.addEventListener("click",pointerLock);
  const mouse=e=>{if(document.pointerLockElement!==renderer.domElement)return;yaw-=e.movementX*CAMERA.mouseSensitivity;pitch=Math.max(-1.35,Math.min(1.35,pitch-e.movementY*CAMERA.mouseSensitivity));};
  const down=e=>{if(e.code==="Tab"){e.preventDefault();tabOpen=true;updateInventory();}keys.add(e.code);if(e.code==="KeyE"&&!tabOpen&&hovered)take(hovered);if(e.code==="KeyF")examine();if(e.code==="KeyC"&&tabOpen)combine();if(e.code==="KeyH"&&tabOpen)fry();if(e.code==="KeyG"&&tabOpen)dropSelected();if(e.code==="KeyR")drink();};
  const up=e=>{keys.delete(e.code);if(e.code==="Tab"){tabOpen=false;dragging=false;updateInventory();}},wheel=e=>{if(!tabOpen||!inventory.length)return;e.preventDefault();selectedIndex=(selectedIndex+(e.deltaY>0?1:-1)+inventory.length)%inventory.length;updateInventory();},pointerDown=e=>{if(tabOpen){dragging=true;lastDragX=e.clientX;}},pointerMove=e=>{if(!dragging||!tabOpen||!inventory.length)return;const delta=e.clientX-lastDragX;if(Math.abs(delta)>28){selectedIndex=(selectedIndex+(delta<0?1:-1)+inventory.length)%inventory.length;lastDragX=e.clientX;updateInventory();}},pointerUp=()=>dragging=false,lock=()=>{prompt.hidden=document.pointerLockElement===renderer.domElement;},resize=()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);};
  addEventListener("mousemove",mouse);addEventListener("keydown",down);addEventListener("keyup",up);addEventListener("wheel",wheel,{passive:false});addEventListener("pointerdown",pointerDown);addEventListener("pointermove",pointerMove);addEventListener("pointerup",pointerUp);addEventListener("resize",resize);document.addEventListener("pointerlockchange",lock);
  document.querySelectorAll("[data-move]").forEach(button=>{const code={forward:"KeyW",left:"KeyA",back:"KeyS",right:"KeyD"}[button.dataset.move],press=()=>keys.add(code),release=()=>keys.delete(code);button.addEventListener("pointerdown",press);mobileListeners.push([button,"pointerdown",press]);for(const type of["pointerup","pointercancel","pointerleave"]){button.addEventListener(type,release);mobileListeners.push([button,type,release]);}});
  $("#new-run").onclick=()=>{cleanupGame?.();cleanupGame=createGame();};
  $("#modal-close").onclick=()=>{modal.hidden=true;renderer.domElement.requestPointerLock();};
  $("#sound").onclick=()=>{muted=!muted;audio.mute(muted);$("#sound").textContent=muted?"SON OFF":"SON ON";};
  const clockTimer=setInterval(()=>{elapsed++;thirst=Math.min(100,thirst+.15);hunger=Math.min(100,hunger+.08);thirstEl.textContent=`${Math.floor(thirst)}%`;hungerEl.textContent=`${Math.floor(hunger)}%`;timeEl.textContent=`${String(Math.floor(elapsed/60)).padStart(2,"0")}:${String(elapsed%60).padStart(2,"0")}`;},1000);
  let frame=0;
  function animate(now){
    const dt=Math.min((now-last)/1000,.04);last=now;camera.rotation.set(pitch,yaw,0,"YXZ");const forward=Number(keys.has("KeyW")||keys.has("KeyZ")||keys.has("ArrowUp"))-Number(keys.has("KeyS")||keys.has("ArrowDown")),side=Number(keys.has("KeyD"))-Number(keys.has("KeyA")||keys.has("KeyQ")),speed=keys.has("ControlLeft")?PLAYER.runSpeed:PLAYER.walkSpeed,dx=(-Math.sin(yaw)*forward+Math.cos(yaw)*side)*speed*dt,dz=(-Math.cos(yaw)*forward-Math.sin(yaw)*side)*speed*dt;if(!collides(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(!collides(camera.position.x,camera.position.z+dz))camera.position.z+=dz;const motion=Math.hypot(camera.position.x-observedPlayerX,camera.position.z-observedPlayerZ);if(motion>.035){observedPlayerX=camera.position.x;observedPlayerZ=camera.position.z;lastPlayerMoveAt=now;}const playerIdle=now-lastPlayerMoveAt>PLAYER.idleDelay;
    const silhouetteStartIndex=levelOne.silhouettes.startLevel-1,detectedRecord=levelManager.findByPosition(camera.position.x,camera.position.z),detected=detectedRecord?.index??currentIndex;if(detected!==currentIndex){currentIndex=detected;levelLabel.textContent=`LABYRINTHE ${currentIndex+1}`;traversedEl.textContent=String(currentIndex);stream();silhouette.visible=false;if(levelOne.silhouettes.enabled&&currentIndex>=silhouetteStartIndex)nextSilhouette=now+15000;if(guideActive&&guideChunk!==currentIndex){guideChunk=currentIndex;lastPlayerCell="";lastRemainingSteps=Infinity;playerOnCorrectRoute=false;if(guidePhase==="waitLevel"){guidePhase="rebirth";rebirthAt=now+350;}else{guidePhase="complete";transitionStart=now;transitionStartY=companion.position.y;guidePath=[];coreMat.color.set(0xffffff);haloMat.color.set(0xffffff);guideLight.color.set(0xffffff);vapor.visible=true;vapor.position.y=0;}}}
    if(levelOne.silhouettes.enabled&&currentIndex>=silhouetteStartIndex&&!silhouette.visible&&now>=nextSilhouette){const route=findMazePath(definition(currentIndex),camera.position.x,camera.position.z),walls=rendered.get(currentIndex)?.walls||[];let spawned=false;for(let i=route.length-1;i>=1;i--){const point=route[i],distance=Math.hypot(point.x-camera.position.x,point.z-camera.position.z);if(distance<13||distance>29)continue;losOrigin.set(camera.position.x,1.55,camera.position.z);losTarget.set(point.x,1.55,point.z);losDirection.subVectors(losTarget,losOrigin);raycaster.far=losDirection.length();raycaster.set(losOrigin,losDirection.normalize());if(raycaster.intersectObjects(walls,false).length)continue;silhouette.position.set(point.x,0,point.z);silhouette.lookAt(camera.position.x,1.1,camera.position.z);silhouette.visible=true;silhouetteAppearedAt=now;silhouetteSeenAt=0;spawned=true;break;}if(!spawned)nextSilhouette=now+12000;}
    if(silhouette.visible){const look=new THREE.Vector3();camera.getWorldDirection(look);const toward=silhouette.position.clone().sub(camera.position).normalize();if(look.dot(toward)>.965){if(!silhouetteSeenAt)silhouetteSeenAt=now;if(now-silhouetteSeenAt>450){silhouette.visible=false;nextSilhouette=now+60000+Math.random()*50000;}}else silhouetteSeenAt=0;if(now-silhouetteAppearedAt>8000){silhouette.visible=false;nextSilhouette=now+60000+Math.random()*50000;}}
    updateGuide(dt,now,playerIdle);
    inventory.forEach((object,index)=>{const angle=inventory.length?(index-selectedIndex)/inventory.length*Math.PI*2:0;const tx=tabOpen?Math.sin(angle)*.34:camera.aspect*.48-(index%5)*.095,ty=tabOpen?-.12:-.30+Math.floor(index/5)*.09,tz=tabOpen?-.65+Math.cos(angle)*.18:-.9,scale=tabOpen?.32:.11;object.position.lerp(new THREE.Vector3(tx,ty,tz),.13);object.scale.lerp(new THREE.Vector3(scale,scale,scale),.13);object.rotation.y+=tabOpen?.008:.015;});
    if(++frame%RENDERING.interactionRefreshFrames===0){raycaster.setFromCamera(new THREE.Vector2(0,0),camera);const available=interactables.filter(o=>!inventory.includes(o)&&o.parent===scene);const hits=raycaster.intersectObjects(available,true);hovered=null;for(const hit of hits){if(hit.distance>INTERACTION.rayDistance)break;let o=hit.object;while(o&&!o.userData.interactable)o=o.parent;if(o?.userData.interactable&&!inventory.includes(o)){hovered=o;break;}}
      if(!hovered){const direction=new THREE.Vector3();camera.getWorldDirection(direction);let bestDistance=Infinity;for(const candidate of available){const toward=candidate.getWorldPosition(new THREE.Vector3()).sub(camera.position),distance=toward.length();if(distance<INTERACTION.proximityDistance&&toward.normalize().dot(direction)>INTERACTION.proximityAlignment&&distance<bestDistance){hovered=candidate;bestDistance=distance;}}}
      renderActions();for(const chunk of rendered.values())for(const wall of chunk.walls)wall.visible=Math.hypot(camera.position.x-wall.position.x,camera.position.z-wall.position.z)<RENDERING.wallDistance;}
    for(let i=artifacts.length-1;i>=0;i--){const artifact=artifacts[i];if(Math.hypot(camera.position.x-artifact.position.x,camera.position.z-artifact.position.z)>44){scene.remove(artifact);interactables.splice(interactables.indexOf(artifact),1);artifacts.splice(i,1);artifact.geometry.dispose();artifact.material.dispose();}else{artifact.rotation.y+=dt*1.5;artifact.rotation.x+=dt*.8;artifact.position.y=.25+Math.sin(now*.0025+artifact.position.x)*.04;}}
    renderer.render(scene,camera);raf=requestAnimationFrame(animate);
  }
  raf=requestAnimationFrame(animate);
  return()=>{cancelAnimationFrame(raf);clearInterval(clockTimer);for(const id of pendingTimeouts)clearTimeout(id);pendingTimeouts.clear();clearTimeout(showNotice.timer);notice.hidden=true;game.classList.remove("flash");audio.stop();levelManager.clear();document.exitPointerLock?.();renderer.domElement.removeEventListener("click",pointerLock);renderer.dispose();viewport.replaceChildren();radialMenu.replaceChildren();for(const[element,type,handler]of mobileListeners)element.removeEventListener(type,handler);mobileListeners.length=0;removeEventListener("mousemove",mouse);removeEventListener("keydown",down);removeEventListener("keyup",up);removeEventListener("wheel",wheel);removeEventListener("pointerdown",pointerDown);removeEventListener("pointermove",pointerMove);removeEventListener("pointerup",pointerUp);removeEventListener("resize",resize);document.removeEventListener("pointerlockchange",lock);};
}
