import {INPUT_CATALOG,INPUT_PROFILES,formatInputCode,keyboardEventInputCode,pointerEventInputCode} from "./input-bindings.js";
import {loadInputPreferences,remapInputBinding,resetInputPreferences,selectInputProfile} from "./input-preferences.js";

export class ControlsPanel{
  constructor({documentRef=globalThis.document,storage}={}){
    if(!documentRef?.createElement)throw new TypeError("Un document est requis.");this.document=documentRef;this.storage=storage;this.preferences=loadInputPreferences(storage);this.listeners=new Set();this.awaiting=null;this.pendingConflict=null;this.returnContext="home";
    const overlay=documentRef.createElement("div");overlay.className="controls-overlay";overlay.hidden=true;overlay.innerHTML=`<section class="controls-dialog" role="dialog" aria-modal="true" aria-labelledby="controls-title"><header><div><small>CONFIGURATION LOCALE</small><h2 id="controls-title">COMMANDES</h2></div><button type="button" data-controls-close aria-label="Fermer">×</button></header><div class="controls-profiles"><button type="button" data-profile="azerty">AZERTY</button><button type="button" data-profile="qwerty">QWERTY</button><button type="button" data-controls-reset>RÉINITIALISER</button></div><p class="controls-help">Sélectionnez une touche, puis appuyez sur sa remplaçante.</p><div class="controls-list" data-controls-list></div><div class="controls-conflict" data-controls-conflict hidden><p data-conflict-text></p><button type="button" data-conflict-confirm>ÉCHANGER LES TOUCHES</button><button type="button" data-conflict-cancel>ANNULER</button></div><p class="controls-status" data-controls-status aria-live="polite"></p><footer><button type="button" data-controls-done>TERMINER</button></footer></section>`;documentRef.body.append(overlay);this.overlay=overlay;this.list=overlay.querySelector("[data-controls-list]");this.status=overlay.querySelector("[data-controls-status]");this.conflict=overlay.querySelector("[data-controls-conflict]");this.conflictText=overlay.querySelector("[data-conflict-text]");this.onClick=event=>this.#click(event);this.onKeyDown=event=>this.#keyDown(event);this.onMouseButton=event=>this.#mouseButton(event);overlay.addEventListener("click",this.onClick);globalThis.addEventListener?.("keydown",this.onKeyDown,true);globalThis.addEventListener?.("mousedown",this.onMouseButton,true);globalThis.addEventListener?.("mouseup",this.onMouseButton,true);globalThis.addEventListener?.("auxclick",this.onMouseButton,true);this.render();
  }
  open(context="home"){this.returnContext=context;this.awaiting=null;this.pendingConflict=null;this.status.textContent="";this.conflict.hidden=true;this.preferences=loadInputPreferences(this.storage);this.render();this.overlay.hidden=false;this.overlay.querySelector("[data-controls-close]")?.focus();}
  close(){this.awaiting=null;this.pendingConflict=null;this.overlay.hidden=true;this.conflict.hidden=true;this.#emit("close");}
  isOpen(){return !this.overlay.hidden;}
  subscribe(listener){if(typeof listener!=="function")throw new TypeError("Abonné invalide.");this.listeners.add(listener);return()=>this.listeners.delete(listener);}
  render(){this.list.replaceChildren();for(const action of INPUT_CATALOG){const row=this.document.createElement("div"),codes=this.preferences.bindings[action.id]??[],layout=this.preferences.layout;row.className="controls-row";row.innerHTML=`<span><small>${action.category}</small><strong>${action.label}</strong></span><div>${codes.map((code,index)=>`<button type="button" data-bind-action="${action.id}" data-bind-slot="${index}">${formatInputCode(code,{layout})}</button>`).join("")}</div>`;this.list.append(row);}for(const button of this.overlay.querySelectorAll("[data-profile]"))button.classList.toggle("active",button.dataset.profile===this.preferences.profile||button.dataset.profile===this.preferences.layout);}
  dispose(){this.overlay.removeEventListener("click",this.onClick);globalThis.removeEventListener?.("keydown",this.onKeyDown,true);globalThis.removeEventListener?.("mousedown",this.onMouseButton,true);globalThis.removeEventListener?.("mouseup",this.onMouseButton,true);globalThis.removeEventListener?.("auxclick",this.onMouseButton,true);this.overlay.remove();this.listeners.clear();}
  #emit(type){for(const listener of this.listeners)listener({type,preferences:this.preferences,context:this.returnContext});}
  #setPreferences(preferences,message){this.preferences=preferences;this.awaiting=null;this.pendingConflict=null;this.conflict.hidden=true;this.status.textContent=message;this.render();this.#emit("change");}
  #click(event){const bind=event.target.closest?.("[data-bind-action]");if(bind){this.awaiting={action:bind.dataset.bindAction,slot:Number(bind.dataset.bindSlot)};this.pendingConflict=null;this.conflict.hidden=true;this.status.textContent=`Appuyez sur la nouvelle touche pour ${bind.textContent}. Échap annule.`;bind.classList.add("awaiting");return;}const profile=event.target.closest?.("[data-profile]")?.dataset.profile;if(profile){this.#setPreferences(selectInputProfile(profile,this.storage),`Profil ${profile.toUpperCase()} appliqué.`);return;}if(event.target.closest?.("[data-controls-reset]")){const profile=INPUT_PROFILES[this.preferences.profile]?this.preferences.profile:this.preferences.layout??"azerty";this.#setPreferences(resetInputPreferences(profile,this.storage),"Commandes réinitialisées.");return;}if(event.target.closest?.("[data-conflict-confirm]")&&this.pendingConflict){const pending=this.pendingConflict,result=remapInputBinding(this.preferences,pending.action,pending.code,{slot:pending.slot,replaceConflict:true,storage:this.storage});this.#setPreferences(result.preferences,"Touches échangées.");return;}if(event.target.closest?.("[data-conflict-cancel]")){this.pendingConflict=null;this.awaiting=null;this.conflict.hidden=true;this.status.textContent="Modification annulée.";this.render();return;}if(event.target===this.overlay||event.target.closest?.("[data-controls-close],[data-controls-done]"))this.close();}
  #keyDown(event){if(!this.isOpen())return;if(!this.awaiting){if(event.code==="Escape"){event.preventDefault();event.stopImmediatePropagation?.();this.close();}return;}event.preventDefault();event.stopImmediatePropagation?.();if(event.code==="Escape"){this.awaiting=null;this.status.textContent="Modification annulée.";this.render();return;}try{const inputCode=keyboardEventInputCode(event),result=remapInputBinding(this.preferences,this.awaiting.action,inputCode,{slot:this.awaiting.slot,storage:this.storage}),label=formatInputCode(inputCode);if(result.changed){this.#setPreferences(result.preferences,`${label} attribuée.`);return;}this.pendingConflict={...this.awaiting,code:inputCode};this.awaiting=null;this.conflictText.textContent=`${label} est déjà utilisée par une autre action.`;this.conflict.hidden=false;this.status.textContent="Confirmez l’échange ou annulez.";this.render();}catch(error){this.status.textContent=error.message;this.awaiting=null;this.render();}}
  #mouseButton(event){if(!this.isOpen())return;const inputCode=pointerEventInputCode(event);if(!inputCode)return;event.preventDefault();event.stopImmediatePropagation?.();if(event.type!=="mousedown"||!this.awaiting)return;try{const result=remapInputBinding(this.preferences,this.awaiting.action,inputCode,{slot:this.awaiting.slot,storage:this.storage}),label=formatInputCode(inputCode);if(result.changed){this.#setPreferences(result.preferences,`${label} attribuée.`);return;}this.pendingConflict={...this.awaiting,code:inputCode};this.awaiting=null;this.conflictText.textContent=`${label} est déjà utilisée par une autre action.`;this.conflict.hidden=false;this.status.textContent="Confirmez l’échange ou annulez.";this.render();}catch(error){this.status.textContent=error.message;this.awaiting=null;this.render();}}
}
