import * as THREE from "../vendor/three.module.min.js";
import {TransitionManager} from "../js/systems/transition-manager.js";
import {LevelManager} from "../js/systems/level-manager.js";
import {createDoorAssembly,DoorController} from "../js/systems/door.js";
import {createItem} from "../js/systems/item-registry.js";
import {snapshotItem,restoreItem} from "../js/systems/item-persistence.js";
import {createLevelLighting} from "../js/systems/level-lighting.js";
import {disposeObjectTree} from "../js/systems/resource-disposal.js";
import {BackroomsAudio} from "../js/audio.js";
import {getLevelConfig} from "../js/levels/index.js";
import {loadOptionalDebug} from "../js/systems/optional-debug.js";
import {updateWallVisibility,wallVisibilityThresholds} from "../js/systems/wall-visibility.js";
import {circleIntersectsMeshes} from "../js/systems/collision.js";
import {calculateInteractionLayout,shouldShowInteractionLabel} from "../js/systems/interaction-layout.js";

function assert(condition,message){if(!condition)throw new Error(message);}
function test(name,callback){try{callback();console.log(`✓ ${name}`);}catch(error){console.error(`✗ ${name}: ${error.message}`);throw error;}}

test("faux mur : passage vers le niveau 2 et retour",()=>{const manager=new LevelManager(424242),one=manager.ensure(1),two=manager.ensure(2),transitions=new TransitionManager(),exitX=one.originX+(one.maze.exitColumn+.5)*one.maze.cellSize,entryX=two.originX+(two.maze.entryColumn+.5)*two.maze.cellSize;transitions.registerAnchor({id:"hidden-exit",level:1,position:{x:exitX,y:0,z:one.bounds.maxZ},yaw:0,width:one.maze.cellSize,height:3.25,depth:1.2});transitions.registerAnchor({id:"return-wall",level:2,position:{x:entryX,y:0,z:two.bounds.minZ},yaw:0,width:two.maze.cellSize,height:3.25,depth:1.2});transitions.register(getLevelConfig(1).transitions[0]);const forward=transitions.tryCrossing({levelNumber:1,previousPosition:{x:exitX,y:1.7,z:one.bounds.maxZ-1},currentPosition:{x:exitX,y:1.7,z:one.bounds.maxZ+.2},isEnabled:()=>true});assert(forward?.targetLevel===2,"aller absent");transitions.releaseExitedAnchors(2,{x:entryX,y:1.7,z:two.bounds.minZ+2});const back=transitions.tryCrossing({levelNumber:2,previousPosition:{x:entryX,y:1.7,z:two.bounds.minZ+1},currentPosition:{x:entryX,y:1.7,z:two.bounds.minZ-.2},isEnabled:()=>true});assert(back?.targetLevel===1,"retour absent");});

test("porte physique : niveau 2 vers 3 et retour",()=>{const manager=new LevelManager(525252),two=manager.ensure(2),three=manager.ensure(3),x=two.originX+(two.maze.exitColumn+.5)*two.maze.cellSize,z=two.bounds.maxZ;assert(Math.abs(z-three.bounds.minZ)<1e-9,"sols désalignés");assert(manager.findByPosition(x,z-.01)?.levelNumber===2,"côté niveau 2 absent");assert(manager.findByPosition(x,z+.01)?.levelNumber===3,"côté niveau 3 absent");});

test("porte : contraste, ouverture, fermeture et sécurité en mouvement",()=>{const assembly=createDoorAssembly({width:2,height:2}),controller=new DoorController(assembly,{maxAngle:Math.PI/2,duration:1000,playerRadius:.15}),panelColor=assembly.doorPanel.material.color,frameColor=assembly.leftPost.material.color,contrast=Math.hypot(panelColor.r-frameColor.r,panelColor.g-frameColor.g,panelColor.b-frameColor.b);assert(panelColor.getHex()===0xe7e3d5,"panneau de porte non blanc");assert(contrast>.55,"cadre insuffisamment contrasté");controller.open(0);controller.update(1000,{x:5,z:5});assert(!controller.moving&&controller.angle===controller.maxAngle,"ouverture incomplète");controller.close(1100);controller.update(2100,{x:5,z:5});assert(controller.angle===0,"fermeture incomplète");controller.open(2200);controller.update(2700,{x:-.292893,z:.707107});assert(controller.blocked&&!controller.moving,"joueur traversé");assembly.dispose();});

test("objet : inventaire et état persistants",()=>{const item=createItem("water_half",{userData:{instanceId:"test-water",level:1}}),inventory=[item],manager=new LevelManager(626262);item.userData.sips=0;item.userData.name="BOUTEILLE VIDE";for(let level=1;level<=8;level++){manager.setActive(level);manager.streamingWindow();}assert(inventory[0]===item&&inventory[0].userData.sips===0,"inventaire modifié");const restored=restoreItem(snapshotItem(item));assert(restored.userData.instanceId==="test-water"&&restored.userData.sips===0,"état au sol perdu");disposeObjectTree(item);disposeObjectTree(restored);});

test("son et éclairage diffèrent entre les cartes",()=>{const profiles=[1,2,3].map(level=>getLevelConfig(level)),ambiences=new Set(profiles.map(config=>config.audio.ambience)),modes=new Set(profiles.map(config=>config.lighting.mode));assert(ambiences.size===3,"ambiances identiques");assert(modes.size===3,"éclairages identiques");const manager=new LevelManager(727272),controllers=profiles.map((config,index)=>createLevelLighting(manager.ensure(index+1).maze,config.lighting,config.appearance,1));assert(controllers.every(controller=>controller.lights.length>0),"éclairage manquant");controllers.forEach(controller=>controller.dispose());});

test("luminaires : centrés, dirigés vers le sol et hors des colonnes",()=>{const manager=new LevelManager(737373);for(let level=1;level<=3;level++){const record=manager.ensure(level),config=getLevelConfig(level),controller=createLevelLighting(record.maze,config.lighting,config.appearance,1),columns=new Set((record.maze.features??[]).filter(feature=>feature.type==="column").map(feature=>`${feature.x},${feature.y}`));assert(controller.lights.length===controller.panels.length,"panneau sans lumière");controller.lights.forEach((light,index)=>{const x=(light.position.x-record.maze.originX)/record.maze.cellSize,z=(light.position.z-record.maze.originZ)/record.maze.cellSize,panel=controller.panels[index];assert(Math.abs(x-Math.floor(x)-.5)<1e-9&&Math.abs(z-Math.floor(z)-.5)<1e-9,"luminaire hors du centre d’une cellule");assert(!columns.has(`${light.userData.cellX},${light.userData.cellY}`),"luminaire placé sur une colonne");assert(panel.position.x===light.position.x&&panel.position.z===light.position.z,"panneau désaligné de sa lumière");assert(panel.position.y<3.25,"panneau au-dessus du plafond");assert(light.isSpotLight&&light.target.position.y<light.position.y,"lumière non dirigée vers le sol");assert(light.target.position.x===light.position.x&&light.target.position.z===light.position.z,"faisceau lumineux incliné");});controller.dispose();}});

test("murs : marge de brouillard et hystérésis sans effet sur les collisions",()=>{const geometry=new THREE.BoxGeometry(5,.13,3.25),material=new THREE.MeshBasicMaterial(),wall=new THREE.Mesh(geometry,material),thresholds=wallVisibilityThresholds({distance:50,margin:20,hysteresis:5});wall.position.set(0,0,0);updateWallVisibility([wall],-72.6,0,{distance:50,margin:20,hysteresis:5});assert(!wall.visible,"mur lointain encore affiché");assert(circleIntersectsMeshes(0,0,.32,[wall]),"collision supprimée avec le rendu");updateWallVisibility([wall],-68,0,{distance:50,margin:20,hysteresis:5});assert(!wall.visible,"hystérésis absente au retour");updateWallVisibility([wall],-(thresholds.showDistance+2.5),0,{distance:50,margin:20,hysteresis:5});assert(wall.visible,"mur non restauré dans la bande sûre");updateWallVisibility([wall],-55,0,{distance:50,margin:20,hysteresis:5});assert(wall.visible,"mur masqué dans la zone garantie");assert(thresholds.guaranteed===50&&thresholds.showDistance===65&&thresholds.hideDistance===70,"seuils incorrects");geometry.dispose();material.dispose();});

test("interactions : disposition lisible sans nom redondant",()=>{for(const height of[320,480,720,1160])for(let count=1;count<=5;count++){const layout=calculateInteractionLayout(count,height,{compact:height<=480}),buttonBottom=layout.radius+layout.cardHeight/2;assert(layout.labelOffset-buttonBottom>=12,"marge insuffisante sous les actions");assert(layout.labelOffset<height/2,"description hors de l’écran");}assert(calculateInteractionLayout(1,720).radius<calculateInteractionLayout(4,720).radius,"nombre d’actions ignoré");assert(shouldShowInteractionLabel({objectAvailable:true,inventoryOpen:false}),"nom de l’objet au sol absent");assert(!shouldShowInteractionLabel({objectAvailable:true,inventoryOpen:true}),"nom répété dans l’inventaire");assert(!shouldShowInteractionLabel({objectAvailable:false,inventoryOpen:false}),"nom affiché sans objet");});

class Param{constructor(){this.value=0;}setValueAtTime(value){this.value=value;}exponentialRampToValueAtTime(value){this.value=value;}linearRampToValueAtTime(value){this.value=value;}cancelScheduledValues(){}setTargetAtTime(value){this.value=value;}}
class AudioNodeMock{constructor(){this.gain=new Param();this.frequency=new Param();this.positionX=new Param();this.positionY=new Param();this.positionZ=new Param();}connect(target){return target;}disconnect(){}start(){}stop(){}}
class AudioContextMock{constructor(){this.currentTime=0;this.state="running";this.sampleRate=10;this.destination=new AudioNodeMock();this.listener=new AudioNodeMock();}resume(){return Promise.resolve();}createGain(){return new AudioNodeMock();}createBiquadFilter(){return new AudioNodeMock();}createOscillator(){return new AudioNodeMock();}createBufferSource(){return new AudioNodeMock();}createPanner(){return new AudioNodeMock();}createBuffer(){return{getChannelData:()=>new Float32Array(20)};}close(){this.state="closed";return Promise.resolve();}}

globalThis.AudioContext=AudioContextMock;
const audio=new BackroomsAudio();await audio.start();
test("longue session : fenêtre et audio restent bornés",()=>{const manager=new LevelManager(828282);for(let level=1;level<=60;level++){manager.setActive(level);manager.streamingWindow();const previous=[...audio.sources];audio.setLevelAudio(getLevelConfig(level%3+1).audio);previous.forEach(source=>source.onended?.());assert(manager.loaded.size<=3,"plus de trois labyrinthes chargés");assert(audio.sources.length<=4,"sources audio accumulées");}assert([...manager.records.values()].filter(record=>record.maze).length<=3,"anciens labyrinthes conservés");});
audio.stop();
let debugImports=0;
const normalDebugSession=await loadOptionalDebug(Object.freeze({}),{search:"",importer:async()=>{debugImports++;throw new Error("import inattendu");}});
assert(!normalDebugSession.requested&&!normalDebugSession.loaded&&debugImports===0,"le mode normal tente de charger debug");
console.log("✓ jeu normal : aucun chargement du dossier debug");
let unavailableReported=false;
const missingDebugSession=await loadOptionalDebug(Object.freeze({}),{search:"?debug=1",importer:async()=>{debugImports++;throw new Error("404 debug/debug.js");},onUnavailable:()=>unavailableReported=true});
assert(missingDebugSession.requested&&!missingDebugSession.loaded&&unavailableReported&&debugImports===1,"module debug absent non contenu");
missingDebugSession.dispose();
console.log("✓ production ?debug=1 : module absent sans blocage");
console.log("\n11 scénarios de parcours et 2 scénarios d’absence debug validés.");
