import * as THREE from "../vendor/three.module.min.js";
import {readFileSync} from "node:fs";
import {TransitionManager} from "../js/systems/transition-manager.js";
import {LevelManager} from "../js/systems/level-manager.js";
import {createDoorAssembly,createDoorHeadWall,DoorController} from "../js/systems/door.js";
import {createItem,expandObjectRules} from "../js/systems/item-registry.js";
import {snapshotItem,restoreItem} from "../js/systems/item-persistence.js";
import {createLevelLighting} from "../js/systems/level-lighting.js";
import {disposeObjectTree} from "../js/systems/resource-disposal.js";
import {BackroomsAudio} from "../js/audio.js";
import {getLevelConfig} from "../js/levels/index.js";
import {loadOptionalDebug} from "../js/systems/optional-debug.js";
import {updateWallVisibility,wallVisibilityThresholds} from "../js/systems/wall-visibility.js";
import {circleIntersectsMeshes} from "../js/systems/collision.js";
import {calculateInteractionLayout,shouldShowInteractionLabel} from "../js/systems/interaction-layout.js";
import {INPUT_ACTIONS,INPUT_CATALOG,INPUT_PROFILES,RESERVED_INPUT_CODES,cloneInputBindings,findInputConflicts,formatInputCode,keyboardEventInputCode,pointerEventInputCode,validateInputBindings} from "../js/systems/input-bindings.js";
import {InputManager,isHoldInputAction} from "../js/systems/input-manager.js";
import {inputActionLabel,movementInputLabel,refreshInputLabels} from "../js/systems/input-labels.js";
import {JOURNAL_LIMITS,SAVE_SCHEMA_KIND,SAVE_SCHEMA_VERSION,SAVE_STORAGE_KEY,createEmptyLevelSave,createExplorationSave,migrateExplorationSave,parseExplorationSave,serializeExplorationSave,validateExplorationSave} from "../js/systems/save-schema.js";
import {resolveRestoredPlayerPosition} from "../js/systems/save-restoration.js";
import {AutosaveController,SAVE_BACKUP_KEY,createExplorationSaveStorage} from "../js/systems/save-storage.js";
import {findSafeGuideSpawn} from "../js/systems/guide-spawn.js";
import {buildSaveReport,readSaveReport} from "../js/systems/save-report.js";
import {deterministicReportVariant,formatReportDate,formatReportNumber,reportPluralKey} from "../js/systems/report-presentation.js";
import {ExplorationJournal} from "../js/systems/exploration-journal.js";
import {LOCALE_STORAGE_KEY,SUPPORTED_LOCALES,getLocale,getTranslationDiagnostics,setLocale,subscribeLocale,translate,translateDocument} from "../js/systems/i18n.js";
import {INPUT_STORAGE_KEY,loadInputPreferences,remapInputBinding,resetInputPreferences,selectInputProfile} from "../js/systems/input-preferences.js";
import {CreatureManager} from "../js/systems/creature-registry.js";
import {BATTERY_DEFAULT_CAPACITY,PLUSH_ACTIVATION_COST,PLUSH_POWER_STATES,burnOutPlush,extractBatteryFromPlush,installBatteryInPlush,normalizePlushPowerData,powerPlush} from "../js/systems/item-power-state.js";
import {applyFriedPlushAppearance} from "../js/systems/item-appearance.js";
import {POWER_LEVELS,POWER_SOURCE_KINDS,canInstallPowerSource,consumePowerSource,createPowerSlot,installPowerSource,powerLevel,removePowerSource} from "../js/systems/device-power.js";
import {reconcilePowerItems} from "../js/systems/item-power-migration.js";
import {CONTAINER_KINDS,UNIT_KINDS,addUnits,consumeUnits,createUnitContainer,hasUnits,normalizeUnitContainer,removeUnits} from "../js/systems/unit-container.js";
import {WATER_BOTTLE_TYPE,createWaterBottleContainer,reconcileUnitContainers} from "../js/systems/item-unit-migration.js";
import {inspectUnitTransfer,transferUnits,unitKindsCompatible} from "../js/systems/unit-transfer.js";
import {MEDICINE_KINDS,createMedicineBlister,drinkWaterDose,takeMedicineDose} from "../js/systems/consumable-use.js";
import {chamberRound,createMagazine,createPistol,firePistol,insertMagazine,reloadPistol,removeMagazine} from "../js/systems/firearm-state.js";
import {UNIT_INDICATOR_MODES,createUnitIndicatorModel} from "../js/systems/unit-indicator.js";

function assert(condition,message){if(!condition)throw new Error(message);}
function test(name,callback){try{callback();console.log(`✓ ${name}`);}catch(error){console.error(`✗ ${name}: ${error.message}`);throw error;}}

test("faux mur : passage vers le niveau 2 et retour",()=>{const manager=new LevelManager(424242),one=manager.ensure(1),two=manager.ensure(2),transitions=new TransitionManager(),exitX=one.originX+(one.maze.exitColumn+.5)*one.maze.cellSize,entryX=two.originX+(two.maze.entryColumn+.5)*two.maze.cellSize;transitions.registerAnchor({id:"hidden-exit",level:1,position:{x:exitX,y:0,z:one.bounds.maxZ},yaw:0,width:one.maze.cellSize,height:3.25,depth:1.2});transitions.registerAnchor({id:"return-wall",level:2,position:{x:entryX,y:0,z:two.bounds.minZ},yaw:0,width:two.maze.cellSize,height:3.25,depth:1.2});transitions.register(getLevelConfig(1).transitions[0]);const forward=transitions.tryCrossing({levelNumber:1,previousPosition:{x:exitX,y:1.7,z:one.bounds.maxZ-1},currentPosition:{x:exitX,y:1.7,z:one.bounds.maxZ+.2},isEnabled:()=>true});assert(forward?.targetLevel===2,"aller absent");transitions.releaseExitedAnchors(2,{x:entryX,y:1.7,z:two.bounds.minZ+2});const back=transitions.tryCrossing({levelNumber:2,previousPosition:{x:entryX,y:1.7,z:two.bounds.minZ+1},currentPosition:{x:entryX,y:1.7,z:two.bounds.minZ-.2},isEnabled:()=>true});assert(back?.targetLevel===1,"retour absent");});

test("porte physique : niveau 2 vers 3 et retour",()=>{const manager=new LevelManager(525252),two=manager.ensure(2),three=manager.ensure(3),x=two.originX+(two.maze.exitColumn+.5)*two.maze.cellSize,z=two.bounds.maxZ;assert(Math.abs(z-three.bounds.minZ)<1e-9,"sols désalignés");assert(manager.findByPosition(x,z-.01)?.levelNumber===2,"côté niveau 2 absent");assert(manager.findByPosition(x,z+.01)?.levelNumber===3,"côté niveau 3 absent");});

test("porte : contraste, ouverture, fermeture et sécurité en mouvement",()=>{const assembly=createDoorAssembly({width:2,height:2}),controller=new DoorController(assembly,{maxAngle:Math.PI/2,duration:1000,playerRadius:.15}),panelColor=assembly.doorPanel.material.color,frameColor=assembly.leftPost.material.color,contrast=Math.hypot(panelColor.r-frameColor.r,panelColor.g-frameColor.g,panelColor.b-frameColor.b);assert(panelColor.getHex()===0xe7e3d5,"panneau de porte non blanc");assert(contrast>.55,"cadre insuffisamment contrasté");controller.open(0);controller.update(1000,{x:5,z:5});assert(!controller.moving&&controller.angle===controller.maxAngle,"ouverture incomplète");controller.close(1100);controller.update(2100,{x:5,z:5});assert(controller.angle===0,"fermeture incomplète");controller.open(2200);controller.update(2700,{x:-.292893,z:.707107});assert(controller.blocked&&!controller.moving,"joueur traversé");assembly.dispose();});

test("porte : mur de tête raccordé au plafond sans collision basse",()=>{const material=new THREE.MeshStandardMaterial(),head=createDoorHeadWall({width:2.35,openingHeight:2.48,wallHeight:3.25,depth:.13,material}),size=new THREE.Vector3(),epsilon=1e-6;head.geometry.computeBoundingBox();head.geometry.boundingBox.getSize(size);assert(Math.abs(size.y-.77)<epsilon,"hauteur de remplissage incorrecte");assert(Math.abs(head.position.y+size.y/2-3.25)<epsilon,"remplissage non raccordé au plafond");assert(Math.abs(head.position.y-size.y/2-2.48)<epsilon,"remplissage non raccordé au linteau");assert(head.userData.nonBlocking===true,"mur de tête ajouté aux collisions basses");head.geometry.dispose();material.dispose();});

test("objet : inventaire et état persistants",()=>{const item=createItem("water_bottle",{userData:{instanceId:"test-water",level:1,container:createWaterBottleContainer(0)}}),inventory=[item],manager=new LevelManager(626262);item.userData.name="BOUTEILLE VIDE";for(let level=1;level<=8;level++){manager.setActive(level);manager.streamingWindow();}assert(inventory[0]===item&&inventory[0].userData.container.units===0,"inventaire modifié");const restored=restoreItem(snapshotItem(item));assert(restored.userData.instanceId==="test-water"&&restored.userData.container.units===0,"état au sol perdu");disposeObjectTree(item);disposeObjectTree(restored);});

test("lapin et pile : identités séparées, charge conservée et cycle irréversible",()=>{const plush=createItem("plush",{userData:{instanceId:"rabbit-1"}}),battery=createItem("battery",{userData:{instanceId:"battery-1"}}),installed=installBatteryInPlush(plush.userData,battery.userData);assert(installed.powerState===PLUSH_POWER_STATES.BATTERY_INSTALLED&&installed.containedBattery.instanceId==="battery-1","identité de pile perdue à l’installation");assert(installed.containedBattery.energy.charge===BATTERY_DEFAULT_CAPACITY,"charge initiale incorrecte");const powered=powerPlush(installed),burnt=burnOutPlush(powered.data);assert(powered.changed&&burnt.changed&&burnt.data.powerState===PLUSH_POWER_STATES.FRIED,"cycle d’activation incomplet");assert(burnt.remainingCharge===BATTERY_DEFAULT_CAPACITY-PLUSH_ACTIVATION_COST&&burnt.remainingCharge>0,"pile vidée par le lapin");assert(!powerPlush(burnt.data).changed,"lapin grillé rallumable");Object.assign(plush.userData,burnt.data);const restored=restoreItem(snapshotItem(plush));assert(restored.userData.containedBattery.instanceId==="battery-1"&&restored.userData.containedBattery.energy.charge===burnt.remainingCharge,"pile contenue non persistée");const legacy=normalizePlushPowerData({instanceId:"old-rabbit",powered:true,fried:true});assert(legacy.powerState===PLUSH_POWER_STATES.FRIED&&legacy.containedBattery.instanceId==="embedded-battery:old-rabbit","ancien lapin non normalisé");disposeObjectTree(plush);disposeObjectTree(battery);disposeObjectTree(restored);});

test("lapin grillé au sol : apparence lisible, persistance et guide unique",()=>{const plush=createItem("plush",{userData:{instanceId:"rabbit-ground",fried:true,powered:true,guideTriggered:true}});applyFriedPlushAppearance(plush);const fur=plush.children.find(child=>child.userData.plushPart==="fur"),indicator=plush.children.find(child=>child.userData.burntIndicator);assert(fur.material.color.getHex()===0x705548&&fur.material.color.getHex()!==0x222222,"lapin encore noir ou non brûlé");assert(indicator?.isPointLight&&indicator.intensity<1,"œil grillé trop lumineux ou absent");const restored=restoreItem(snapshotItem(plush));assert(restored.userData.instanceId==="rabbit-ground"&&restored.userData.guideTriggered&&restored.children.some(child=>child.userData.burntIndicator),"lapin au sol mal restauré");const source=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");assert(source.includes("plush.userData.fried&&!plush.userData.guideTriggered")&&source.includes("plush.userData.guideTriggered=true"),"guide redéclenchable");assert(!source.includes("plush.userData.consumed=true")&&!source.includes("disposeObjectTree(plush)"),"lapin encore consommé après dépôt");disposeObjectTree(plush);disposeObjectTree(restored);});

test("extraction de pile : une seule restitution, même identité et charge inconnue",()=>{setLocale("fr",{persist:false});const plush=createItem("plush",{userData:{instanceId:"rabbit-extract"}}),battery=createItem("battery",{userData:{instanceId:"battery-extract"}}),installed=installBatteryInPlush(plush.userData,battery.userData),burnt=burnOutPlush(powerPlush(installed).data),extracted=extractBatteryFromPlush(burnt.data);assert(extracted.changed&&extracted.battery.instanceId==="battery-extract","mauvaise pile extraite");assert(extracted.battery.energy.charge===BATTERY_DEFAULT_CAPACITY-PLUSH_ACTIVATION_COST,"charge restante modifiée à l’extraction");assert(extracted.data.fried&&!extracted.data.powered&&extracted.data.batteryExtracted&&!extracted.data.containedBattery,"compartiment non vidé");assert(!extractBatteryFromPlush(extracted.data).changed,"seconde extraction autorisée");Object.assign(plush.userData,extracted.data);const recovered=createItem("battery",{userData:{...extracted.battery,recoveredFromPlush:true}}),restoredPlush=restoreItem(snapshotItem(plush)),restoredBattery=restoreItem(snapshotItem(recovered));assert(restoredPlush.userData.batteryExtracted&&!restoredPlush.userData.containedBattery&&restoredBattery.userData.instanceId==="battery-extract","extraction non persistée");assert(restoredBattery.userData.description.includes("difficile")&&!restoredBattery.userData.description.includes(String(extracted.battery.energy.charge)),"charge exacte révélée ou description absente");const source=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");assert(source.includes('t("game.action.extractBattery")')&&source.includes('markSave("extract-battery")')&&source.includes('recordResource("battery","extracted"'),"interaction d’extraction non branchée");disposeObjectTree(plush);disposeObjectTree(battery);disposeObjectTree(recovered);disposeObjectTree(restoredPlush);disposeObjectTree(restoredBattery);});

test("alimentation générique : compatibilité, consommation, retrait et lampe simulée",()=>{const flashlight=createPowerSlot({acceptedKinds:[POWER_SOURCE_KINDS.AA_BATTERY]}),battery={type:"battery",instanceId:"flashlight-cell",powerSource:{kind:POWER_SOURCE_KINDS.AA_BATTERY,capacity:100,charge:65}},wrong={instanceId:"wrong-cell",kind:"battery-9v",capacity:100,charge:100};assert(canInstallPowerSource(flashlight,battery)&&!canInstallPowerSource(flashlight,wrong),"compatibilité de source incorrecte");assert(!installPowerSource(flashlight,wrong).changed&&installPowerSource(flashlight,wrong).reason==="incompatible","source incompatible acceptée");const installed=installPowerSource(flashlight,battery),used=consumePowerSource(installed.slot,40),removed=removePowerSource(used.slot);assert(installed.changed&&used.consumed===40&&used.slot.source.charge===25,"consommation de lampe incorrecte");assert(powerLevel(used.slot.source)===POWER_LEVELS.WEAK,"niveau qualitatif incorrect");assert(removed.changed&&removed.source.instanceId==="flashlight-cell"&&removed.source.charge===25&&!removed.slot.source,"identité ou charge perdue au retrait");const fixed=installPowerSource(createPowerSlot({acceptedKinds:[POWER_SOURCE_KINDS.AA_BATTERY],removable:false}),battery);assert(!removePowerSource(fixed.slot).changed,"source fixe retirée");const depleted=consumePowerSource(installed.slot,999);assert(depleted.slot.source.charge===0&&powerLevel(depleted.slot.source)===POWER_LEVELS.EMPTY,"épuisement non borné");const plushSource=readFileSync(new URL("../js/systems/item-power-state.js",import.meta.url),"utf8");for(const operation of["installPowerSource","consumePowerSource","removePowerSource"])assert(plushSource.includes(operation),`lapin non branché au contrat : ${operation}`);});

test("contenants à unités : normalisation, consommation, ajout et bornes",()=>{const bottle=createUnitContainer({capacity:4,units:2,unitKind:UNIT_KINDS.WATER_DOSE,reloadable:true,containerKind:CONTAINER_KINDS.BOTTLE});assert(bottle.capacity===4&&bottle.units===2&&hasUnits(bottle,2)&&!hasUnits(bottle,3),"bouteille normalisée incorrectement");const drunk=consumeUnits(bottle,1);assert(drunk.changed&&drunk.consumed===1&&drunk.container.units===1&&bottle.units===2,"consommation mutable ou incorrecte");const emptied=removeUnits(drunk.container,8);assert(emptied.removed===1&&emptied.container.units===0&&!removeUnits(emptied.container,1).changed,"retrait non borné");const refilled=addUnits(emptied.container,99);assert(refilled.added===4&&refilled.container.units===4,"remplissage non borné");const blister=createUnitContainer({capacity:8,units:3,unitKind:UNIT_KINDS.MEDICINE_TABLET,reloadable:false,containerKind:CONTAINER_KINDS.BLISTER});assert(!addUnits(blister,1).changed&&addUnits(blister,1).reason==="not-reloadable","plaquette rechargeable");const malformed=normalizeUnitContainer({capacity:-4,units:99,unitKind:""});assert(malformed.capacity===1&&malformed.units===1&&malformed.unitKind==="generic-unit","valeurs invalides non corrigées");assert(Object.isFrozen(bottle)&&Object.isFrozen(drunk.container),"états de contenant mutables");});

test("migration bouteilles : type unique, doses et identités conservés",()=>{const full=createItem("water_full",{userData:{instanceId:"legacy-full",level:1,sips:3}}),half=createItem("water_half",{userData:{instanceId:"legacy-half",level:2,sips:1}}),empty=createItem("water_empty",{userData:{instanceId:"legacy-empty",level:2,sips:0}}),level=createEmptyLevelSave();level.objects=[snapshotItem(half),snapshotItem(empty)];const save=createExplorationSave({seed:1818,inventory:[snapshotItem(full)],levels:{2:level}}),migration=reconcileUnitContainers(save),items=[...migration.save.inventory,...migration.save.levels[2].objects];assert(migration.diagnostics.normalized===3&&items.every(item=>item.type===WATER_BOTTLE_TYPE),"anciens types non remplacés");assert(items.map(item=>item.userData.container.units).join(",")==="3,1,0","gorgées perdues pendant la migration");assert(items.map(item=>item.userData.instanceId).join(",")==="legacy-full,legacy-half,legacy-empty","identités remplacées");assert(items.every(item=>item.userData.container.capacity===4&&item.userData.container.reloadable&&item.userData.container.unitKind===UNIT_KINDS.WATER_DOSE),"contrat de bouteille incorrect");const again=reconcileUnitContainers(migration.save);assert(JSON.stringify(again.save)===JSON.stringify(migration.save),"migration des bouteilles non idempotente");const rules=expandObjectRules(getLevelConfig(1).objects).filter(rule=>rule.type===WATER_BOTTLE_TYPE);assert(rules.length===2&&new Set(rules.map(rule=>rule.instanceId)).size===2&&rules.map(rule=>rule.userData.container.units).join(",")==="4,2","placements du niveau 1 non configurés");[full,half,empty].forEach(disposeObjectTree);});

test("transfert d’unités : compatibilité, politiques et conservation",()=>{const reservoir=createUnitContainer({capacity:8,units:6,unitKind:UNIT_KINDS.WATER_DOSE,reloadable:true}),bottle=createWaterBottleContainer(1),moved=transferUnits(reservoir,bottle,2,{sourceId:"source",targetId:"bottle"});assert(moved.changed&&moved.reason==="transferred"&&moved.transferred===2,"transfert compatible refusé");assert(moved.source.units===4&&moved.target.units===3&&reservoir.units+bottle.units===moved.source.units+moved.target.units,"unités créées ou perdues");assert(reservoir.units===6&&bottle.units===1,"état source modifié");const medicine=createUnitContainer({capacity:8,units:4,unitKind:UNIT_KINDS.MEDICINE_TABLET,reloadable:false,containerKind:CONTAINER_KINDS.BLISTER}),magazine=createUnitContainer({capacity:12,units:2,unitKind:UNIT_KINDS.AMMUNITION_9MM,reloadable:true,containerKind:CONTAINER_KINDS.MAGAZINE}),wrongAmmo=createUnitContainer({capacity:10,units:5,unitKind:"ammunition-45",reloadable:true,containerKind:CONTAINER_KINDS.MAGAZINE});assert(!unitKindsCompatible(medicine,bottle)&&!transferUnits(medicine,bottle,1).changed&&transferUnits(medicine,bottle,1).reason==="incompatible","ressource incompatible acceptée");assert(transferUnits(reservoir,medicine,1).reason==="not-reloadable","plaquette rechargée");assert(transferUnits(wrongAmmo,magazine,1).reason==="incompatible","munition incompatible acceptée");assert(inspectUnitTransfer(reservoir,bottle,-1).reason==="invalid-amount","quantité négative acceptée");assert(transferUnits(reservoir,createWaterBottleContainer(3),2).reason==="capacity-exceeded","surcharge partielle autorisée");assert(transferUnits(createWaterBottleContainer(1,8),createWaterBottleContainer(0),2).reason==="insufficient-units","source insuffisante ignorée");assert(transferUnits(reservoir,bottle,1,{sourceId:"same",targetId:"same"}).reason==="same-container","auto-transfert duplicateur accepté");});

test("consommables spécialisés : eau, soif et comprimés restent distincts",()=>{const bottle=createWaterBottleContainer(2),drink=drinkWaterDose(bottle,{thirst:42,relief:15});assert(drink.changed&&drink.reason==="drank"&&drink.container.units===1&&drink.thirst===27,"effet de la gorgée incorrect");const last=drinkWaterDose(drink.container,{thirst:7}),empty=drinkWaterDose(last.container,{thirst:last.thirst});assert(last.container.units===0&&last.thirst===0&&!empty.changed&&empty.reason==="empty","bouteille vide ou soif mal bornée");const blister=createMedicineBlister({capacity:6,tablets:2,medicineKind:MEDICINE_KINDS.ANALGESIC}),tablet=takeMedicineDose(blister);assert(tablet.changed&&tablet.reason==="medicine-taken"&&tablet.container.units===1&&blister.units===2,"prise de comprimé incorrecte ou mutable");assert(!blister.reloadable&&takeMedicineDose(bottle).reason==="not-medicine"&&drinkWaterDose(blister,{thirst:50}).reason==="not-water","comportements de consommables mélangés");const object=createItem("medicine_blister",{userData:{instanceId:"med-a"}});assert(object.userData.container.containerKind===CONTAINER_KINDS.BLISTER&&object.userData.nameKey==="item.medicineBlister.name","objet médical non enregistré ou traduit");const gameSource=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");assert(gameSource.includes("drinkWaterDose(object.userData.container,{thirst})"),"bouteille encore reliée directement au noyau quantitatif");disposeObjectTree(object);});

test("arme : chargeur, chambre, tir et rechargement restent cohérents",()=>{const pistol=createPistol({instanceId:"sidearm"}),magazine=createMagazine({instanceId:"mag-a",rounds:3}),inserted=insertMagazine(pistol,magazine);assert(inserted.changed&&inserted.firearm.magazine.instanceId==="mag-a"&&!pistol.magazine,"insertion mutable ou absente");const chambered=chamberRound(inserted.firearm);assert(chambered.changed&&chambered.firearm.chambered&&chambered.firearm.magazine.container.units===2,"chambrage incorrect");const fired=firePistol(chambered.firearm);assert(fired.fired&&fired.autoChambered&&fired.firearm.chambered&&fired.firearm.magazine.container.units===1,"cycle semi-automatique incorrect");const replacement=createMagazine({instanceId:"mag-b",rounds:5}),reloaded=reloadPistol(fired.firearm,replacement);assert(reloaded.changed&&reloaded.reason==="magazine-replaced"&&reloaded.ejectedMagazine.instanceId==="mag-a"&&reloaded.firearm.magazine.instanceId==="mag-b","changement de chargeur incomplet");const removed=removeMagazine(reloaded.firearm);assert(removed.changed&&removed.magazine.instanceId==="mag-b"&&!removed.firearm.magazine&&removed.firearm.chambered,"retrait du chargeur a perdu la cartouche chambrée");const shot=firePistol(removed.firearm);assert(shot.fired&&!shot.autoChambered&&!shot.firearm.chambered,"dernier tir sans chargeur incorrect");const wrong=createMagazine({instanceId:"wrong",caliber:"45",rounds:4});assert(insertMagazine(pistol,wrong).reason==="incompatible-magazine"&&!reloadPistol(reloaded.firearm,wrong).changed,"calibre incompatible accepté");assert(!firePistol(pistol).changed&&firePistol(pistol).reason==="not-chambered","tir à vide accepté");const magazineObject=createItem("magazine_9mm",{userData:{instanceId:"object-mag"}}),pistolObject=createItem("pistol_9mm",{userData:{instanceId:"object-gun"}});assert(magazineObject.userData.container.unitKind===UNIT_KINDS.AMMUNITION_9MM&&pistolObject.userData.firearm.instanceId==="object-gun"&&pistolObject.userData.nameKey==="item.pistol9mm.name","objets d’arme non enregistrés ou identité perdue");disposeObjectTree(magazineObject);disposeObjectTree(pistolObject);});

test("indicateur d’unités : cases, jauge, texte et traductions",()=>{const four=createUnitIndicatorModel(createWaterBottleContainer(3)),eight=createUnitIndicatorModel(createWaterBottleContainer(0,8)),bar=createUnitIndicatorModel(createUnitContainer({capacity:12,units:5})),text=createUnitIndicatorModel(createUnitContainer({capacity:64,units:64}));assert(four.mode===UNIT_INDICATOR_MODES.CELLS&&four.state==="partial"&&four.ratio===.75,"indicateur quatre cases incorrect");assert(eight.mode===UNIT_INDICATOR_MODES.CELLS&&eight.state==="empty","indicateur huit cases incorrect");assert(bar.mode===UNIT_INDICATOR_MODES.BAR&&bar.units===5&&text.mode===UNIT_INDICATOR_MODES.TEXT&&text.state==="full","repli jauge ou texte incorrect");for(const locale of["fr","en"]){setLocale(locale,{persist:false});for(const key of["unit.indicator.label","unit.state.empty","unit.state.partial","unit.state.full","unit.action.refilled","unit.error.incompatible","unit.error.notReloadable","unit.error.capacityExceeded","unit.error.insufficientUnits","unit.error.sameContainer","unit.error.invalidAmount"])assert(translate(key,{units:2,capacity:4})!==key,`traduction d’unité absente en ${locale} : ${key}`);}setLocale("fr",{persist:false});});

test("persistance des contenants : capacités, niveaux et unités conservés",()=>{const reservoir=createItem("water_bottle",{userData:{instanceId:"water-reservoir",level:2,container:createWaterBottleContainer(5,8)}}),bottle=createItem("water_bottle",{userData:{instanceId:"water-carried",level:1,container:createWaterBottleContainer(1)}}),refill=transferUnits(reservoir.userData.container,bottle.userData.container,3,{sourceId:reservoir.userData.instanceId,targetId:bottle.userData.instanceId});assert(refill.changed&&refill.source.units+refill.target.units===6,"recharge pré-sauvegarde non conservatrice");reservoir.userData.container=refill.source;bottle.userData.container=refill.target;const blister=createItem("medicine_blister",{userData:{instanceId:"med-empty",level:2,container:createMedicineBlister({tablets:0,medicineKind:MEDICINE_KINDS.ANALGESIC})}}),magazine=createItem("magazine_9mm",{userData:{instanceId:"mag-partial",level:2,container:createMagazine({rounds:5}).container}}),pistol=createItem("pistol_9mm",{userData:{instanceId:"gun-loaded",level:2,firearm:createPistol({instanceId:"gun-loaded",magazine:createMagazine({instanceId:"mag-inside",rounds:2}),chambered:true})}}),level=createEmptyLevelSave();level.objects=[snapshotItem(reservoir),snapshotItem(blister)];const save=createExplorationSave({seed:2020,level:2,inventory:[snapshotItem(bottle),snapshotItem(magazine),snapshotItem(pistol)],levels:{2:level}}),roundtrip=parseExplorationSave(serializeExplorationSave(save)),restoredInventory=roundtrip.inventory.map(restoreItem),restoredLevel=roundtrip.levels[2].objects.map(restoreItem),all=[...restoredInventory,...restoredLevel],byId=id=>all.find(item=>item.userData.instanceId===id);assert(byId("water-reservoir").userData.container.capacity===8&&byId("water-reservoir").userData.container.units===2,"réservoir partiel altéré");assert(byId("water-carried").userData.container.capacity===4&&byId("water-carried").userData.container.units===4,"bouteille rechargée altérée");assert(byId("water-reservoir").userData.container.units+byId("water-carried").userData.container.units===6,"unités perdues au changement de niveau");assert(byId("med-empty").userData.container.units===0&&!byId("med-empty").userData.container.reloadable,"plaquette épuisée restaurée à tort");assert(byId("mag-partial").userData.container.units===5&&byId("gun-loaded").userData.firearm.magazine.container.units===2&&byId("gun-loaded").userData.firearm.chambered,"chargeur ou chambre non restaurés");[reservoir,bottle,blister,magazine,pistol,...all].forEach(disposeObjectTree);});

test("migration lapin-pile : anciennes parties normalisées sans recréation ni doublon",()=>{const plush=createItem("plush",{userData:{instanceId:"legacy-rabbit"}}),battery=createItem("battery",{userData:{instanceId:"legacy-cell"}}),burnt=burnOutPlush(powerPlush(installBatteryInPlush(plush.userData,battery.userData)).data);Object.assign(plush.userData,burnt.data,{guideTriggered:true});const duplicate=snapshotItem(battery),level=createEmptyLevelSave();level.objects=[snapshotItem(plush)];const legacy=createExplorationSave({seed:1515,inventory:[duplicate],progress:{guide:{active:true,phase:"near",level:1,position:[1,1.78,1],completedLevels:[]}},levels:{1:level}}),reconciled=reconcilePowerItems(legacy);assert(reconciled.diagnostics.duplicatesRemoved===1&&reconciled.save.inventory.length===0,"pile embarquée dupliquée conservée");const migratedPlush=reconciled.save.levels[1].objects[0];assert(migratedPlush.userData.containedBattery.instanceId==="legacy-cell"&&migratedPlush.userData.containedBattery.energy.charge===65,"pile ancienne mal normalisée");const again=reconcilePowerItems(reconciled.save);assert(JSON.stringify(again.save)===JSON.stringify(reconciled.save),"réconciliation non idempotente");const missing=createExplorationSave({seed:1616,progress:{exitOpened:true,guide:{active:false,phase:"completed",level:1,position:[0,1.78,0],completedLevels:[1]}},levels:{1:createEmptyLevelSave()}}),decision=reconcilePowerItems(missing);assert(decision.diagnostics.legacyMissingPlush&&decision.diagnostics.policy==="preserve-absence"&&!decision.save.inventory.length&&!decision.save.levels[1].objects.length,"objets inventés dans une ancienne partie terminée");const extracted=extractBatteryFromPlush(migratedPlush.userData),standalone=createItem("battery",{userData:{...extracted.battery,recoveredFromPlush:true}});Object.assign(plush.userData,extracted.data);const current=createExplorationSave({seed:1717,inventory:[snapshotItem(plush),snapshotItem(standalone)]}),roundtrip=parseExplorationSave(serializeExplorationSave(reconcilePowerItems(current).save));assert(roundtrip.inventory.length===2&&new Set(roundtrip.inventory.map(item=>item.userData.instanceId)).size===2,"lapin et pile extraits perdus après reprise");disposeObjectTree(plush);disposeObjectTree(battery);disposeObjectTree(standalone);});

test("son et éclairage diffèrent entre les cartes",()=>{const profiles=[1,2,3].map(level=>getLevelConfig(level)),ambiences=new Set(profiles.map(config=>config.audio.ambience)),modes=new Set(profiles.map(config=>config.lighting.mode));assert(ambiences.size===3,"ambiances identiques");assert(modes.size===3,"éclairages identiques");const manager=new LevelManager(727272),controllers=profiles.map((config,index)=>createLevelLighting(manager.ensure(index+1).maze,config.lighting,config.appearance,1));assert(controllers.every(controller=>controller.lights.length>0),"éclairage manquant");controllers.forEach(controller=>controller.dispose());});

test("luminaires : centrés, dirigés vers le sol et hors des colonnes",()=>{const manager=new LevelManager(737373);for(let level=1;level<=3;level++){const record=manager.ensure(level),config=getLevelConfig(level),controller=createLevelLighting(record.maze,config.lighting,config.appearance,1),columns=new Set((record.maze.features??[]).filter(feature=>feature.type==="column").map(feature=>`${feature.x},${feature.y}`));assert(controller.lights.length===controller.panels.length,"panneau sans lumière");controller.lights.forEach((light,index)=>{const x=(light.position.x-record.maze.originX)/record.maze.cellSize,z=(light.position.z-record.maze.originZ)/record.maze.cellSize,panel=controller.panels[index];assert(Math.abs(x-Math.floor(x)-.5)<1e-9&&Math.abs(z-Math.floor(z)-.5)<1e-9,"luminaire hors du centre d’une cellule");assert(!columns.has(`${light.userData.cellX},${light.userData.cellY}`),"luminaire placé sur une colonne");assert(panel.position.x===light.position.x&&panel.position.z===light.position.z,"panneau désaligné de sa lumière");assert(panel.position.y<3.25,"panneau au-dessus du plafond");assert(light.isSpotLight&&light.target.position.y<light.position.y,"lumière non dirigée vers le sol");assert(light.target.position.x===light.position.x&&light.target.position.z===light.position.z,"faisceau lumineux incliné");});controller.dispose();}});

test("murs : marge de brouillard et hystérésis sans effet sur les collisions",()=>{const geometry=new THREE.BoxGeometry(5,.13,3.25),material=new THREE.MeshBasicMaterial(),wall=new THREE.Mesh(geometry,material),thresholds=wallVisibilityThresholds({distance:50,margin:20,hysteresis:5});wall.position.set(0,0,0);updateWallVisibility([wall],-72.6,0,{distance:50,margin:20,hysteresis:5});assert(!wall.visible,"mur lointain encore affiché");assert(circleIntersectsMeshes(0,0,.32,[wall]),"collision supprimée avec le rendu");updateWallVisibility([wall],-68,0,{distance:50,margin:20,hysteresis:5});assert(!wall.visible,"hystérésis absente au retour");updateWallVisibility([wall],-(thresholds.showDistance+2.5),0,{distance:50,margin:20,hysteresis:5});assert(wall.visible,"mur non restauré dans la bande sûre");updateWallVisibility([wall],-55,0,{distance:50,margin:20,hysteresis:5});assert(wall.visible,"mur masqué dans la zone garantie");assert(thresholds.guaranteed===50&&thresholds.showDistance===65&&thresholds.hideDistance===70,"seuils incorrects");geometry.dispose();material.dispose();});

test("interactions : disposition lisible sans nom redondant",()=>{for(const height of[320,480,720,1160])for(let count=1;count<=5;count++){const layout=calculateInteractionLayout(count,height,{compact:height<=480}),buttonBottom=layout.radius+layout.cardHeight/2;assert(layout.labelOffset-buttonBottom>=12,"marge insuffisante sous les actions");assert(layout.labelOffset<height/2,"description hors de l’écran");}assert(calculateInteractionLayout(1,720).radius<calculateInteractionLayout(4,720).radius,"nombre d’actions ignoré");assert(shouldShowInteractionLabel({objectAvailable:true,inventoryOpen:false}),"nom de l’objet au sol absent");assert(!shouldShowInteractionLabel({objectAvailable:true,inventoryOpen:true}),"nom répété dans l’inventaire");assert(!shouldShowInteractionLabel({objectAvailable:false,inventoryOpen:false}),"nom affiché sans objet");});

test("commandes : catalogue complet, profils valides et libellés de clavier",()=>{assert(INPUT_CATALOG.length===12,"catalogue incomplet");assert(validateInputBindings(INPUT_PROFILES.azerty).valid,"profil AZERTY invalide");assert(validateInputBindings(INPUT_PROFILES.qwerty).valid,"profil QWERTY invalide");assert(INPUT_PROFILES.azerty[INPUT_ACTIONS.MOVE_FORWARD][0]==="KeyZ"&&INPUT_PROFILES.qwerty[INPUT_ACTIONS.MOVE_FORWARD][0]==="KeyW","profils AZERTY/QWERTY identiques");assert(formatInputCode("KeyZ")==="Z"&&formatInputCode("KeyQ")==="Q"&&formatInputCode("KeyW")==="W","libellés AZERTY/QWERTY incorrects");assert(keyboardEventInputCode({key:"z",code:"KeyW"})==="KeyZ"&&keyboardEventInputCode({key:"w",code:"KeyZ"})==="KeyW","lettre logique du clavier ignorée");const custom=cloneInputBindings("azerty");custom[INPUT_ACTIONS.EXAMINE]=["KeyE"];assert(findInputConflicts(custom).some(conflict=>conflict.code==="KeyE"),"conflit non détecté");assert(!validateInputBindings(custom).valid,"conflit accepté");assert(RESERVED_INPUT_CODES.includes("F2")&&!validateInputBindings({...cloneInputBindings("azerty"),[INPUT_ACTIONS.DRINK]:["F2"]}).valid,"touche debug non réservée");assert(formatInputCode("ArrowUp")==="↑"&&formatInputCode("ControlLeft")==="CTRL","touches spéciales incorrectes");});

test("InputManager : maintien, pression unique, tactile, pause et nettoyage",()=>{class Target{constructor(){this.handlers=new Map();}addEventListener(type,handler){const handlers=this.handlers.get(type)??new Set();handlers.add(handler);this.handlers.set(type,handlers);}removeEventListener(type,handler){this.handlers.get(type)?.delete(handler);}emit(type,event={}){for(const handler of this.handlers.get(type)??[])handler({preventDefault(){},repeat:false,ctrlKey:false,altKey:false,metaKey:false,...event});}count(){return[...this.handlers.values()].reduce((sum,handlers)=>sum+handlers.size,0);}}const target=new Target(),input=new InputManager({target,bindings:INPUT_PROFILES.azerty});let interactions=0,releases=0;input.onPress(INPUT_ACTIONS.INTERACT,()=>interactions++);input.onRelease(INPUT_ACTIONS.MOVE_FORWARD,()=>releases++);target.emit("keydown",{code:"KeyE"});target.emit("keydown",{code:"KeyE",repeat:true});assert(interactions===1,"répétition automatique non ignorée");target.emit("keyup",{code:"KeyE"});target.emit("keydown",{code:"KeyW"});target.emit("keydown",{code:"ArrowUp"});target.emit("keyup",{code:"KeyW"});assert(input.isActive(INPUT_ACTIONS.MOVE_FORWARD),"action relâchée malgré une seconde touche");target.emit("keyup",{code:"ArrowUp"});assert(!input.isActive(INPUT_ACTIONS.MOVE_FORWARD)&&releases===1,"relâchement multiple incorrect");input.activate(INPUT_ACTIONS.MOVE_LEFT,"mobile:left");assert(input.isActive(INPUT_ACTIONS.MOVE_LEFT),"commande tactile inactive");input.deactivate(INPUT_ACTIONS.MOVE_LEFT,"mobile:left");assert(!input.isActive(INPUT_ACTIONS.MOVE_LEFT),"commande tactile bloquée");input.setEnabled(false);target.emit("keydown",{code:"KeyE"});assert(interactions===1,"action déclenchée pendant la pause");input.setEnabled(true);input.setBindings(INPUT_PROFILES.qwerty);target.emit("keydown",{code:"KeyZ"});assert(!input.isActive(INPUT_ACTIONS.MOVE_FORWARD),"mauvaise position active après changement de profil");target.emit("keydown",{code:"KeyW"});assert(input.isActive(INPUT_ACTIONS.MOVE_FORWARD),"position physique W/Z inactive");target.emit("keyup",{code:"KeyW"});assert(isHoldInputAction(INPUT_ACTIONS.RUN)&&!isHoldInputAction(INPUT_ACTIONS.INTERACT),"types d’action incorrects");target.emit("keydown",{code:"KeyE",ctrlKey:true});assert(interactions===1,"raccourci navigateur intercepté");input.dispose();assert(target.count()===0,"écouteurs non nettoyés");target.emit("keydown",{code:"KeyE"});assert(interactions===1,"gestionnaire actif après destruction");});

test("préférences : profils, disposition, persistance, conflit et réinitialisation",()=>{class Storage{constructor(){this.values=new Map();}getItem(key){return this.values.get(key)??null;}setItem(key,value){this.values.set(key,String(value));}removeItem(key){this.values.delete(key);}}const storage=new Storage();let preferences=selectInputProfile("qwerty",storage);assert(preferences.profile==="qwerty"&&preferences.layout==="qwerty"&&preferences.bindings[INPUT_ACTIONS.MOVE_FORWARD][0]==="KeyW","profil QWERTY non appliqué");preferences=loadInputPreferences(storage);assert(preferences.source==="storage"&&preferences.profile==="qwerty","préférences non rechargées");let remap=remapInputBinding(preferences,INPUT_ACTIONS.EXAMINE,"KeyE",{storage});assert(!remap.changed&&remap.conflict.action===INPUT_ACTIONS.INTERACT,"conflit non demandé");remap=remapInputBinding(preferences,INPUT_ACTIONS.EXAMINE,"KeyE",{replaceConflict:true,storage});assert(remap.changed&&remap.preferences.profile==="custom"&&remap.preferences.layout==="qwerty","disposition perdue après personnalisation");assert(remap.preferences.bindings[INPUT_ACTIONS.EXAMINE][0]==="KeyE"&&remap.preferences.bindings[INPUT_ACTIONS.INTERACT][0]==="KeyF","touches non échangées");assert(loadInputPreferences(storage).bindings[INPUT_ACTIONS.EXAMINE][0]==="KeyE","personnalisation non persistée");storage.setItem(INPUT_STORAGE_KEY,"{invalide");preferences=loadInputPreferences(storage);assert(preferences.recovered&&preferences.profile==="azerty"&&preferences.layout==="azerty","sauvegarde corrompue non restaurée");preferences=resetInputPreferences("qwerty",storage);assert(preferences.profile==="qwerty"&&preferences.layout==="qwerty"&&validateInputBindings(preferences.bindings).valid,"réinitialisation invalide");});

test("souris : boutons latéraux remappables et navigation bloquée",()=>{class Target{constructor(){this.handlers=new Map();}addEventListener(type,handler){const list=this.handlers.get(type)??new Set();list.add(handler);this.handlers.set(type,list);}removeEventListener(type,handler){this.handlers.get(type)?.delete(handler);}emit(type,event){for(const handler of this.handlers.get(type)??[])handler(event);}}const bindings=cloneInputBindings("azerty");bindings[INPUT_ACTIONS.EXAMINE]=["MouseBack"];const target=new Target(),input=new InputManager({target,bindings});let pressed=0,released=0,prevented=0,stopped=0;input.onPress(INPUT_ACTIONS.EXAMINE,()=>pressed++);input.onRelease(INPUT_ACTIONS.EXAMINE,()=>released++);const event=button=>({button,preventDefault(){prevented++;},stopImmediatePropagation(){stopped++;}});target.emit("mousedown",event(3));target.emit("mouseup",event(3));target.emit("auxclick",event(4));assert(pressed===1&&released===1,"bouton latéral non résolu");assert(prevented===3&&stopped===3,"navigation navigateur non bloquée");assert(pointerEventInputCode({button:3})==="MouseBack"&&pointerEventInputCode({button:4})==="MouseForward"&&formatInputCode("MouseBack")==="SOURIS 4","libellé souris invalide");input.dispose();});

test("libellés : accueil, HUD et actions suivent les préférences",()=>{const preferences=selectInputProfile("qwerty"),actionNode={dataset:{inputAction:INPUT_ACTIONS.INTERACT},textContent:""},movementNode={dataset:{},textContent:""},root={querySelectorAll(selector){return selector==="[data-input-action]"?[actionNode]:selector==="[data-input-movement]"?[movementNode]:[];}};refreshInputLabels(root,preferences);assert(actionNode.textContent==="E"&&movementNode.textContent==="WASD","rafraîchissement QWERTY incorrect");assert(inputActionLabel(preferences,INPUT_ACTIONS.INVENTORY)==="TAB"&&movementInputLabel(selectInputProfile("azerty"))==="ZQSD","libellés de profil incorrects");const html=readFileSync(new URL("../index.html",import.meta.url),"utf8"),gameSource=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");assert(html.includes("data-input-movement")&&html.includes('data-input-action="inventory"'),"zones dynamiques absentes");assert(gameSource.includes("inputActionLabel(inputPreferences,action)")&&gameSource.includes("activeObjective()")&&gameSource.includes("refreshGameTranslation()"),"actions, objectifs ou traduction dynamique absents");});

test("interface commandes : accès accueil, pause et reprise sans nouvelle partie",()=>{const html=readFileSync(new URL("../index.html",import.meta.url),"utf8"),gameSource=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");for(const id of["home-controls","game-pause","pause-menu","resume-game","pause-controls"])assert(html.includes(`id="${id}"`),`élément ${id} absent`);assert(html.includes("assets/controls.css"),"styles des commandes absents");assert(gameSource.includes("if(paused){renderer.render")&&gameSource.includes("if(paused)return;elapsed++"),"simulation non figée");assert(gameSource.includes("input.setBindings(event.preferences.bindings)"),"remappage non appliqué en jeu");});

test("pause : chronologies audio et créatures décalées",()=>{const creatures=new CreatureManager(new THREE.Scene()),instance={spawnedAt:200,seenAt:350};creatures.nextSpawn.set(1,1000);creatures.instances.push(instance);creatures.shiftTimeline(500);assert(creatures.nextSpawn.get(1)===1500&&instance.spawnedAt===700&&instance.seenAt===850,"chronologie créature non suspendue");creatures.instances.length=0;const audioTimeline=new BackroomsAudio();audioTimeline.nextEventAt=1200;audioTimeline.shiftTimeline(500);assert(audioTimeline.nextEventAt===1700,"chronologie audio non suspendue");});

class Param{constructor(){this.value=0;}setValueAtTime(value){this.value=value;}exponentialRampToValueAtTime(value){this.value=value;}linearRampToValueAtTime(value){this.value=value;}cancelScheduledValues(){}setTargetAtTime(value){this.value=value;}}
class AudioNodeMock{constructor(){this.gain=new Param();this.frequency=new Param();this.positionX=new Param();this.positionY=new Param();this.positionZ=new Param();}connect(target){return target;}disconnect(){}start(){}stop(){}}
class AudioContextMock{constructor(){this.currentTime=0;this.state="running";this.sampleRate=10;this.destination=new AudioNodeMock();this.listener=new AudioNodeMock();}resume(){return Promise.resolve();}createGain(){return new AudioNodeMock();}createBiquadFilter(){return new AudioNodeMock();}createOscillator(){return new AudioNodeMock();}createBufferSource(){return new AudioNodeMock();}createPanner(){return new AudioNodeMock();}createBuffer(){return{getChannelData:()=>new Float32Array(20)};}close(){this.state="closed";return Promise.resolve();}}

globalThis.AudioContext=AudioContextMock;
const audio=new BackroomsAudio();await audio.start();
test("longue session : fenêtre et audio restent bornés",()=>{const manager=new LevelManager(828282);for(let level=1;level<=60;level++){manager.setActive(level);manager.streamingWindow();const previous=[...audio.sources];audio.setLevelAudio(getLevelConfig(level%3+1).audio);previous.forEach(source=>source.onended?.());assert(manager.loaded.size<=3,"plus de trois labyrinthes chargés");assert(audio.sources.length<=4,"sources audio accumulées");}assert([...manager.records.values()].filter(record=>record.maze).length<=3,"anciens labyrinthes conservés");});
test("sauvegarde v2 : instantané complet et aller-retour JSON",()=>{const item={type:"plush",userData:{instanceId:"rabbit-1",powered:true,fried:false},position:[1,.2,3],rotation:[0,1,0,"XYZ"],scale:[1,1,1]},levelState=createEmptyLevelSave();levelState.objects.push(item);levelState.consumed.push("battery-1");levelState.creatures.push({type:"watcher",state:"hidden"});levelState.events.push({id:"hum-1",done:true});levelState.custom.puzzle={phase:2};const save=createExplorationSave({seed:424242,level:3,elapsed:875,position:[12,1.7,18],yaw:1.2,pitch:-.1,thirst:34,hunger:21,inventory:[item],progress:{exitOpened:true,doors:[{id:"door-2-3",angle:1.57}],transitions:[{id:"hidden-exit",enabled:true}],guide:{active:false,phase:"waitLevel"},artifacts:["artifact:0"]},levels:{1:levelState},createdAt:1000,updatedAt:2000}),restored=parseExplorationSave(serializeExplorationSave(save));assert(restored.kind===SAVE_SCHEMA_KIND&&restored.version===SAVE_SCHEMA_VERSION&&SAVE_STORAGE_KEY==="backrooms.save.v2","identité du schéma invalide");assert(restored.world.seed===424242&&restored.world.level===3&&restored.player.needs.thirst===34,"état principal perdu");assert(restored.inventory[0].userData.powered&&restored.levels[1].custom.puzzle.phase===2&&restored.levels[1].creatures[0].type==="watcher"&&restored.journal.coverage==="partial","état extensible perdu");item.userData.powered=false;assert(save.inventory[0].userData.powered,"instantané lié aux objets sources");});

test("sauvegarde v1 : valeurs incohérentes et objets Three.js refusés",()=>{const valid=createExplorationSave({seed:1}),broken=structuredClone(valid);broken.player.needs.thirst=Infinity;assert(!validateExplorationSave(broken).valid,"nombre infini accepté");const threeState=structuredClone(valid);threeState.levels={1:createEmptyLevelSave()};threeState.levels[1].custom.vector=new THREE.Vector3(1,2,3);assert(!validateExplorationSave(threeState).valid,"objet Three.js accepté");let parseRejected=false,migrationRejected=false;try{parseExplorationSave("{cassé");}catch{parseRejected=true;}try{migrateExplorationSave({...valid,version:0});}catch{migrationRejected=true;}assert(parseRejected&&migrationRejected,"sauvegarde illisible ou ancienne acceptée");});

test("sauvegarde v1 : chaque création produit des collections indépendantes",()=>{const first=createExplorationSave({seed:10,levels:{1:createEmptyLevelSave()}}),second=createExplorationSave({seed:20,levels:{1:createEmptyLevelSave()}});first.progress.doors.push({id:"a"});first.levels[1].events.push({id:"event"});assert(second.progress.doors.length===0&&second.levels[1].events.length===0,"collections partagées entre sauvegardes");});

test("restauration : le seed régénère exactement les mêmes labyrinthes",()=>{const first=new LevelManager(918273),second=new LevelManager(918273);for(let level=1;level<=5;level++){const a=first.ensure(level),b=second.ensure(level);assert(JSON.stringify(a.maze.cells)===JSON.stringify(b.maze.cells),`géométrie différente au niveau ${level}`);assert(a.originX===b.originX&&a.originZ===b.originZ&&a.maze.exitColumn===b.maze.exitColumn,`placement différent au niveau ${level}`);}first.clear();second.clear();});

test("restauration : position valide conservée et collision remplacée",()=>{const findLevel=(x,z)=>x>=0&&x<20&&z>=0&&z<20?{levelNumber:2}:null,collides=(x,z)=>x===9&&z===9,fallback=[2,1.7,2];assert(resolveRestoredPlayerPosition([5,1.7,6],{levelNumber:2,findLevel,collides,fallback})[0]===5,"position valide remplacée");assert(resolveRestoredPlayerPosition([9,1.7,9],{levelNumber:2,findLevel,collides,fallback})[0]===2,"collision non remplacée");assert(resolveRestoredPlayerPosition([30,1.7,30],{levelNumber:2,findLevel,collides,fallback})[0]===2,"mauvais niveau accepté");let rejected=false;try{resolveRestoredPlayerPosition([5,1.7,6],{levelNumber:2,findLevel,collides:()=>true,fallback});}catch{rejected=true;}assert(rejected,"repli dangereux accepté");});

test("restauration : createGame expose un export réutilisable",()=>{const source=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");assert(source.includes("function createGame(initialSave=null)")&&source.includes("migrateExplorationSave(initialSave)"),"entrée de restauration absente");assert(source.includes("cleanup.exportSave=exportGameState")&&source.includes("inventory:inventory.map(snapshotItem)"),"export de partie absent");assert(source.includes("resolveRestoredPlayerPosition")&&source.includes("levelObjectStates.set(Number(level)"),"position ou objets non restaurés");});

test("stockage de partie : écriture, lecture et suppression validées",()=>{class Storage{constructor(){this.values=new Map();}getItem(key){return this.values.get(key)??null;}setItem(key,value){this.values.set(key,String(value));}removeItem(key){this.values.delete(key);}}const raw=new Storage(),storage=createExplorationSaveStorage({storage:raw}),save=createExplorationSave({seed:777});assert(storage.read().status==="empty","stockage neuf non vide");assert(storage.write(save).ok,"écriture refusée");const loaded=storage.read();assert(loaded.ok&&loaded.save.world.seed===777,"lecture invalide");assert(storage.remove().ok&&storage.read().status==="empty","suppression invalide");});

test("stockage de partie : indisponibilité et corruption ne bloquent jamais",()=>{const unavailable=createExplorationSaveStorage({storage:{getItem(){throw new Error("private");},setItem(){throw new Error("quota");},removeItem(){throw new Error("private");}}});assert(!unavailable.read().ok&&!unavailable.write(createExplorationSave({seed:1})).ok&&!unavailable.remove().ok,"erreur de stockage propagée");const corrupt=createExplorationSaveStorage({storage:{getItem(){return "{cassé";},setItem(){},removeItem(){}}});assert(corrupt.read().status==="invalid","sauvegarde corrompue acceptée");});

test("migration : format legacy sauvegardé avant conversion v2",()=>{class Storage{constructor(raw){this.values=new Map([[SAVE_STORAGE_KEY,raw]]);}getItem(key){return this.values.get(key)??null;}setItem(key,value){this.values.set(key,String(value));}removeItem(key){this.values.delete(key);}}const level=createEmptyLevelSave(),legacy={version:0,seed:2468,level:2,elapsed:91,player:{position:[4,1.7,5],yaw:.4,pitch:0,thirst:12,hunger:8},inventory:[],progress:{exitOpened:false},levels:{1:level},savedAt:5000},raw=JSON.stringify(legacy),native=new Storage(raw),storage=createExplorationSaveStorage({storage:native}),result=storage.read();assert(result.ok&&result.status==="migrated"&&result.fromVersion===0,"migration v0 non exécutée");assert(result.save.version===2&&result.save.world.seed===2468&&result.save.world.level===2,"données legacy perdues");assert(native.getItem(SAVE_BACKUP_KEY)===raw&&storage.readBackup().raw===raw,"copie de secours absente");assert(JSON.parse(native.getItem(SAVE_STORAGE_KEY)).version===2,"format courant non réécrit");});

test("migration v1 : ancienne clé découverte sans route inventée",()=>{const current=createExplorationSave({seed:8642,level:3,elapsed:777,progress:{exitOpened:true,guide:{active:false,phase:"completed",level:2,position:[0,1.78,0],completedLevels:[1,2]}},levels:{1:createEmptyLevelSave()}}),legacy=structuredClone(current);legacy.version=1;delete legacy.journal;const raw=JSON.stringify(legacy),values=new Map([["backrooms.save.v1",raw]]),storage=createExplorationSaveStorage({storage:{getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)}}),result=storage.read();assert(result.ok&&result.status==="migrated"&&result.fromVersion===1&&result.sourceKey==="backrooms.save.v1","ancienne clé v1 non découverte");assert(result.save.version===2&&result.save.journal.coverage==="partial"&&result.save.journal.visitedLevels.length===1&&result.save.journal.visitedLevels[0].level===3,"journal v1 inventé ou incomplet");assert(result.save.journal.milestones.some(entry=>entry.id==="guide-complete:1")&&values.get(SAVE_BACKUP_KEY)===raw&&values.has(SAVE_STORAGE_KEY),"jalons ou sauvegarde de secours perdus");storage.remove();assert(!values.has(SAVE_STORAGE_KEY)&&!values.has("backrooms.save.v1"),"ancienne sauvegarde ressuscitable après suppression");});

test("migration : version inconnue conservée et signalée",()=>{const raw=JSON.stringify({version:99,secret:"future"}),values=new Map([[SAVE_STORAGE_KEY,raw]]),storage=createExplorationSaveStorage({storage:{getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)}}),result=storage.read();assert(!result.ok&&result.status==="incompatible"&&result.version===99,"version future non signalée");assert(values.get(SAVE_STORAGE_KEY)===raw&&!values.has(SAVE_BACKUP_KEY),"version inconnue modifiée");});

test("reprise complète : progression multi-niveaux conservée",()=>{const item=(type,id,level)=>({type,userData:{type,instanceId:id,level,powered:type==="plush",fried:false},position:[level,.2,level*2],rotation:[0,0,0,"XYZ"],scale:[1,1,1]}),one=createEmptyLevelSave(),two=createEmptyLevelSave(),three=createEmptyLevelSave();one.objects=[item("water_half","water-1",1)];one.consumed=["battery-1"];two.objects=[item("book","book-2",2)];two.doors=[{id:"door-2-3",angle:1.2}];three.objects=[item("artifact","artifact-3",3)];three.events=[{id:"arrival",done:true}];const original=createExplorationSave({seed:654321,level:3,elapsed:1842,position:[17,1.7,44],yaw:2.1,pitch:-.2,thirst:61,hunger:37,inventory:[item("plush","rabbit-1",1)],progress:{exitOpened:true,doors:[{sourceLevel:2,targetLevel:3,angle:1.2}],transitions:[{id:"hidden-exit",enabled:true}],guide:{active:false,phase:"waitLevel",level:2,position:[4,.2,8]},artifacts:[item("artifact","artifact-global",1)]},levels:{1:one,2:two,3:three},createdAt:10,updatedAt:20}),restored=parseExplorationSave(serializeExplorationSave(original));assert(restored.world.level===3&&restored.world.elapsed===1842&&restored.player.needs.hunger===37,"joueur multi-niveaux perdu");assert(restored.inventory[0].userData.instanceId==="rabbit-1"&&restored.levels[1].consumed[0]==="battery-1","inventaire ou consommation perdu");assert(restored.progress.exitOpened&&restored.progress.doors[0].angle===1.2&&restored.progress.guide.phase==="waitLevel","porte, sortie ou guide perdu");assert(restored.levels[3].events[0].done&&restored.progress.artifacts.length===1,"événement ou artefact perdu");});

test("reprise répétée : aucun objet restauré n’est partagé ou dupliqué",()=>{const snapshot=(id,x)=>({type:"book_red",userData:{type:"book_red",instanceId:id,level:2},position:[x,.1,2],rotation:[0,0,0,"XYZ"],scale:[1,1,1]}),save=createExplorationSave({seed:99,inventory:[snapshot("inventory-book",1)],levels:{2:{...createEmptyLevelSave(),objects:[snapshot("ground-book",3)]}}});for(let cycle=0;cycle<20;cycle++){const parsed=parseExplorationSave(serializeExplorationSave(save)),inventory=parsed.inventory.map(restoreItem),ground=parsed.levels[2].objects.map(restoreItem),ids=[...inventory,...ground].map(object=>object.userData.instanceId);assert(ids.length===2&&new Set(ids).size===2,"objet dupliqué après reprise");assert(inventory[0]!==ground[0]&&inventory[0].geometry!==ground[0].geometry,"ressource Three.js partagée entre restaurations");inventory.forEach(disposeObjectTree);ground.forEach(disposeObjectTree);}});

test("guide et artefacts : identité, disparition et persistance par niveau",()=>{const source=readFileSync(new URL("../js/game.js",import.meta.url),"utf8"),save=createExplorationSave({seed:15,progress:{guide:{active:false,phase:"completed",level:2,position:[1,.2,2],completedLevels:[1,2]}}}),restored=parseExplorationSave(serializeExplorationSave(save));assert(restored.progress.guide.completedLevels.join(",")==="1,2","niveaux terminés du guide perdus");assert(source.includes('id=`level-${level}:guide-artifact`'),"identité d’artefact non liée au niveau");assert(source.includes("guideCompletedLevels.add(level)")&&source.includes('guideActive=false;guidePhase="completed"'),"guide terminé encore actif");assert(source.includes("!guideCompletedLevels.has(enteredLevel)")&&source.includes('guidePhase=guideCompletedLevels.has(enteredLevel)?"completed":"inactive"'),"guide recréé au retour");assert(source.includes("const artifactIndex=artifacts.indexOf(object);if(artifactIndex>=0)artifacts.splice")&&source.includes("artifact.parent===scene"),"artefact ramassé encore animé au sol");assert(!source.includes("Math.hypot(camera.position.x-artifact.position.x"),"artefact supprimé par distance");});

test("fin du guide niveau 1 : mur intact, descente au seuil et artefact au pied",()=>{const source=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");assert(source.includes('guidePhase="finish"')&&source.includes("chunk.originZ+chunk.worldLength-.55"),"approche finale du faux mur absente");assert(source.includes('else if(guidePhase==="finish")')&&source.includes("beginGuideCompletion(now)"),"disparition déclenchée avant l’arrivée au mur");assert(source.includes("createArtifact(companion.position)"),"artefact non déposé à la position finale du guide");assert(source.includes("exitOpened?chunk.walls.filter(mesh=>mesh!==exitWall):chunk.walls"),"faux mur encore bloquant après le guide");assert(!source.includes("exitWall.position.y=")&&!source.includes("exitWall.parent?.remove(exitWall)"),"faux mur déplacé ou supprimé");});

test("guide niveau 2 : apparition dans une position libre ou attente",()=>{const origin={x:5,z:5},blocked=(x,z)=>x>5,inside=(x,z)=>x>=0&&x<=10&&z>=0&&z<=10,spawn=findSafeGuideSpawn(origin,{collides:blocked,contains:inside,minDistance:1,maxDistance:2,ringStep:.5,samples:16,startAngle:0});assert(spawn&&inside(spawn.x,spawn.z)&&!blocked(spawn.x,spawn.z),"position sûre non trouvée");assert(Math.hypot(spawn.x-origin.x,spawn.z-origin.z)>=1,"guide trop proche du joueur");assert(findSafeGuideSpawn(origin,{collides:()=>true,contains:inside,minDistance:1,maxDistance:1,samples:8})===null,"apparition forcée dans un mur");const source=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");assert(source.includes("const spawn=safeGuideSpawn();if(!spawn){rebirthAt=now+250;}"),"nouvelle tentative sûre absente");});

test("i18n : langues, repli, notification et traduction du document",()=>{assert(LOCALE_STORAGE_KEY==="backrooms.locale.v1"&&SUPPORTED_LOCALES.join(",")==="fr,en","configuration i18n invalide");let notified=0;const unsubscribe=subscribeLocale(()=>notified++);setLocale("fr",{persist:false});assert(getLocale()==="fr"&&translate("language.label")==="Langue","français indisponible");setLocale("en",{persist:false});assert(getLocale()==="en"&&translate("language.label")==="Language"&&notified===1,"anglais ou notification indisponible");assert(translate("missing.translation.key")==="missing.translation.key","repli de clé instable");const textNode={dataset:{i18n:"language.label"},textContent:""},ariaNode={dataset:{i18nAria:"language.label"},setAttribute(name,value){this[name]=value;}},frButton={dataset:{locale:"fr"},classList:{toggle(name,value){this.active=value;}}},enButton={dataset:{locale:"en"},classList:{toggle(name,value){this.active=value;}}},root={documentElement:{lang:""},querySelectorAll(selector){return selector==="[data-i18n]"?[textNode]:selector==="[data-i18n-aria]"?[ariaNode]:selector==="[data-locale]"?[frButton,enButton]:[];}};translateDocument(root);assert(root.documentElement.lang==="en"&&textNode.textContent==="Language"&&ariaNode["aria-label"]==="Language"&&!frButton.classList.active&&enButton.classList.active,"document non traduit");unsubscribe();setLocale("fr",{persist:false});});

test("i18n objets : clés stables et anciennes sauvegardes retraduites",()=>{setLocale("en",{persist:false});const legacy=createItem("plush",{userData:{name:"PELUCHE USÉE",description:"Ancien texte français",powered:true}});assert(legacy.userData.name==="POWERED PLUSH"&&legacy.userData.nameKey==="item.plush.poweredName","ancien texte non remplacé");const snapshot=snapshotItem(legacy);assert(!("name" in snapshot.userData)&&!("description" in snapshot.userData),"texte traduit encore persisté");const restored=restoreItem(snapshot);assert(restored.userData.name==="POWERED PLUSH"&&restored.userData.descriptionKey==="item.plush.poweredDescription","objet restauré non traduit");disposeObjectTree(legacy);disposeObjectTree(restored);setLocale("fr",{persist:false});});

test("i18n commandes : catalogues complets et paramètres cohérents",()=>{const diagnostics=getTranslationDiagnostics();assert(diagnostics.valid,`catalogues incohérents : ${JSON.stringify(diagnostics)}`);for(const locale of["fr","en"]){setLocale(locale,{persist:false});for(const action of INPUT_CATALOG){assert(translate(action.labelKey)!==action.labelKey,`action absente en ${locale} : ${action.labelKey}`);assert(translate(action.categoryKey)!==action.categoryKey,`catégorie absente en ${locale} : ${action.categoryKey}`);}}setLocale("en",{persist:false});assert(formatInputCode("MouseBack")==="MOUSE 4"&&formatInputCode("ShiftLeft")==="SHIFT","codes anglais incorrects");setLocale("fr",{persist:false});assert(formatInputCode("MouseBack")==="SOURIS 4"&&formatInputCode("ShiftLeft")==="MAJ","codes français incorrects");});

test("reportage v1 : faits confirmés sans historique inventé",()=>{const water=createItem("water_half",{userData:{instanceId:"level-1:water_half:0",level:1,sips:1}}),artifactOne=createItem("artifact",{userData:{instanceId:"level-1:guide-artifact",level:1,guideReward:true}}),artifactTwo=createItem("artifact",{userData:{instanceId:"level-2:guide-artifact",level:2,guideReward:true}}),save=createExplorationSave({seed:737373,level:2,elapsed:321,thirst:34,hunger:21,inventory:[snapshotItem(water),snapshotItem(artifactOne),snapshotItem(artifactTwo)],progress:{exitOpened:true,doors:[{sourceLevel:2,targetLevel:3,angle:.5}],guide:{active:false,phase:"completed",level:2,position:[0,1.78,0],completedLevels:[1,2]}},levels:{1:createEmptyLevelSave(),2:createEmptyLevelSave()}}),report=buildSaveReport(save);assert(report?.coverage==="partial"&&report.subject.level===2&&report.inventory.length===3,"rapport v1 incomplet");assert(report.resources.waterSips===1&&report.resources.artifacts===2,"ressources incorrectes");assert(report.milestones.some(entry=>entry.id==="guide-complete:1")&&report.milestones.some(entry=>entry.id==="exit-opened:1"),"étapes confirmées absentes");assert(report.route.length===1&&report.route[0].level===2&&report.encounters.length===0&&!report.sections.encounters,"historique inventé");assert(report.inventory.filter(item=>item.type==="artifact").map(item=>item.instanceId).join(",")==="level-1:guide-artifact,level-2:guide-artifact","artefacts confondus");disposeObjectTree(water);disposeObjectTree(artifactOne);disposeObjectTree(artifactTwo);});

test("reportage : absence et sauvegarde invalide restent masquées",()=>{const absent=readSaveReport({read:()=>({ok:true,status:"empty",save:null})}),invalid=readSaveReport({read:()=>({ok:true,status:"loaded",save:{version:1}})});assert(!absent.available&&absent.status==="empty"&&!invalid.available&&invalid.status==="invalid","reportage affichable sans sauvegarde reconnue");});

test("reportage accueil : section conditionnelle, rubriques sûres et actualisation",()=>{const html=readFileSync(new URL("../index.html",import.meta.url),"utf8"),source=readFileSync(new URL("../js/landing.js",import.meta.url),"utf8");assert(/id="exploration-report"[^>]*hidden/.test(html),"reportage visible par défaut");for(const section of["inventory","route","milestones","encounters","resources"])assert(html.includes(`data-report-section="${section}" hidden`),`rubrique ${section} visible sans données`);assert(source.includes("readSaveReport()")&&source.includes("reportSection.hidden=true")&&source.includes("reportSection.hidden=false"),"visibilité non reliée à la sauvegarde");for(const unavailable of["route-history","encounter-history","resource-history"])assert(source.includes(`unavailable.includes("${unavailable}")`),`historique indisponible exposé : ${unavailable}`);assert(source.includes('addEventListener("storage"')&&source.includes('addEventListener("backrooms:save-changed"'),"actualisation du reportage absente");assert(source.includes("textContent=String(text)")&&!source.includes("report.subject.position")&&!source.includes("report.subject.orientation"),"données techniques ou HTML brut exposés");});

test("reportage traduit : variantes stables, pluriels, nombres et dates localisés",()=>{const variants=new Set();for(let seed=1;seed<=30;seed++)variants.add(deterministicReportVariant(seed,"landing-intro",3));assert(variants.size>1,"variantes narratives inactives");assert(deterministicReportVariant(424242,"landing-intro",3)===deterministicReportVariant(424242,"landing-intro",3),"variante instable pour une même seed");assert(reportPluralKey("report.route.visits",1,"en")==="report.route.visits.one"&&reportPluralKey("report.route.visits",2,"fr")==="report.route.visits.other","pluriels localisés incorrects");assert(formatReportNumber(1234,"en").includes("1")&&formatReportNumber(1234,"fr").includes("1"),"nombre localisé absent");assert(formatReportDate("invalid","fr")==="—"&&formatReportDate(1723370400000,"en")!==formatReportDate(1723370400000,"fr"),"date locale incorrecte");});

test("reportage bouteilles : indicateur générique relié aux contenants",()=>{const source=readFileSync(new URL("../js/landing.js",import.meta.url),"utf8"),styles=readFileSync(new URL("../assets/styles.css",import.meta.url),"utf8");assert(source.includes("renderUnitIndicator(row.units")&&source.includes("units:item.state.container??null"),"contenants non reliés à l’indicateur générique");assert(styles.includes(".unit-indicator--cells")&&styles.includes(".unit-indicator--bar")&&styles.includes(".unit-indicator--text"),"modes visuels de l’indicateur absents");});

test("reportage robuste : stockage indisponible, JSON corrompu et version future masqués",()=>{const unavailable=readSaveReport({read:()=>({ok:false,status:"unavailable",save:null})}),corruptValues=new Map([[SAVE_STORAGE_KEY,"{cassé"]]),futureValues=new Map([[SAVE_STORAGE_KEY,JSON.stringify({version:999})]]),native=values=>({getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)}),corrupt=readSaveReport(createExplorationSaveStorage({storage:native(corruptValues)})),future=readSaveReport(createExplorationSaveStorage({storage:native(futureValues)}));assert(!unavailable.available&&unavailable.status==="unavailable","stockage indisponible affiché");assert(!corrupt.available&&corrupt.status==="invalid","JSON corrompu affiché");assert(!future.available&&future.status==="incompatible","version future affichée");});

test("reportage complet : objets identiques distincts, retours, rencontres et bouteilles partielles",()=>{const objects=[createItem("book_red",{userData:{instanceId:"book-l1",level:1}}),createItem("book_red",{userData:{instanceId:"book-l2",level:2}}),createItem("water_full",{userData:{instanceId:"water-a",level:1,sips:3}}),createItem("water_half",{userData:{instanceId:"water-b",level:2,sips:1}})],save=createExplorationSave({seed:8181,level:2,inventory:objects.map(snapshotItem),journal:{coverage:"complete",visitedLevels:[{level:1,firstVisitedAt:0,entries:2},{level:2,firstVisitedAt:30,entries:1}],transitions:[{id:"go",source:1,target:2,elapsed:30},{id:"back",source:2,target:1,elapsed:45}],milestones:[{id:"known",type:"guide-awake",level:1,elapsed:10}],resources:{water_full:{taken:1}},encounters:{watcher:{spawned:3,observed:2,chased:1,vanished:2,levels:{2:3}}}}}),report=buildSaveReport(save);assert(report.inventory.length===4&&report.inventory.filter(item=>item.type==="book_red").length===2,"objets de niveaux différents fusionnés");assert(report.resources.waterSips===4,"gorgées partielles incorrectes");assert(report.route[0].entries===2&&report.transitions.length===2&&report.encounters[0].observed===2,"retours ou rencontres perdus");objects.forEach(disposeObjectTree);});

test("journal longue session : toutes les collections restent bornées",()=>{const journal=new ExplorationJournal();for(let index=1;index<=400;index++){journal.visitLevel(index,index).crossTransition(`transition-${index}`,index,index+1,index);journal.completeMilestone(`milestone-${index}`,index,index,{type:"generic"});journal.recordResource(`resource-${index}`,"taken",1,index);journal.recordEncounter(`creature-${index}`,"spawned",index,index);}const snapshot=journal.snapshot();assert(snapshot.visitedLevels.length===JOURNAL_LIMITS.visitedLevels,"visites non bornées");assert(snapshot.transitions.length===JOURNAL_LIMITS.transitions&&snapshot.milestones.length===JOURNAL_LIMITS.milestones,"chronologie non bornée");assert(Object.keys(snapshot.resources).length===JOURNAL_LIMITS.resourceTypes&&Object.keys(snapshot.encounters).length===JOURNAL_LIMITS.encounterTypes,"registres non bornés");});

test("reportage confidentiel : aucune coordonnée, métadonnée ou étape future n’est publiée",()=>{const source=readFileSync(new URL("../js/landing.js",import.meta.url),"utf8"),gameSource=readFileSync(new URL("../js/game.js",import.meta.url),"utf8"),styles=readFileSync(new URL("../assets/styles.css",import.meta.url),"utf8");for(const forbidden of["report.subject.position","report.subject.orientation","entry.metadata","JSON.stringify(report)"])assert(!source.includes(forbidden),`donnée interne rendue : ${forbidden}`);assert(source.includes('translated===key?translate("report.milestone.generic")'),"jalon inconnu révélateur");assert(gameSource.includes('saveStorage.remove();refreshSaveUi()')&&gameSource.includes('new CustomEvent("backrooms:save-changed")'),"suppression non répercutée immédiatement");assert(styles.includes("@media(max-width:750px)")&&styles.includes(".report-grid{grid-template-columns:1fr}"),"mise en page mobile absente");});

test("journal d’exploration : visites, événements uniques, ressources et rencontres",()=>{const journal=new ExplorationJournal();journal.visitLevel(2,12).visitLevel(1,18).visitLevel(2,24).crossTransition("hidden-exit",1,2,12).recordResource("water_full","taken",1,1).recordResource("water_full","consumed",2,2).recordEncounter("watcher","spawned",2,30).recordEncounter("watcher","observed",2,32);assert(journal.completeMilestone("guide-complete:1",1,40,{type:"guide-complete"}),"jalon initial refusé");assert(!journal.completeMilestone("guide-complete:1",1,41,{type:"guide-complete"}),"jalon unique dupliqué");const snapshot=journal.snapshot(),levelTwo=snapshot.visitedLevels.find(entry=>entry.level===2);assert(snapshot.coverage==="complete"&&levelTwo.entries===2&&snapshot.transitions[0].source===1&&snapshot.transitions[0].target===2,"route non enregistrée");assert(snapshot.resources.water_full.taken===1&&snapshot.resources.water_full.consumed===2,"ressources non comptées");assert(snapshot.encounters.watcher.spawned===1&&snapshot.encounters.watcher.observed===1&&snapshot.milestones.length===1,"rencontres ou jalons incorrects");const restored=new ExplorationJournal(snapshot).snapshot();assert(JSON.stringify(restored)===JSON.stringify(snapshot),"journal non restaurable à l’identique");});

test("instrumentation : jeu et créatures publient les événements du reportage",()=>{const gameSource=readFileSync(new URL("../js/game.js",import.meta.url),"utf8"),creatureSource=readFileSync(new URL("../js/systems/creature-registry.js",import.meta.url),"utf8");for(const hook of["recordResource","completeMilestone","crossTransition","visitLevel","recordEncounter"])assert(gameSource.includes(hook),`hook de journal absent : ${hook}`);for(const event of['event:"spawned"','event:"observed"','event:"chased"'])assert(creatureSource.includes(event),`événement créature absent : ${event}`);assert(creatureSource.includes("event:reason")&&creatureSource.includes('#remove(index,"vanished"'),"disparition de créature absente");assert(creatureSource.includes('{notify:false}'),"déchargement de carte compté comme rencontre");});

test("sauvegarde automatique : attente, intervalle, immédiat et nettoyage",()=>{let writes=0,tick=null,cleared=false;const storage={write(save){writes++;return{ok:true,status:"saved",updatedAt:save.meta.updatedAt};}},controller=new AutosaveController({snapshot:()=>createExplorationSave({seed:123}),storage,intervalMs:5000,setIntervalFn:callback=>{tick=callback;return 9;},clearIntervalFn:id=>{cleared=id===9;}});assert(controller.flush().status==="not-ready","écriture avant restauration");controller.start();assert(writes===0&&typeof tick==="function","intervalle non préparé");tick();assert(writes===1,"premier intervalle non sauvegardé");tick();assert(writes===1,"état propre réécrit");controller.markDirty({reason:"item",immediate:true});assert(writes===2,"modification importante non sauvegardée");controller.markDirty({immediate:false});controller.stop({flush:true});assert(writes===3&&cleared&&!controller.ready,"arrêt ou vidage invalide");});

test("sauvegarde automatique : hooks importants présents dans le jeu",()=>{const source=readFileSync(new URL("../js/game.js",import.meta.url),"utf8");for(const hook of["take-item","combine","power-plush","drop-item","drink","level-change","before-unload","return-home"])assert(source.includes(hook),`hook absent : ${hook}`);assert(source.includes("intervalMs:15000")&&source.includes("autosave?.stop()"),"intervalle ou nettoyage absent");});

test("interface de sauvegarde : continuer, résumé, pause et confirmations",()=>{const html=readFileSync(new URL("../index.html",import.meta.url),"utf8"),source=readFileSync(new URL("../js/game.js",import.meta.url),"utf8"),styles=readFileSync(new URL("../assets/controls.css",import.meta.url),"utf8");for(const id of["continue-game","delete-save","save-summary","pause-save","pause-load","save-status"])assert(html.includes(`id="${id}"`),`élément absent : ${id}`);assert(html.includes('id="continue-game" class="play-button continue-button" type="button" hidden')&&styles.includes(".continue-button[hidden]{display:none}"),"bouton Continuer visible sans sauvegarde");assert(source.includes("function refreshSaveUi()")&&source.includes('t("game.save.summary"')&&source.includes("save.meta.updatedAt"),"résumé non révélateur absent");assert(source.includes("startGame(result.save)")&&source.includes("createGame(result.save)"),"reprise accueil ou pause absente");for(const key of["game.save.confirmNew","game.save.confirmDelete","game.save.confirmLoad"])assert(source.includes(key),`confirmation traduisible absente : ${key}`);assert(source.includes('event.code!=="Escape"||!paused||pauseMenu.hidden')&&source.includes('[globalThis,"keydown",pauseEscape]'),"fermeture de pause avec Échap absente ou non nettoyée");});

test("commandes complètes : chaque action répond dans les deux profils",()=>{class Target{constructor(){this.handlers=new Map();}addEventListener(type,handler){const list=this.handlers.get(type)??new Set();list.add(handler);this.handlers.set(type,list);}removeEventListener(type,handler){this.handlers.get(type)?.delete(handler);}emit(type,event={}){for(const handler of this.handlers.get(type)??[])handler({preventDefault(){},repeat:false,ctrlKey:false,altKey:false,metaKey:false,...event});}}for(const profile of["azerty","qwerty"]){const target=new Target(),input=new InputManager({target,bindings:INPUT_PROFILES[profile]}),pressed=new Set(),released=new Set();for(const action of INPUT_CATALOG){input.onPress(action.id,()=>pressed.add(action.id));input.onRelease(action.id,()=>released.add(action.id));const code=INPUT_PROFILES[profile][action.id][0],key=code.startsWith("Key")?code.slice(3).toLowerCase():code.startsWith("Digit")?code.slice(5):undefined;target.emit("keydown",{code,key});target.emit("keyup",{code,key});}assert(pressed.size===INPUT_CATALOG.length,`actions manquantes en ${profile}`);assert(released.size===INPUT_CATALOG.length,`relâchements manquants en ${profile}`);input.dispose();}});

test("remappage complet : douze commandes personnalisées persistent",()=>{class Storage{constructor(){this.values=new Map();}getItem(key){return this.values.get(key)??null;}setItem(key,value){this.values.set(key,String(value));}}const storage=new Storage(),codes=["Numpad0","Numpad1","Numpad2","Numpad3","Numpad4","Numpad5","Numpad6","Numpad7","Numpad8","Numpad9","Home","End"];let preferences=selectInputProfile("qwerty",storage);INPUT_CATALOG.forEach((action,index)=>{const result=remapInputBinding(preferences,action.id,codes[index],{storage});assert(result.changed,`remappage refusé : ${action.id}`);preferences=result.preferences;});const restored=loadInputPreferences(storage);assert(restored.profile==="custom"&&restored.layout==="qwerty","profil personnalisé perdu");INPUT_CATALOG.forEach((action,index)=>assert(restored.bindings[action.id][0]===codes[index],`touche non persistée : ${action.id}`));assert(validateInputBindings(restored.bindings).valid,"configuration complète invalide");const reset=selectInputProfile("azerty",storage);assert(reset.profile==="azerty"&&reset.bindings[INPUT_ACTIONS.MOVE_FORWARD][0]==="KeyZ","changement de profil après personnalisation invalide");});

test("stockage indisponible : les commandes restent utilisables en mémoire",()=>{const storage={getItem(){throw new Error("accès interdit");},setItem(){throw new Error("quota");}},loaded=loadInputPreferences(storage);assert(loaded.profile==="azerty"&&validateInputBindings(loaded.bindings).valid,"repli de lecture invalide");const selected=selectInputProfile("qwerty",storage);assert(selected.profile==="qwerty"&&selected.source==="memory"&&validateInputBindings(selected.bindings).valid,"repli d’écriture invalide");});

test("cycle des inputs : aucune écoute ni action ne survit à la destruction",()=>{class Target{constructor(){this.handlers=new Map();}addEventListener(type,handler){const list=this.handlers.get(type)??new Set();list.add(handler);this.handlers.set(type,list);}removeEventListener(type,handler){this.handlers.get(type)?.delete(handler);}count(){return[...this.handlers.values()].reduce((sum,list)=>sum+list.size,0);}}const target=new Target();for(let index=0;index<30;index++){const input=new InputManager({target,bindings:index%2?INPUT_PROFILES.azerty:INPUT_PROFILES.qwerty});input.activate(INPUT_ACTIONS.RUN,"test");input.dispose();assert(target.count()===0,"écouteur accumulé après destruction");assert(!input.isActive(INPUT_ACTIONS.RUN),"action maintenue après destruction");}});

test("libellés spéciaux : les noms longs restent explicites",()=>{for(const[code,label]of [["Space","ESPACE"],["Enter","ENTRÉE"],["ShiftLeft","MAJ"],["ControlRight","CTRL"],["MouseForward","SOURIS 5"]])assert(formatInputCode(code)===label,`libellé incorrect pour ${code}`);});

audio.stop();
let debugImports=0;
const normalDebugSession=await loadOptionalDebug(Object.freeze({}),{search:"",importer:async()=>{debugImports++;throw new Error("import inattendu");}});
assert(!normalDebugSession.requested&&!normalDebugSession.loaded&&debugImports===0,"le mode normal tente de charger debug");
console.log("✓ jeu normal : aucun chargement du dossier debug");
let unavailableReported=false;
const missingDebugSession=await loadOptionalDebug(Object.freeze({}),{search:"?debug=1",importer:async()=>{debugImports++;throw new Error("404 debug/debug.js");},onUnavailable:()=>unavailableReported=true});
assert(missingDebugSession.requested&&!missingDebugSession.loaded&&unavailableReported&&debugImports===1,"module debug absent non contenu");
missingDebugSession.dispose();
console.log("✓ production ?debug=1 : module absent sans blocage");
console.log("\n69 scénarios de parcours et 2 scénarios d’absence debug validés.");
